### ISSUE TITLE
Smarter pagination for history

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1019]
Followup from #995, see https://github.com/mozilla/application-services/pull/995#issuecomment-483883406 for details. In particular, the current implementation is O(n^2) to iterate over all records.

We probably want to use some trickery to make things more efficient `OFFSET`, for example: https://github.com/mozilla-services/server-syncstorage/blob/9de1850199cff3a2771cbf752cf79a2391732456/syncstorage/storage/sql/__init__.py#L414

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-77)

**Comment by lyuyuan** [comment]
I will try this :)

**Comment by lyuyuan** [comment]
Hi @rfk and @thomcc ! I just read the pagination trickery example in server-syncstorage repo, and I would like to confirm with you about what need to be done in this issue if you have time. So,
1. [`get_page_visit`](https://github.com/mozilla/application-services/blob/1c76286f61dd4613d8aeb2700ae4dfb6706bfa7b/components/places/src/storage/history.rs#L1120) should return `HistoryVisitInfos` along with a "offset token" (bound and offset). `bound` is the last (earliest) `visit_date` value of the items, and `offset` is the number of items whose `visit_data` is equal to `bound`.
2. The caller of `get_page_visit` should use the "offset token" to do the desired limit & offset and pass the token value back in in order to query next page.
Does this sound correct? Thanks!

**Comment by rfk** [comment]
That sounds broadly correct to me. The resulting query will then contain a `WHERE visit_date <= {bound}` clause and an `OFFSET {offset}`, which allows it to execute in two steps:

* Quickly skip over the dates we've already completely processed, using the index on `visit_date`.
* More slowly skip over items with a matching `visit_date` that we've already processed, using the `OFFSET`.

If you're feeling adventurous, it may be worth trying to do a before/after benchmark to see how long it takes to page through a large history dataset using both the old method and this new method. I don't expect any performance regressions even for small datasets, but my expectations don't always match reality...
