### ISSUE TITLE
Review use of crypto primitives in rust-ece crate

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1068]
(Not strictly related to the work on NSS, but close enough that I'm putting the "NSS" label on it)

In #958 we will implement an NSS backend for the rust-ece crate, which is used by our push and send-tab components:

  https://github.com/mozilla/rust-ece

We also need to review the way that this create uses said crypto primitives to confirm that it correctly and safely implements the ECE spec.  In a previous email conversation with @martinthomson he said:

"""
I took a look at what you have and found at least one snafu, but I didn't spend that long with it.
"""

So we've definitely got at least one change to make on this front :-)

@martinthomson, could you please take a look at the current code in the rust-ece crate and let us know about this and any other snafus?  I think it will be valuable even while the NSS migration is ongoing, because we can use any lessons learned to feed in to the NSS migration work.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-64)
┆Story Points: 3
┆Sprint: SYNC - 2019-07-05
┆Epic: Trusted Crypto

**Comment by martinthomson** [comment]
Do you still need the old `aesgcm` code?  There's a fair bit of baggage associated with that.

**Comment by martinthomson** [comment]
The snafu I remember (and can't find now, which is good) was a mismatch between two constants that had the same value.  A tag length being used for a key size, or vice versa.

I didn't look in detail, but it looks like generally sound code, but further to my last comment, I would suggest cutting this down severely.  Web push doesn't need very much code to implement correctly and this is more than you really need.  

* drop old content codings
* drop multiple records
* simplify padding (the code you have seems to be copied from my more general padding code, which pads across multiple records)

Then there are little things, like the fact that the code allows parameters to be passed in.  You don't need that in the new content coding.  The encrypt routine can generate a salt value and the decrypt routine has it automatically.  You might want to tune padding and record size for the first record, but given the size constraints on web push, the record size can just be fixed to 4096 without parameterization.

With that, you should be able to cut this down to a quarter of its size without affecting interoperability at all.

Nits:

The comment on generate_iv is wrong.

The use of offsets in reading and generating the header is inconsistent.  There are some constants and some raw values.  It's hard to read.

**Comment by rfk** [comment]
> Do you still need the old aesgcm code? There's a fair bit of baggage associated with that.

@eoger or @jrconlin are you able to comment on this?

**Comment by jrconlin** [comment]
In short "yes". The problem is that there are a number of in use WebPush libraries out in the wild that still send `aesgcm` formatted messages. I've reached out to a number of the big ones to strongly encourage them to use the Spec Standard, but we're still seeing about 4MM `aesgcm` update messages a day,vs. 10K `aes128gcm` messages per day.

I have the feeling we would need to be a good deal more vocal about disabling `aesgcm` support if we want to get publishers using the correct content encoding, and return some error code (415?) indicating that the Content Type is no longer valid. Granted, publishers don't generally pay attention to return codes so we'd probably just see a huge drop in messages, and the current mobile client would have no idea why existing subscriptions stopped working. 

We should probably wait to deprecate the `aesgcm` format until after the new client code has rolled out.

**Comment by martinthomson** [comment]
I see, so the intent is to make this part of a receiver (Firefox?).  In that case, the `aesgcm` support is probably necessary.

**Comment by rfk** [comment]
> I see, so the intent is to make this part of a receiver (Firefox?).

Eventually, yes - for example to power a future webpush implementation for Fenix.

**Comment by rfk** [comment]
> drop multiple records

This seems like it would be a nice simplification. Despite being named "rust-ece", as far as I can tell the crate is quite highly specialized to the [webpush-encryption](https://tools.ietf.org/html/draft-ietf-webpush-encryption-09) spec rather than the more generic [RFC8188](https://tools.ietf.org/html/rfc8188), and webpush-encryption says that applications [MUST encrypt a push message with a single record.](https://tools.ietf.org/html/draft-ietf-webpush-encryption-09#section-4).

@eoger @jrconlin do we have a requirement to keep the support for multiple records, perhaps for legacy reasons?

**Comment by rfk** [comment]
> do we have a requirement to keep the support for multiple records, perhaps for legacy reasons?

In fact I get the feeling that multiple record support is broken for the legacy `aesgcm` scheme anyway, because I don't see any logic to handle the difference in `rs` between the two schemes.  `aesgcm` treats `rs` as the *plaintext* record size:

  https://dxr.mozilla.org/mozilla-central/rev/aaae630f30291056f4f40bbd9e12a917309e401e/dom/push/PushCrypto.jsm#434

While `aes128gcm` treats it as the *ciphertext* record size:

  https://dxr.mozilla.org/mozilla-central/rev/aaae630f30291056f4f40bbd9e12a917309e401e/dom/push/PushCrypto.jsm#486

**Comment by jrconlin** [comment]
Sorry that I didn't see this until now. 

Multi-record support isn't really supported partly for the reasons you state. Plus the fact that the current clients don't really handle it either. You're right that this is more about the WebPush version of ECE rather than the larger version. If we get enough demand for full RFC spec ECE, I suppose we can add the additional features like proper multi-record support.
