### ISSUE TITLE
Question: a local script that runs tests before sending a pull request?

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#1069]
As part of our PR template we have a:

```
This PR builds and tests run cleanly
cargo test --all produces no test failures
cargo clippy --all --all-targets --all-features runs without emitting any warnings
cargo fmt does not produce any changes to the code
./gradlew ktlint detekt runs without emitting any warnings
```

Could we have a script like `check-my-pr.sh` that runs all of those? instead of running 4 commands ? do we have this already?

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-65)

**Comment by thomcc** [comment]
One issue is the last step is very slow to run, and only needs to happen if you changed kotlin. This is also an incomplete list, since you should run gradle tests if you made android changes, xcode tests if you changed swift, etc.

I played around with writing a prepush hook earlier, but never finished it (I don't remember how complete it was, it looks mostly there though, if a bit dated vs our current setup): https://gist.github.com/thomcc/be8387604727d8349c5f0e87320ec471

**Comment by vladikoff** [comment]
yea the `need_check_kotlin` idea totally makes sense. Maybe we can just do rust code for now as part of that script.

**Comment by bug-mirror** [comment]
from mtg: we should do it! but not clear what exactly this script should do

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

Closing as won't do for now
