### ISSUE TITLE
Password change for an account doesn't result in an `AUTHENTICATION` error code

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#1122]
Via @grigoryk on slack. He changed his password externally then tried to sync. The log showed

    D/libfxaclient_ffi: reqwest::async_impl::response: Response: '400 Bad Request' for https://oauth.accounts.firefox.com/v1/token

which is mapped to `FxaException$Unspecified`.  components/fxa-client/src/ffi.rs tries to map the internal FxA errors to these "app facing" errors, and it expects only 401 errors to mean unauthorized. But according to [the fxa docs](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/fxa-oauth-server/docs/api.md#errors), many 400 responses could also mean unauthorized. It's not clear if simply treating *all* 400s the same as 401 is the correct answer or not.

I think checking how lockbox reacts to this should be a priority.

cc @eoger

**Comment by rfk** [comment]
> It's not clear if simply treating all 400s the same as 401 is the correct answer or not.

Errnos `108` and `115` are the only ones I see that should be treated as `AUTHENTICATION` errors; the others typically indicate a more fatal logic error of some kind.  I think the server is probably incorrect here and should be using a `401` response status, and perhaps we should investigate that change as well, but I'm not sure what it might break.  Hopefully nothing, but you never know...

**Comment by rfk** [comment]
I can take a quick look at this one.

**Comment by rfk** [comment]
> 400 Bad Request' for https://oauth.accounts.firefox.com/v1/token

Actually, as of https://github.com/mozilla/application-services/pull/1055 we should no longer be hitting that endpoint. Instead we should be hitting one on the auth-server, which returns a different error number (for reasons). AFAICT the auth-server route *will* correctly use a `401` status code in this case rather than a `400`.

@grigoryk can you reproduce this behaviour on latest release of a-s, which should have the above endpoint change in it?

**Comment by jdragojevic** [comment]
Needs to be reproduced - expectation that this is fixed.

**Comment by rfk** [comment]
Trying this out in a local build of today's Fenix (`b54628210bd72ea7ecee20e088e084453d4c8795 `) I did the following:

* Sign in to Fenix
* Go back from account settings, then re-enter account settings to force UI refresh
* Hit "sync now"
* Confirm that it synced successfully, saying "last synced 0 minutes ago"
* Use desktop browser to change my account password
* Go back to Fenix, which is now showing "last synced 1 minute ago"
* Hit "sync now" again

It failed to sync, although the only reason I could tell is that it it remained on "last synced 1 minute ago". In logcat output I see:

```
05-21 11:09:50.494  3437  3796 D SyncWorker: Starting sync... Tagged as: [Immediate, mozilla.components.feature.sync.WorkManagerSyncWorker, Common]
05-21 11:09:50.494  3437  3796 D fxaclient_ffi: fxa_from_json
05-21 11:09:50.495  3437  3796 D fxaclient_ffi: fxa_get_token_server_endpoint_url
05-21 11:09:50.506  3437  3812 D fxaclient_ffi: fxa_get_access_token
05-21 11:09:51.243  3437  3812 W fxa_client::ffi: Authentication error: Error(
05-21 11:09:51.243  3437  3812 W fxa_client::ffi: 
05-21 11:09:51.243  3437  3812 W fxa_client::ffi: Remote server error: '401' '110' 'Unauthorized' 'Invalid authentication token in request signature' 'https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format')
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: Work [ id=78f480d4-02f9-4566-9fe0-2c6f8ea12c34, tags={ Immediate, mozilla.components.feature.sync.WorkManagerSyncWorker, Common } ] failed because it threw an exception/error
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: java.util.concurrent.ExecutionException: mozilla.appservices.fxaclient.FxaException$Unauthorized: Remote server error: '401' '110' 'Unauthorized' 'Invalid authentication token in request signature' 'https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format'
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:289)
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at java.lang.Thread.run(Thread.java:764)
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: Caused by: mozilla.appservices.fxaclient.FxaException$Unauthorized: Remote server error: '401' '110' 'Unauthorized' 'Invalid authentication token in request signature' 'https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format'
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:44)
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at mozilla.appservices.fxaclient.FirefoxAccount.getAccessToken(FirefoxAccount.kt:597)
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at mozilla.components.service.fxa.FirefoxAccount$getAccessToken$1.invokeSuspend(FirefoxAccount.kt:176)
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
05-21 11:09:51.257  3437  3455 E WM-WorkerWrapper: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
05-21 11:09:51.259  3437  3455 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=78f480d4-02f9-4566-9fe0-2c6f8ea12c34, tags={ Immediate, mozilla.components.feature.sync.WorkManagerSyncWorker, Common } ]
```

Which looks like the expected `401` error, which should turn into an `AUTHENTICATION` error as required.

However, it's not clear to me if the app is supposed to be recovering from this situation automatically. It's certainly not prompting me to re-authenticate.

Quitting the app and restarting doesn't seem to help. In fact it makes things slightly worse, because it discards my cached profile info and cannot re-fetch it, so it shows me as being signed in to a generic "Firefox Account":

![Capture](https://user-images.githubusercontent.com/34695/58061676-8c549e00-7bba-11e9-8b89-7f5caa0db745.PNG)

Signing out and back in fixes things, as expected.

**Comment by rfk** [comment]
@grigoryk could you please help us understand whether this bug is sufficiently resolved, or what the next steps are here?

**Comment by grigoryk** [comment]
Since the `FxaException$Unauthorized` is the error being surfaced now, I expect that this is sufficiently resolved. Application level error surfacing are part `a-c`, part `fenix` work on top of this.

**Comment by rfk** [comment]
👍  thanks!
