### ISSUE TITLE
Expose hashed_fxa_uid from logins over the ffi so lockbox can use it

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/application-services#1154]
blocks https://github.com/mozilla-lockwise/lockwise-ios/issues/949 and https://github.com/mozilla-lockbox/lockbox-android/issues/645

cc @thomcc @sashei

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-45)
┆Story Points: 1
┆Sprint: SYNC - 2019-07-19
┆Epic: Lockwise Support

**Comment by thomcc** [comment]
#1112 will do this for android, and can probably hack it in for iOS without much work. If you need it before then, we can do it explicitly, but we'd probably rather not.

**Comment by rfk** [comment]
>  If you need it before then,

@linacambridge are we able to give the Lockwise folks some sense of when "then" is, to help decide whether they need this before then?

**Comment by linacambridge** [comment]
Let's do this in a separate PR, in case #1112 gets held up. @irrationalagent, are y'all only planning to use this for events now?

I was thinking we should probably have Lockbox emit Sync pings, too, at least so that we can see sync failures...but that's a separate discussion from this, since you want to tag your own metrics with the hashed UID, too.

**Comment by irrationalagent** [comment]
yea, this would just be for the in-app lockbox event telemetry for now. I do think having a sync ping from lockbox would be useful too, but we can punt on that for the time being as this is all that's blocking us from joining lockbox data across platforms within user.
