### ISSUE TITLE
Investigate whether current behaviour described issue #508 will break desktop

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/application-services#1185]
https://github.com/mozilla/application-services/issues/508

**Comment by mhammond** [comment]
As Thom mentioned in #508, this shouldn't affect desktop because the dates go via [this function](https://searchfox.org/mozilla-central/rev/662de518b1686c4769320d6b8825ce4864c4eda0/toolkit/components/places/PlacesUtils.jsm#518) and are stored as ms.

However, this is a problem for Firefox for iOS - [it considers visits equal based on microseconds](https://github.com/mozilla-mobile/firefox-ios/blob/master/Storage/Visit.swift#L60) and [so does Fennec](https://searchfox.org/mozilla-central/rev/662de518b1686c4769320d6b8825ce4864c4eda0/mobile/android/services/src/main/java/org/mozilla/gecko/sync/repositories/domain/HistoryRecord.java#147) - although I might be missing some subtlety here.

So it sounds like we really must do something here

**Comment by mhammond** [comment]
Actually, I'm not so sure. We'll have no interop issues with desktop, and we will have identical interop issues with other mobile implementation to the ones desktop already has. I'm going to close this and continue the discussion in #508
