### ISSUE TITLE
Several reports of "endless syncing" in Lockwise for Android

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1235]
The Play Store reviews for Lockbox for Android include a repeated thing of "the app doesn't sync my passwords, it just keeps trying to sync forever".  Examples include:

* "stalled at "syncing" passwords stage. never completes sync. Signed out and tried again. Same result. this is not ready for prime time yet"
* "Downloaded the app a week ago and it has not been able to sync my passwords. I've reinstalled, did not fix. I get through the setup process fine, but then it endlessly says "Syncing your logins..." Even with good internet connection"
* "Initial sync never completed, or possibly even started. From checking the app details, it appears to have never used data. So something is fundamentally broken."
* "Constant syncing. Never stops. Tried turning off WiFi and rely on data. No different. Very poor."

I don't know what's up with this, but maybe it's something we can help @sashei and co debug.  Do we have appropriate timeouts set on this operation? Are we deadlocking somewhere trying to write to the DB? Suggestions welcome how we might investigate this further.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-19)
┆Story Points: 8
┆Epic: Lockwise Support

**Comment by mhammond** [comment]
I saw something like this trying to get the FxA UID hooked up. I ended up coming to the conclusion that any error from android-components or from us would cause these symptoms. The error in my case was my own fault, but I was very surprised to find no logs, no "oops, something went wrong" ui etc.

(I didn't file a bug at the time because it's tricky to work out what the right thing is - showing an "oops" message doesn't actually help, asking the user to use logcat probably doesn't help, so this "spinning" doesn't seem much worse than all the other options I could come up with... That said though, ensuring stuff ends up on logcat is probably actionable and worthwhile)

**Comment by rfk** [comment]
This happened to me once just now, but when I quit the app and cam back in the sync worked again. So I wonder if it was some transient error that got dropped.

**Comment by rfk** [comment]
We saw this in syncfest today when we did a password change on another device, the Lockwise app did not detect that its auth token has been revoked and it just keep on "syncing your logins..."

**Comment by eoger** [comment]
This should be resolved by using `clearAccessTokenCache` introduced by https://github.com/mozilla/application-services/pull/1244.
