### ISSUE TITLE
Allow fxa-client consumers to specify authorization action

### ISSUE THREAD

**Issue by sashei** [mozilla/application-services#124]
In custom implementations of the OAuth flow, implementers are able to specify an `action` (one of `email`, `signup`, `signin`, or `force_auth`) in the [request parameters](https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#request-parameters-5) for the version of the OAuth login they would like to use. Ideally, the `beginOAuthFlow()` method signature could be extended to support the `action` desired by consumers of the library.

**Comment by vladikoff** [comment]
@rfk @shane-tomlinson do we want to support this or do we do `email` flow everywhere? 

(Alex says do email-first flow everywhere)

**Comment by rfk** [comment]
> (Alex says do email-first flow everywhere)

I was coming here to say something similar :-)

I think we intend for email-first to be the default flow everywhere, but if the app already knows the uid and/or email address of the user who is authenticating, it should be able to pass that in so that we default to the signin page with email address prefilled.

(The oauth spec way of doing this is with a parameter called [login_hint](https://developers.google.com/identity/protocols/OpenIDConnect#login-hint))

@sashei does that make sense from your perspective, or do you have requirements as a consumer that would not be met by defaulting to the email-first flow?

**Comment by linuxwolf** [comment]
> @sashei does that make sense from your perspective, or do you have requirements as a consumer that would not be met by defaulting to the email-first flow?

For Lockbox, the email-first flow makes the most sense.  The login_hint is less useful to us right now, but that might not always be true.

**Comment by shane-tomlinson** [comment]
> I think we intend for email-first to be the default flow everywhere, but if the app already knows the uid and/or email address of the user who is authenticating, it should be able to pass that in so that we default to the signin page with email address prefilled.

Email first is intended to take care of this scenario too, plus [`login_hint` is already supported](https://github.com/mozilla/fxa-content-server/blob/5ab28b49223310ebf869bffb84dc40d15471d2fa/app/scripts/models/reliers/oauth.js#L35). Personally I'd rather use email-first everywhere except for `force_auth`. `force_auth` is a special flower since the user is unable to change the account.
