### ISSUE TITLE
Implement a URLSession backend for viaduct on iOS

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1326]
This was mentioned in slack last week, wanted to file it for future reference.

Our networking library currently uses hyper on iOS, which bottoms out at the system networking and TLS stack, but brings with it a bunch of intermediate dependencies. We should consider doing a thin viaduct backend that directly uses the native [`URLSession`](https://developer.apple.com/documentation/foundation/urlsession) infrastructure provided by the platform, which would reduce dependency footprint and simplify reasoning about the system.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-742)
┆Sprint: Backlog

**Comment by thomcc** [comment]
This doesn't sound hard. The same backend as for the android code could hopefully be used, just with swift powering it rather than Kotlin. The one caveat is that the API exposed by viaduct backends must be synchronous, whereas URLSession is async.

That said, swift has *some* locks and stuff even if it's much more limited than rust there, so we can hopefully make that work.

**Comment by garvankeeley** [comment]
Happy to help. Quick tip for URLSession, instantiate it with the arg `delegateQueue: .main`, so that the response calls back to main (default behaviour is off-main response calls).

**Comment by rfk** [comment]
Would it make sense to allow the caller to pass in a `URLSession` instance in a similar way to how a-c can pass in a specific `Fetch` implementation?
