### ISSUE TITLE
Add FxA metrics documentation to website

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/application-services#135]
We've tentatively decided to combine the still-relevant bits from 

https://github.com/mozilla/fxa-auth-server/blob/master/docs/metrics-events.md
https://github.com/mozilla/fxa-content-server/blob/master/docs/client-metrics.md

& some as-yet-undocumented metrics into a more public-facing doc hosted on the app services site.

I'll start by adding a metrics.md file to https://github.com/mozilla/application-services/tree/master/docs/accounts that documents our utm_* and entrypoint parameters, since those are the most pressing pieces that need docs. then we can fill it out from there. 

cc @davismtl

**Comment by davismtl** [comment]
@irrationalagent 

You are right, let's start by focusing on utm_* ,  entrypoints and views? (which might be the new one for hosted email_first forms based on IRC conversation).

To help you out, based on all the problems we've run into internally and with other teams, I think that you should elaborate on the following:

1) Let's explain what each parameter is used for
2) Give a list of potential values for each parameter
3) what characters are allowed (include regex rules)
4) Show how they show up in our metrics for consumption and building charts
5) Perhaps links to example charts in Amplitude that filters on these parameters
6) Best practices for tracking the performance of A/B tests run on the pages not hosted by FxA team. What parameters should they use? (should we create a new one?)
7) Best way to test that the integration is well done and that we receiving those parameters and consuming them (so that we can minimize our work in the long run with a growing number of reliers)
