### ISSUE TITLE
Figure out ourselves whether or not a scope "wants" keys

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1400]
The following signature implies that the caller knows whether or not a scope is key bearing.

https://github.com/mozilla/application-services/blob/056b54facaef04a6c66b7b02e32843a9c0c1741d/components/fxa-client/src/oauth.rs#L104

We should instead either hard-code a list of key bearing scopes and request keys if necessary auto magically, or hit a server endpoint that can tell us that.

A-C bug: https://github.com/mozilla-mobile/android-components/issues/3747.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-190)
┆Story Points: 5

**Comment by vladikoff** [comment]
probably a server endpoint is better, we have various products in development that have dev credentials and experiment with scopes

**Comment by eoger** [comment]
Or even not having to pass `wantsKeys` to content at all, since we will always send `true` to key-bearing scopes anyway.

**Comment by rfk** [comment]
Large +1 to removing "wants keys" from the public API, since this is entirely implied by the requested scopes.

The simplest option may be to just remove `wants_keys`, and also remove the content-server check that errors out when you send a `keys_jwk` but don't request any key-bearing scopes:

  * https://github.com/mozilla/fxa/blob/6eebc81600a57e7a87ca9c31ed9b04fd12191ead/packages/fxa-content-server/app/scripts/models/reliers/oauth.js#L362

We added this as a kind of sanity-check to catch incorrectly-configured client apps, but I don't believe it provides any security benefit. So if it's harming more than helping the client development experience, we should just get rid of it.

This would mean that the client code always includes a `keys_jwk` parameter when starting the OAuth flow, but will receive an empty `keys_jwe` if it doesn't request any key-bearing scopes.

**Comment by vladikoff** [comment]
> "remove the content-server check that errors out when you send a keys_jwk but don't request any key-bearing scopes"

 👍

**Comment by vladikoff** [comment]
FxA issue: https://github.com/mozilla/fxa/issues/1792

**Comment by rfk** [comment]
I put up a quick PR for this in https://github.com/mozilla/fxa/pull/1806

> but will receive an empty keys_jwe if it doesn't request any key-bearing scopes.

In the linked PR, that's not actually true, it will not receive a `keys_jwe` at all if no key-bearing scopes are requested.
