### ISSUE TITLE
Let Fenix be able to migrate the session token without creating a new one

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#1677]
Currently we create a new token on session migration. Due to some changes we need a way to just reuse the existing one.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-157)
┆Story Points: 3
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-01-03

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Ideally, we'd also make it possible to re-use the existing device record from Fennec, keeping e.g. any customized device name (but re-registering push endpoints and what-not).

**Comment by rfk** [comment]
A related question...the current `migrateFromSessionToken` will only work if the user is online, because it uses the sessionToken to authorized a refresh token and some access tokens for itself.  Does this mean that the Fennec->Fenix migration will fail to copy signed-in state if the user is offline?

I wonder if we could just take the sessionToken and keys and write them into our local state without doing any network requests (or perhaps, without failing on network connectivity errors). This would let the migration succeed, but would require us to be able to operate successfully in a "missing refresh_token, but working sessionToken" scenario.

We have some code for handling this case when generating access tokens here:

* https://github.com/mozilla/application-services/blob/5730e3b7da850fd623d7325fbd82e4657cb4406f/components/fxa-client/src/oauth.rs#L57

But there are probably other things that wouldn't work, such as device registration which currently assumes we have a refresh_token:

* https://github.com/mozilla/application-services/blob/5730e3b7da850fd623d7325fbd82e4657cb4406f/components/fxa-client/src/device.rs#L264

@grigoryk what do you think, is it worth digging into this in more detail?
