### ISSUE TITLE
Sync Manager: Support for sync interruption

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1684]
In #1447, I punted on interruption, mainly as it's hard to make logins/places use the correct interrupt handle (Instead, I gave them a dummy interrupt handle). This is probably a problem long term, as sync (probably) needs to be interruptable.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2384)
┆epic: Sync Ecosystem (backlog)
┆sprintEndDate: 2022-02-18

**Comment by bendk** [comment]
I'm going to try to fix this one alongside #4617

**Comment by bendk** [comment]
Talked with mhammond about this one some more and I think fixing it is a bigger project.  I think we can probably do it along side the sync-manager/places work we're doing, but not with #4617.

**Comment by bendk** [comment]
This one has been tricky for 2 reasons:
  - Most of the components aren't set up for interrupting sqlite.  They use a shared connection for syncing and all other operation.  This means if we just try to interrupt that connection, it's possible we'll interrupt the wrong operation.
  - It's not totally clear if this is needed.  On Android it seems like we probably don't need that since their interruption model is based on simply killing a processes.  On iOS it's unclear if this is useful or not.

I think there is a way forward on this one though:
  - We mostly focusing on just getting the sync engines to use the correct `SqlInterruptScope`.  This would allow for the Rust code to be interrupted.
  - We allow sync engines to optionally pass an `rusqlite.InterruptHandle` to the `SyncManager`. Then when the sync manager's interrupt method is call, it would interrupt those handles.  In the short term, only places would do this.  Places tends to have the longest running queries, so at least we have that covered.  In the long term, if we decide we need this for other components, we could update their code to have a dedicated sync connection and then hook them up as well.

I think this makes this issue much more tractable since we can ignore the harder issue of trying to interrupt a sql query for components with a shared DB connection

**Comment by mhammond** [comment]
> * We allow sync engines to optionally pass an `rusqlite.InterruptHandle` to the `SyncManager`.

Can we just add an `interrupt` or similar methods on the sync engine trait?

But in general, this SGTM.

**Comment by bendk** [comment]
I didn't add `SyncEngine.interrupt()` just because places has 2 sync engines that share a connection, so we only need to interrupt 1 of them.  Instead I just made top-level function for it, like `get_registered_sync_engine()`.

At some point, we could define a `SyncEngineManager` trait which has `get_registered_sync_engine()` and `interrupt_current_sync_query()` as its methods.

**Comment by bendk** [comment]
Ignore those last few comments, we decided to go a different way with this one.  #4816 adds some support for this by adding a shutdown module in sql-support that allows the consumer code to enter shutdown mode which permanently interrupts all `SqlInterruptScopes`.  We decided that shutdown mode matches the one known use case for this, which is shutting down on desktop.  Android doesn't really need syncing interruption support because Android just kiils the process.  It's unclear what the best system for iOS would be, but I think shutdown mode could be good.  If we ever need to we can also add code to disable shutdown mode, which might be good for suspend/resume support.

There's still a few items left to do though:
  - Add shutdown to support for components other than places
  - Hook up the `SqlInterruptScope` created for the our `SyncEngines` to the shutdown code
  - The `interrupt.rs` and `shutdown.rs` modules feel like they belong in sql-support.  Let's move them to interrupt support.
  - Expose the `shutdown` method via UniFFI.  I think this means adding a UDL file for `interrupt-support`.  But we could also add it to an existing UDL namespace (maybe sync-manager?).
