### ISSUE TITLE
Prototype an "FxA Account Manager" crate

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#1695]
External API:

# Account Manager functions
- Synchronous UI state: are we logged-in? needs reauth? Connected?
- Observer notifications to drive UI.
- Fetch profile.
- Log-in flows: Pairing/OAuth.
- Try to recover from need-reauth state.
- Log-out.

# Device constellation functions
- Get other devices.
- Set device name.
- Refresh device list.
- Observer notifications for device list updated.
- Poll for events.
- Get "our" device.
- Set Push subscription.
- Process push message.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-347)
┆Story Points: 8
┆Sprint: SYNC - 2019-09-27

**Comment by thomcc** [comment]
Worth noting that we have tests that log into the same account multiple times, in order to perform sync integration tests. Much of the sync manager's complexity is, in part, to keep these working. The FxA manager would have to as well

It's unfortunate, but the only other option is basically TPS, which is hell to work with and debug because of it's multi-process setup.

**Comment by rfk** [comment]
I'd like to add "process webchannel events" to the list alongside "process push messages", do you think that makes sense @eoger?

**Comment by eoger** [comment]
Yes I believe it does, however we should implement this as a follow-up since this is "new" code.

**Comment by eoger** [comment]
Postmortem here: https://docs.google.com/document/d/1X6hLkt6QF7yI5SOVCaawuSVIdk1KtZ10rt4VESZBvCc/edit?usp=sharing
