### ISSUE TITLE
Logins: check_valid is missing some checks

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1781]
What we have currently: https://github.com/mozilla/application-services/blob/master/components/logins/src/login.rs#L87-L104

What we should have: https://searchfox.org/mozilla-central/rev/878bbf3cb8897a208454df27535f3522ab482cf2/toolkit/components/passwordmgr/LoginManager.jsm#256-291

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-194)
┆Story Points: 2
┆Epic: Logins Component 1.0
┆Sprint: SYNC - end 2019-12-06

**Comment by thomcc** [comment]
All of those checks are either present or unnecessary because we enforce them in the type system.

However we are missing the checks that verify that signons2.txt will be able to successfully store logins: https://searchfox.org/mozilla-central/source/toolkit/components/passwordmgr/LoginHelper.jsm#132-176

It's not clear if these are still relevant on desktop anymore either, though, as I believe that file format has not been used for a long time. @mnoorenberghe might be able to say.

We should be enforcing that the url values are both valid URLs, and the origin portion of URLs but that's #695, which has a mostly-complete patch but required some decisions which got punted on forever by the lockwise team due to other priorities. Maybe we should bring it up again?

**Comment by rfk** [comment]
> Maybe we should bring it up again?

+1; who is the right person to make decisions on that these days, is it @mnoorenberghe?

**Comment by mnoorenberghe** [comment]
> However we are missing the checks that verify that signons2.txt will be able to successfully store logins: https://searchfox.org/mozilla-central/source/toolkit/components/passwordmgr/LoginHelper.jsm#132-176

Even though we don't use the txt file format anymore I think ensuring we don't have newlines or null characters in the strings is still useful.

> > Maybe we should bring it up again?
> 
> +1; who is the right person to make decisions on that these days, is it @mnoorenberghe?

I can push for it from the Lockwise side but I don't have context on what the issue was.

**Comment by rfk** [comment]
Summarizing my understanding of this bug: want want to take the various checks for invalid characters in login entries from [this desktop code](https://searchfox.org/mozilla-central/source/toolkit/components/passwordmgr/LoginHelper.jsm#132-176) and apply them in our logins component. It sounds like this should involve some extra validation and testcases in the rust logins component, but not necessarily any new API surface to expose over the FFI.  @thomcc does that sound right?

@lougeniaC64 as discussed earlier today, this might be a good next bug to pick up in the current sprint if you have some cycles.

**Comment by rfk** [comment]
From meeting: yes this sounds right.

**Comment by lougeniaC64** [comment]
> It sounds like this should involve some extra validation and testcases in the rust logins component, but not necessarily any new API surface to expose over the FFI. @thomcc does that sound right?

@rfk @thomcc In the event that there are knock-on effects to this work requiring FFI updates that I'm not aware of, wanted to make it known that I think FFI changes will be required since the new `ensure_valid` FFI function calls `check_valid` and exposes exceptions thrown from that call. So IIUC, exceptions for the new checks will need to be added to the [current exceptions](https://github.com/mozilla/application-services/pull/2101/files#diff-71373ddf665b07b3f163566b49a102baR43).
