### ISSUE TITLE
Move the bugzilla mirroring into its own repo

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#1936]
From mtg: we found that the bugzilla mirroring is very noisy and causes us to ignore a-s issues from GitHub

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-69)

**Comment by rfk** [comment]
Some thoughts on how to make this happen:

* Make a new repo to hold the bugs, including ensuring that the "appsvc-moz" user has write access to it.
* Adjust Jira integration to include the new repo.
* Transfer existing issues with the "bugzilla" label to the new repo.
    * There are currently 105 of them, it may be worth trying to script this rather than do it by hand
    * I don't know if we can do anything clever in Jira to update links issues after moving them to the new repository...
* Change the [GH_REPO](https://github.com/mozilla/application-services/blob/master/tools/sync_bugzilla_to_github.py#L29) variable to point to it
* Optionally, migration the hourly circleci job to run under the new repo instead of under application-services

If there's no clever way to update bugs that have already been merged into Jira, then another option is to change the mirroring script so that *new* issues get created in a separate repo, but existing issues can stay in this one.

**Comment by rfk** [comment]
> Make a new repo to hold the bugs, including ensuring that the "appsvc-moz" user has write access to it.

We have the application-services-bug-mirror already for this purpose; I've invited both "appsvc-moz" and "data-sync-user" as collaborators but apparently whoever owns those accounts may need to accept the invitation? /cc @jdragojevic @eoger

**Comment by appsvc-moz** [comment]
I have accepted the invitation on behalf of @appsvc-moz.
