### ISSUE TITLE
[Logins api] assembleRelease produces 'unoptimized' builds

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#207]
![image](https://user-images.githubusercontent.com/128755/45107210-d538f500-b106-11e8-9249-33f2e1c84629.png)

Is this the only way we can build this to keep the debug info or can we fix this?

**Comment by thomcc** [comment]
Probably yes, because of https://github.com/mozilla/application-services/blob/master/Cargo.toml#L23.

@eoger was resistant to turning that off though. but OTOH he's on PTO.

That said, looking at https://github.com/ncalexan/rust-android-gradle/blob/master/plugin/src/main/kotlin/com/nishtahir/CargoBuildTask.kt#L65 it seems like something is wrong regardless.

**Comment by ncalexan** [comment]
> That said, looking at https://github.com/ncalexan/rust-android-gradle/blob/master/plugin/src/main/kotlin/com/nishtahir/CargoBuildTask.kt#L65 it seems like something is wrong regardless.

The `cargoExtension.profile` there refers to the Gradle configuration, not the Cargo configuration.  So can you try to set `profile = 'release'` around https://github.com/mozilla/application-services/blob/master/logins-api/android/library/build.gradle#L36?
