### ISSUE TITLE
Implement wipe/reset behavior for the synced tabs engine

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#2084]
See https://github.com/mozilla/application-services/pull/2000#discussion_r341399042.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-301)
┆Story Points: 3
┆Epic: Syncing Tabs
┆Sprint: SYNC - end 2019-11-22

**Comment by linacambridge** [comment]
So, to make this work, we'll want to:

* Keep the `StoreSyncAssociation` (that gets passed to `reset`, and contains the global and `tabs` sync ID) around in memory, like we already for the last sync time, and return it from `get_sync_assoc`.
* On reset, drop our map of `remote_clients`, and all remote tabs in `TabsStorage`. We can probably keep our list of local tabs, so, if we've already persisted some, we can upload right away after a node reassignment, instead of waiting for the a-c session store to change. But I don't know that it matters too much.
* On  wipe, do the same as `reset`, but also delete our cached list of local tabs.
