### ISSUE TITLE
iOS SQLCipher: pragma cipher_plaintext_header_size and cipher_salt on open

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/application-services#2100]
There is an iOS+SQLCipher incompatibility whereby iOS will kill an app with a DB file lock if it is a SQLCipher db, but not if it is an unencrypted SQLite db. iOS will try read the file header to see if it is an SQLite db file, and if so, apps are allowed to have a lock when backgrounded. The header of SQLCipher files is not readable, so the OS doesn't identify this a valid DB file.
The solution is to use `pragma cipher_plaintext_header_size=32` and `pragma cipher_salt=...` on open of the db.
https://github.com/sqlcipher/sqlcipher/issues/255#issuecomment-379099676

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-310)
┆Story Points: 5
┆Epic: user requests or bugs
┆Sprint: SYNC - end 2020-01-03

**Comment by ddurst** [comment]
For Lockwise, this is our #2 crasher. Estimations put this as responsible for ~37% of our crashes (#1 was ~63%, and it's a long tail after this one).

**Comment by rfk** [comment]
As an aside, this seems like some horrific hackery on iOS's part; but, I guess we have to deal with the circumstances we have!

I had a quick look at the linked issue and this seems a little fiddly, around the management of `pragma cipher_salt`. IIUC this salt would usually be generated randomly and stored in the leading bytes of the database file, but `pragma cipher_plaintext_header_size` prevents that from being possible. So we either have to use a fixed salt (with unclear implications for security) or store a randomly-generated salt somewhere else (maybe require it to be provided by the application?)

For existing database files we would also need to read the existing salt out of the leading bytes of the database file before setting `pragma cipher_plaintext_header_size`, otherwise the data will be inaccessible.

An alternative fix suggested in the linked issue is the disable WAL mode, but I don't know what implications that would have for our use-case.

**Comment by rfk** [comment]
> So we either have to use a fixed salt (with unclear implications for security) 

From my read of https://www.zetetic.net/sqlcipher/design/, using a fixed salt would probably be fine for our use-case, as it's mostly important for *password-protected* (as opposed to high-entropy-random-key-protected) databases. But I'm not a cryptographer, so we'd probably want to get a review from one before going this route. And it doesn't help with handling existing databases.

**Comment by rfk** [comment]
If we want to do this without raising any cryptographic eyebrows, I think we'll need the application to manage an explicit salt for us. There appear to be two ways to achieve this:

* Offer a two-argument version of `unlock`, e.g. `unlock(key, salt)`, and have it call `pragma key` then `pragma cipher_salt`.
* Accept a 96-byte key from the application, with [`pragma key`](https://www.zetetic.net/sqlcipher/sqlcipher-api/#key) will interpret as a concatenated key and salt.

In either case we would also need to know to call `pragma cipher_plaintext_header_size=32`; doing this automatically for all consumers doesn't seem right to me.

I'm leaning towards being very explicit, e.g. `unlockWithPlaintextHeader(key, salt)` or similar.

@garvankeeley @kaylagalway thoughts?

**Comment by garvankeeley** [comment]
Explicit ` unlockWithPlaintextHeader(key, salt) ` is preferred.

I am concerned about the db migration path, as we will need a special migration handler for this. IIUC the db will first need to be opened with regular unlock(key), and the salt extracted (and stored in iOS keychain or prefs), then the db closed and from then on opened with ` unlockWithPlaintextHeader(key, salt) `

**Comment by rfk** [comment]
> IIUC the db will first need to be opened with regular unlock(key), and the salt extracted
> (and stored in iOS keychain or prefs), then the db closed and from then on opened with
> unlockWithPlaintextHeader(key, salt)

This matches my understanding as well, although I believe it's possible to extract the salt without actually unlocking the database. We'll probably need to expose an additional method, so that application code can do something like:

```
logins = new LoginsStorage("/path/to/logins.db")
(key, salt) = getLoginsStorageCredentialsFromKeychain()
if not key:
  // Do whatever existing key-initialization stuff you already do here.
if not salt:
    // Get the current salt from the database, or make a random one if db doesn't exist.
    salt = logins.getSaltForKey(key)
    // Make sure we store the salt before putting the db into plaintext-header mode!
    updateLoginsStorageCredentialsInKeychain(key, salt)
// Now we can open it in plaintext-header mode
logins.unlockWithPlaintextHeader(key, salt)
```

**Comment by rfk** [comment]
From poking at this a little bit on the command-line, you have to actually query something after setting the key and before setting the plaintext_header_size, otherwise you get a decryption error.

I can do this to initialize a db:

```
sqlite> PRAGMA key='test'; 
sqlite> create table foo(bar int);
```

Then later do this to find the salt:

```
sqlite> PRAGMA key='test'; 
sqlite> PRAGMA cipher_salt;
29538c1e78b5ef1e0624b6fe86973829
```

Setting the salt explicitly works:

```
sqlite> PRAGMA key='test'; 
sqlite> PRAGMA cipher_salt = "x'29538c1e78b5ef1e0624b6fe86973829'";
sqlite> .tables
foo 
```

Setting the salt to an incorrect value gives an error:

```
sqlite> PRAGMA key='test'; 
sqlite> PRAGMA cipher_salt = "x'00001111222233334444555566667777'";
sqlite> .tables
Error: file is not a database 
```

Trying to set the plaintext header size immediately gives an (unexpected) error:

```
sqlite> PRAGMA key='test'; 
sqlite> PRAGMA cipher_salt = "x'29538c1e78b5ef1e0624b6fe86973829'";
sqlite> PRAGMA cipher_plaintext_header_size=32;
sqlite> .tables
Error: file is not a database 
```

But if I do a read of something before setting it, it works fine:

```
sqlite> PRAGMA key='test'; 
sqlite> PRAGMA cipher_salt = "x'29538c1e78b5ef1e0624b6fe86973829'";
sqlite> PRAGMA user_version;
0
sqlite> PRAGMA cipher_plaintext_header_size=32;
sqlite> .tables
foo
```

Actually getting the plaintext header to be written to disk requires modifying something to cause the first db page to be flushed to disk. The docs recommend modifying `PRAGMA user_version`, but I believe we already use that for component-level schema versioning. Luckily this appears to work even if you set it to the same value as it already has.

So I think we can build three functions to support the migration here:

* `getSaltForKey(key)`:
    * Calls `PRAGMA key=$key;` to set the key.
    * Calls `PRAGMA cipher_salt;` to query the salt for an existing database (or equivalently, to magic a salt into existence for an empty database).
    * Does not modify the database.
* `migrateToPlaintextHeader(key, salt)`:
    * Calls `PRAGMA key=$key;` to set the key.
    * Calls `PRAGMA cipher_salt=$salt;` to set the salt.
    * Calls `PRAGMA user_version;` to read the current user version, and also trick the next command into working properly.
    * Calls `PRAGMA cipher_plaintext_header_size = 32;`.
    * Calls `PRAGMA user_version=$user_version` to flush the plaintext header to disk.
    * Closes the db, to ensure that's all written out successfully.
* `unlockWithPlaintextHeader(key, salt)`:
    * Calls `PRAGMA key=$key;` to set the key.
    * Calls `PRAGMA cipher_salt=$salt;` to set the salt.
    * Calls `PRAGMA user_version;` to read the current user version, and also trick the next command into working properly.
    * Calls `PRAGMA cipher_plaintext_header_size = 32;`.
    * Returns the open db without flushing anything to disk.

Suggestions welcome for better names!

The application would need to work like so:

* Retrieve `key` and `salt` from application secure storage.
* If no salt is currently stored:
    * Call `getSaltForKey(key)` to obtain `salt`.
    * Persist `salt` into application secure storage.
    * Call `migrateToPlaintextHeader(key, salt)` make the db be the right format on disk
        * (N.B. from this point, if you lose the generated salt, the database is inaccessible!)
* Call `unlockWithPlaintextHeader(key, salt)` to open the db for use.

@garvankeeley what do you think? It's a bit fiddly, but it puts the application in charge of knowing whether the db has been migrated to the new format, without having to check for that at startup every time.

I don't think we can use the component's own migration-handling logic to handle this migration, because we don't necessarily expect to do it for all consumers.

**Comment by rfk** [comment]
> Call migrateToPlaintextHeader(key, salt) to make the db be the right format on disk

If this step seems annoying, alternatives could include:

* Force a flush of the header every time we open the db; seems wasteful for startup perf.
* Just wait for the db header to be flushed organically during normal db operations; I don't have a sense of how often that happens in practice.
* Physically read the leading bytes of the db file, and force a flush of the header they're not "SQLite 3"; seems yuck but would probably work and simplify the API for callers.

**Comment by garvankeeley** [comment]
It seems like a great solution. 
If there is no salt but there is a key, then as you mentioned we do an upgrade path (`getSaltForKey(k)` and `migrate...()`).

**Comment by rfk** [comment]
(I won't have a chance to work on this in the upcoming sprint, but the above plan sounds actionable if anyone wants to pick it up)
