### ISSUE TITLE
logins: Replace `getByHostname` with `getByBaseDomain`

### ISSUE THREAD

**Issue by mnoorenberghe** [mozilla/application-services#2152]
This would get all logins for the eTLD+1 regardless of scheme. The consumer would then have to filter out the appropriate schemes.

This will be a blocker for Fenix login autofill/capture integration (eventually to be used for autocomplete too). With the GeckoView API, toolkit code will do the appropriate filtering to handle scheme upgrades (http: to https:) but not downgrades (https: to http:), subdomain suggestions, `httpRealm`, `formActionOrigin`, port, etc.

I don't have strong feelings about whether the conversion to a base domain (using the PSL) should be done in this library or by the consumer as long as the responsibility is clear.

Pseudo-code:
```js
findByBaseDomain("www.example.com")
```
could return logins for the following `origin`s (`httpRealm` and `formActionOrigin` are ignored for the search):
* https://www.example.com
* http://www.example.com
* https://example.com
* http://www.example.com:8080
* http://sub.example.com:8080
* https://sub.example.com:8080
* https://sub.sub.example.com
* etc.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-352)
┆Story Points: 3
┆Epic: Logins Component 1.0
┆Sprint: SYNC - end 2019-12-20

**Comment by linacambridge** [comment]
Could you please link to the Toolkit integration bug when you have it, @mnoorenberghe? 😁

**Comment by mnoorenberghe** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1593069 is the GeckoView bug which will depend on the Toolkit part

**Comment by rfk** [comment]
> I don't have strong feelings about whether the conversion to a base domain (using the PSL)
> should be done in this library or by the consumer as long as the responsibility is clear.

FWIW I feel fairly strongly that this should be done by the caller, unless someone can convince me that it's a trivial process that we're highly unlikely to do differently than the calling code in a way that might lead to security problems.

"Firefox autofilled credentials in the wrong place because appservices was using an outdated version of the Public Suffix List" is not a bug I'm interested in having to triage :-)

**Comment by rfk** [comment]
Via slack, Matt says Fenix will need this within the next week or so as the logins integration gets set to land.

Per my comment above, I think we should leave all the eTLD+1 matching to the consuming application, which means we would take an already-reduced base domain and return all entries that are a subdomain of it.  I'd also like to:

1. Name it `getByBaseDomain` for consistency with other existing `get*` methods.
2. Grep our consumers for any use of the existing `getByHostname` method, and if there are any, then keep it around (perhaps deprecated) for b/w compatibility.

Tweaking Matt's example above, a call to `getByBaseDomain("example.com")` would yield logins matching:

* https://example.com
* https://www.example.com
* http://www.example.com
* http://www.example.com:8080
* http://sub.example.com:8080
* https://sub.example.com:8080
* https://sub.sub.example.com

Also, since I've seen this happen surprisingly often in the wild, we should explicitly test that it does *not* match domains like:

* https://badexample.com
* https://example.co
* https://example.com.au

Note that this is *not* just a renaming of `getByHostname`, which does an exact string match on the `hostname` field (and which if we keep it, will eventually be renamed to `getByOrigin`).

Given the structure of the tables in SQLite, I don't believe we have an index available to do this query efficiently. We'll need to do a full table scan and filter out the matching items. That's OK, the tables are small 😄. It's probably not worth trying to parse and compare the URLs in SQL, but we could e.g. do a `WHERE hostname LIKE` simple substring match at the SQL level, and then further filter the results at the rust level.

I'll also add that, worst-case scenario, Fenix could do all of this filtering itself at the application-level. But it does seem very much in the spirit of our component try to do consolidate that logic in a single place for multiple consumers.

**Comment by mnoorenberghe** [comment]
> Given the structure of the tables in SQLite, I don't believe we have an index available to do this query efficiently.

You could do like places.sqlite on desktop and store the reversed domain name as a separate column.

@ekager / @grigoryk Will it be fine for a-c/Fenix to lookup the eTLD+1 itself?

**Comment by rfk** [comment]
> You could do like places.sqlite on desktop and store the reversed domain name as a separate column.

Yep, I believe we do similarly in our version of places here a well; I just didn't want to balloon the size of the initial change 😁

**Comment by thomcc** [comment]
The logins db is small enough that I'm not really sure we should worry about maintaining an index for this the way places does to avoid a table scan here. Now that we're moving towards having telemetry, IMO we should measure the cost of these queries first.

(Also, doing what places does pretty much forces us to confront the issues around invalid origins rather than just doing them as fixups)

**Comment by mnoorenberghe** [comment]
> @ekager / @grigoryk Will it be fine for a-c/Fenix to lookup the eTLD+1 itself?

Nevermind this, we'll do it on the toolkit side so Fenix won't have to worry about it.

**Comment by mhammond** [comment]
Fixed by 1dc0e41
