### ISSUE TITLE
Review logins migration code

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2255]
Specifically, we should double-check the deduping behavior—what happens if we import new logins (into `loginsL`), and then sync? It's an issue that affects the "sign in after creating local logins" case, too, so it's not restricted to the migration case, but it's something we need to think about either way.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-433)
┆Story Points: 3
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2019-12-06

**Comment by linacambridge** [comment]
We'll also want to check how it behaves with different database sizes.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I have added "acceptance criteria" to this issue based on discussion in the meeting today. We don't have to actually have all those things ready to go in order to close out this bug, but we need to have scoped out the work to get them and filed appropriate issues in this epic.
