### ISSUE TITLE
Review bookmarks migration code

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2257]
We should test how well we migrate bookmarks from Fennec. We'll also want an integration test for migrating and then syncing—specifically, what happens if we import bookmarks from Fennec, then sign in to the same account, then run a first sync.

We should also benchmark with different database sizes. What happens if you have 10k bookmarks in Fennec? 50k? What happens if some of those are top sites, left pane roots, or bookmarks with invalid URLs? What happens if the Fennec database is corrupt?

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-434)
┆Story Points: 3
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2019-12-06

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I have added "acceptance criteria" to this issue based on discussion in the meeting today. We don't have to actually have all those things ready to go in order to close out this bug, but we need to have scoped out the work to get them and filed appropriate issues in this epic.
