### ISSUE TITLE
Review history migration code

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2258]
Like #2255 and #2257, but for history. This will probably be the simplest of audit, but we should keep an eye out for duplicate visits and large history libraries, too.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-432)
┆Story Points: 3
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2019-12-06

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I have added "acceptance criteria" to this issue based on discussion in the meeting today. We don't have to actually have all those things ready to go in order to close out this bug, but we need to have scoped out the work to get them and filed appropriate issues in this epic.
