### ISSUE TITLE
Report basic usage and quality metrics for history storage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2299]
Like the ones we're adding for the logins store, but hopefully quicker to implement because we know how to do it this time.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-462)
┆Story Points: 3
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-01-17

**Comment by rfk** [comment]
OK, so I'm going to try to add slightly more details to this issue :-)

This is basically the history equivalent of [this PR for the logins component](https://github.com/mozilla/application-services/pull/2225) - we want to instrument and gather a set of basic usage and quality metrics so that we can have some confidence that our bookmarks component is working as intended in the wild.

I left a big long comment on the specifics over in the equivalent bookmarks issue: https://github.com/mozilla/application-services/issues/2300#issuecomment-567790245

The only thing that might change for this bug, is the set of metrics that we want to gather. My strawman proposal is actually the same set of metrics as proposed for bookmarks:

* A `readQueryCount` and `readQueryErrorCount` from which we can calculate error rate of read operations.
* A `writeQueryCount` and `writeQueryErrorCount` from which we can calculate error rate of write operations.
* A `readQueryTime` timing distribution that measures the execution time of read queries that should be, for want of a better word, "small".
* A `scanQueryTime` timing distribution that measures the execution time of read queries that we expect to be costly (`getVisitInfos` perhaps?).
* A `writeQueryTime` timing distribution that measures the execution time of write queries.

In fact, I think I'm open to the suggestion that we should emit a single set of "places metrics" rather than distinct sets of metrics for bookmarks and history. @linacambridge what do you think?
