### ISSUE TITLE
Find a way to debug FFI layers (and SDK code) using ASan/MemSan

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#230]
Given that we've had serious bugs that would have been caught by these, it seems very much worth doing.

Some documentation on using them with Rust is available here https://github.com/japaric/rust-san

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-699)
┆Sprint: Backlog

**Comment by rfk** [comment]
This is labelled "ship-ready", do we need to return to this before Fenix MVP beta, or Fenix MVP release?

**Comment by jdragojevic** [comment]
This is a quality bug, which we should do ahead of Fenix MVP

**Comment by rfk** [comment]
From @thomcc via slack: "It's worth noting that things are substantially safer than they were when [this issue was filed]. At this point the main issues where memory unsafety can appear in most of our FFI Rust code we actually write are: anything having to do with callbacks, someone doing `FfiStr<'static>`, passing protobuf data *into* Rust. Sadly, Kotlin and Swift aren't designed with producing safe abstractions around unsafe code in mind, so our bindings on that side can cause memory safety issues in a lot more ways"

**Comment by rfk** [comment]
I timeboxed an investigation of this in service of #1349, but I didn't have a lot of lock. Here's what I tried that *didn't* work:

* Added  `--asan` to the build options in `./libs/build-nss-desktop.sh`
* Added a deliberate error in unsafe code in the `nss` binding (in my case, changing `hash_buf` to pass `(data.as_ptr(), data_len + 16)` through to `PK11_HashBuf` rather than `(data.as_ptr(), data_len)`, in an attempt to make it read extra data)
* Ran the tests via `RUSTFLAGS="-Z sanitizer=address" cargo +nightly test --target x86_64-unknown-linux-gnu -- --test-threads=1`

This resulted in a failing test (because `hash_buf` now calculates the hash of too much data) and an apparently unrelated warning about a memory leak, but not in any sort of "you read past the end of a buffer" error.

I *was* able to trigger an asan error by doing something unsafe directly in the rust code, such as reading beyond the bounds of a vector.  So I guess maybe there are additional hoops to jump through to get good integration for memory accesses that happen inside NSS?

**Comment by rfk** [comment]
One small victory: I modified `hash_buf` to under-allocate the output vec that we pass to NSS.  Changing it from ` vec![0u8; result_len]` to  `vec![0u8; result_len - 2]` didn't produce any errors, but making it ` vec![0u8; result_len - 16]` triggered:

```
test digest::tests::sha256_digest ... =================================================================
==15850==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x6020000009b0 in thread T0
  ...
0x6020000009b0 is located 0 bytes inside of 71517289-byte region [0x6020000009b0,0x602004434e19)
```

Which I guess is a result of NSS writing its output into something else on the heap, and then later on we try to drop it and it triggers this error.

Anyways, this was a fun experiment, but my timebox is well and truly over. I suspect we need to look more closely at how to compile NSS with asan checks enabled as a next step here.

**Comment by jdragojevic** [comment]
@rfk  - is it time to close this one?

**Comment by rfk** [comment]
Yes, let's close it, if it comes back it'll probably be as as a UniFFI bug
