### ISSUE TITLE
Report basic usage and quality metrics for bookmarks storage

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2300]
Like the ones we're adding for the logins store, but hopefully quicker to implement because we know how to do it this time.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-463)
┆Story Points: 3
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-01-17

**Comment by rfk** [comment]
OK, so I'm going to try to add slightly more details to this issue :-)

This is basically the bookmarks equivalent of [this PR for the logins component](https://github.com/mozilla/application-services/pull/2225) - we want to instrument and gather a set of basic usage and quality metrics so that we can have some confidence that our bookmarks component is working as intended in the wild. This will involve the following:

## Define the metrics to gather

In Glean, all metrics must be defined in a `metrics.yaml` file for the component that collects them.

The [`metrics.yaml` for logins](https://github.com/mozilla/application-services/blob/master/components/logins/android/metrics.yaml) is a good example. In that file we group the possible operations on a login store into three core types (reads, writes, unlocks) and for each type we collect three basic quality metrics (execution time, execution count, and error count).

What would a similar set of metrics look like for bookmarks? My strawman proposal is:

* A `readQueryCount` and `readQueryErrorCount` from which we can calculate error rate of read operations.
* A `writeQueryCount` and `writeQueryErrorCount` from which we can calculate error rate of write operations.
* A `readQueryTime` timing distribution that measures the execution time of read queries that should be, for want of a better word, "small".
* A `scanQueryTime` timing distribution that measures the execution time of read queries that we expect to be costly (`getBookmarksTree(guid, recursive=True)`, I'm looking in your direction).
* A `writeQueryTime` timing distribution that measures the execution time of write queries.

But I'm not wedded to the particulars here, as long as it's a small set of metrics that will serve as a starting point for understanding quality and performance.

## Integrate the Glean dependency

The [logins component gradle changes](https://github.com/mozilla/application-services/pull/2225/files#diff-c5e146f2725a08bddb196f1a6f4ca1e8) should be a good template here. It results in auto-generated classes that the Kotlin wrapper code can import and use.

## Gather the metrics.

This involves importing the autogenerated classes from Glean in the Kotlin bookmarks wrapper code, and calling their methods at the appropriate times during execution. As above the [logins component instrumentation changes](https://github.com/mozilla/application-services/pull/2225/files#diff-c5e146f2725a08bddb196f1a6f4ca1e8) should be a good template here. I found it useful to wrap the Glean classes into a little helper for re-use; see `LoginsStoreCounterMetrics` in the above-linked file.

We also need to [add some tests](https://github.com/mozilla/application-services/pull/2225/files#diff-d53cd4b5c985cdfe10c67c05addb65d5) to confirm that the metrics are being gathered correctly.

## Get data review

The data-review bug for the logins component as [Bug 1597895](https://bugzilla.mozilla.org/show_bug.cgi?id=1597895). I believe you can request data review inline in the github PR, but I found it useful to use bugzilla and its various flags to manage this process.

Importantly, the data review needs to mention all current known consumers of the component. Since the metrics are only being gathered on the Kotlin side (for now) then our only known consumer is Fenix.

## Update the docs, changelog etc

A few pieces of docs need updating:

* Components that use glean need a [notice in their readme](https://github.com/mozilla/application-services/pull/2225/files#diff-8efed776bec89d217c6538820419e2b4) to inform consumers about requirements for data review.
* The addition of data review requirements constitutes a breaking change that needs to be [noted in the changelog](https://github.com/mozilla/application-services/pull/2225/files#diff-07c3a86afce678200c63cfb0c5762b1c).
* We list all of our metrics-emitting components in [docs/metrics/README.md](https://github.com/mozilla/application-services/pull/2225/files#diff-83d4d833329b365b1f41644cf2082f2f) for easy reference.
* Make sure you `git add` the [docs that get autogenerated by glean](https://github.com/mozilla/application-services/pull/2225/files#diff-87beb3c089a81d069220b04f2769ee7a).

## Test in android-components

You'll need to tweak upstream consumers in android-components, to break the quote-unquote "circular dependency" on the glean component; see [example here](https://github.com/mozilla-mobile/android-components/pull/5223/files#diff-728758767bdb2193d20d5a8b570d7404).

## Profit!

I think that's everything. If you take on this bug and the steps above prove a useful reference, please feel welcome to file an issue asking me to turn them into a proper "howto" doc for future.

**Comment by rfk** [comment]
> Test in android-components

A few additional notes on this step:

* You can follow the workflow in [`docs/howtos/locally-published-components-in-fenix.md`](https://github.com/mozilla/application-services/blob/master/docs/howtos/locally-published-components-in-fenix.md) to publish your modified appservices components and include them in an android-components build (just skip the parts that talk about building Fenix, unless you really want to do that as well).
* The main component impacted by bookmarks and history is in `./components/browser/storage-sync/`; run its tests using `./gradlew browser-storage-sync:test`.
* The main sample app for bookmarks and history is `./samples/sync`; build it using `./gradlew samples-sync:assembleDebug` and find the `.apk` file under `./samples/sync/build/outputs/apk/debug/` which can be run in the android emulator for manual testing.
