### ISSUE TITLE
Remerge: Use numeric versions instead of semver

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#2319]
Lina and I both agreed that this is complexity for little gain, and we should take it out, at least for now. This depends on #2066 landing, but that should happen after it comes out green in CI.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-477)
┆Story Points: 3
┆Epic: Remerge production readiness
┆Sprint: SYNC - end 2020-03-13

**Comment by glasserc** [comment]
`required_version` is currently described as optional in the wire format, but is defaulted to "the lowest compatible version". What should it default to now? 0? Or should we stop defaulting it and just assume that if it's missing, that we shouldn't do version comparisons?

**Comment by glasserc** [comment]
We also have this leftover `LocalRemergeVersionFailsLocalRequired`, which I guess is meant to check if the version of Remerge is itself new enough for the data. This also uses semver. Should it? Alternately, we don't actually have any code that enforces this, just the error variant for when we should violate the condition. Should we drop this whole concept for now since we have the idea of remerge features?

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Decided not to do this.
