### ISSUE TITLE
Figure out how sync adapter interfaces with storage

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#24]
My vague plan, at least recently has been something like:

```rust
pub struct RecordChangeset<T> {
    pub changed: Vec<BsoRecord<T>>,
    pub deleted_ids: Vec<String>,
    /// For GETs, the last sync timestamp that should be persisted after
    /// applying the records.
    /// For POSTs, this is the XIUS timestamp.
    pub timestamp: ServerTimestamp,
}

impl Sync15Service {
    pub fn get_changes<T: Sync15Record>(
        &mut self,
        since: ServerTimestamp
    ) -> Result<RecordChangeset<T>>;

    pub fn post_changes<T: Sync15Record>(
        &mut self,
        changes: RecordChangeset<T>,
        // Whether or not oversized and/or server-failed records
        // blow everything up.
        fully_atomic: bool
    ) -> Result<ServerTimestamp>; // Might want to return the Vec of failed ids too?
}
```

Note that we will likely want to trim down the Result to the set of errors that can actually happen for this.

Also note that the methods might be on something that isn't Sync15Service, but just occupies the role it currently holds.

Implementation note: both methods would encrypt the records immediately to avoid having more code than is necessary monomorphized for each record type.

### Pros

1. API encourages clients to store sync change metadata with the record.
2. Minimizes callbacks between Swift and Rust. Entirely avoids having passing around FFI function pointers (both in Rust and in swift/java). Not having an event driven system also avoids problems like sync tracker's ignoreAll and such.
3. The API makes deletions explicit and not dependent on the caller knowing about the tombstone format (unlike using JSON directly).

### Cons

1. Clients might decide that storing any sort of sync change metadata is a PITA and do a sync for each change they want to upload (e.g. Pro number 1 may backfire). I don't think this is that likely for shipping code, though.
2. Leaves managing sync change timestamps fully up to the app (I think this is going to be more or less necessary for most designs, unfortunately).
3. Shaped nothing like what is proposed in the lockbox sync google doc (Not sure how much this matters, there's a good chance we can either write some sort of wrapper that does what they want, or we'd have problems with it anyway).
4. Likely requires that T get exposed over the FFI? 

@mhammond I expect you'll have some opinions about this?

**Comment by kitcambridge** [comment]
Posting some early thoughts before dinner, will write a more substantive comment later.

Overall, I think this is a nice design, and feels more in line with iOS's "synchronizers" instead of the engine, tracker, store pyramid on Desktop. Each `Sync15Service` impl figures out the best way to fetch what changed, and marshal them into records. Your adapter provides all the primitives, but it's up to the impl to glue them together, which seems like an acceptable trade-off.

IIUC, the way this would work is:

* We call `post_changes` with new incoming records. (Or is there a separate call to apply new records? Should we maybe add a flag to `post_changes` indicating if the records we're passing in are "dirty" and need to be merged, or is that unnecessary?)
* The impl does whatever it needs to merge the items in, including resolving merge conflicts and flagging reconciled items for upload, along with new items. It's up to the impl to manage all this state, and figure out where and how to persist timestamps along with the records.
* We then call `get_changes` to get a changeset of everything we need to upload. (Could this be generalized to an `Iterator` instead of a `Vec`, if we ever want to get fancy and use something like a cursor to pull entries from the database?)
* We upload everything the app gives us.
* We call `post_changes` again, to update the store with what we just uploaded, with the new server time?

If a `BsoRecord` can be a tombstone or a "real" record (maybe a tagged enum?), could we avoid separating `changed` and `deleted_ids`, or is that still necessary?

**Comment by mhammond** [comment]
The collection name isn't specified here - I'm guessing you can derive this at runtime from T?

I think this sounds great, although I believe a part of the puzzle that's missing is both "server state" and "collection state" - consider the "syncIds" - there's a global one and one for each collection, and I think we need some way to track them and communicate (presumably via specific error return values) that either the server or the collection itself is out of date.

Off the top of my head, I could imagine something like:

let serviceState = server.get_ready(oldServiceState);
// If oldServiceState is specified and the current serviceState is not compatible with the existing state (eg, new global syncID, or version, etc) then a specific error is returned. The consumer then needs to do a "reset client" type action.
// If oldServiceState is not specified, then we assume the app has reset and we return a serviceState.
// The service state includes the result of an meta/global, so also carries the syncID of each collection etc - although a collection's syncID changing isn't considered incompatible at this time.

get_changes and post_changes could work similarly - eg, RecordChangeset<T> carries state too, with the same basic semantics as above (ie, not specified assumes collection is being reset and reconciled, specified means we check and throw)

It's not quite clear what the "collection state" actually is though - the state we care about here comes from meta/global, so it's almost like the entire server state is what we need - so maybe we could avoid the "get_ready()" state dance and do it purely in the collection methods - OTOH though, the server being fully reset probably means the app will take slightly more drastic action at setup time rather than being prepared to handle that each time a collection method is called.

I haven't thought too deeply about the API, but thought I'd throw this strawman out there for consideration.

**Comment by mhammond** [comment]
Treating this state as opaque isn't really going to fly - at a minimum, the app needs to know what "storageVersion" it knows how to read and what version it wants written to meta/global if the collection doesn't yet exist.

**Comment by mhammond** [comment]
I'm now thinking it makes sense to wrap some if this state into "a sync".  #19 probably wants it and it's a sane mental model. Eg, apps might declare at startup what collections it cares about and what state it has for them, and then perform periodic "syncs" in the context of that information. In practice, sync 1.5 stuff will *always* do (a) if there's new stuff give it to me, then (b) here is my new stuff. Restricting our model to this might make some of this state easier to mange. I'll try and spell this out more concretely tomorrow :)
