### ISSUE TITLE
Remove the nodejs helper for the sync integration tests

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2403]
This is a low-priority, but would reduce the number of moving parts in our developer experience, and maybe speed up CI runs a little thanks to fewer dependencies.

The sync integration tests (in `./testing/sync-test`) currently use a nodejs helper in order to drive a headless browser and manage the FxA OAuth flow. This works nicely, but adds additional dependencies to the developer experience. We should revisit this and see if it can be done using plain-old-rust dependencies.

One option might be to avoid using a headless browser at all, and instead talk directly to the FxA backend APIs to drive an OAuth flow, much like the script currently does for creating/destroying accounts.

Alternately, we could investigate a native rust webdriver experience such as [fantoccini](https://crates.io/crates/fantoccini).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-702)
┆Story Points: 5
┆Epic: Increase unit and integration test coverage
┆Sprint: SYNC - end 2020-06-19

**Comment by rfk** [comment]
@thomcc I'm curious how much the headless browser part of this is really needed, and how much of it could be replaced by direct backend API calls (assuming someone with sufficient FxA experience can suggest the right sequence of calls, and I think I know just the guy...)

**Comment by eoger** [comment]
Here are the results of my timeboxed work on this, my WIP branch is [remove-node-helper]( https://github.com/mozilla/application-services/tree/remove-node-helper).

The Create and Delete account "commands" are implemented using Rust completely and work. We could merge these if we wanted.

Authenticating is a bit harder: At first I thought it would be as simple as calling `/login` then `/verify_code` to get a valid session token, then finally call `oauth/authorization` to get my `code` and `state`. Seems simple right?
Well there's also the keys problem: in `/authorization` I'm supposed to feed back the sync keys using `keys_jwe`, which involves calling `/keys` with a `keyFetchToken` that I can get in `/login`, do a bunch of crypto derivations and xor and voila.

Since it's more involved than I thought, I almost wonder now if it would be better to grow a `auth` module to `FirefoxAccount`, flagged behind a pref, that can do a non-interactive log-in for testing. It's a bit more involved, it's not really crazy hard work I believe and would may be a good external contributor project? **wink wink**

The other solution to this problem is "why don't you just do a classic OAuth flow using a headless browser" like `fantoccini`?  It seems like it is required to have a webdriver process running on 4444 before using it, which defeats the whole "developer ergonomics" purpose of this (`nightmare` that we currently use spawns the process itself). But maybe we can justify this?

**Comment by lyuyuan** [comment]
Hi @eoger, is there a place I can find documentations for the oauth flow backend APIs?

**Comment by eoger** [comment]
Yes your are correct!

**Comment by thomcc** [comment]
> It seems like it is required to have a webdriver process running on 4444 before using it, which defeats the whole "developer ergonomics" purpose of this (nightmare that we currently use spawns the process itself). But maybe we can justify this?

For clarity, I'd be opposed to this, even though I'd love to see the helper go. There's a reason I didn't use fantoccini when I wrote the helper initially.

**Comment by lyuyuan** [comment]
Hi @eoger , I am not quite certain which key should I feed back to `/authorization`using `keys_jew`? Is it [`kSync`](https://searchfox.org/mozilla-central/source/services/fxaccounts/FxAccountsKeys.jsm#239)? Thanks!

**Comment by eoger** [comment]
Yes I believe this would be `kSync`. You can see some of these API calls happening by launching an OAuth flow in the browser (`cargo run oauth_flow`) and look at the network requests the app makes to figure out what goes where.
