### ISSUE TITLE
Verify that clients behave sensibly during the proposed durable-sync migration process

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2486]
When we attempt to migrate existing users to the new durable sync storage node, we will attempt to do so in a way that preserve their existing data on the server. As discussed in [this issue](https://github.com/mozilla-services/server-syncstorage/issues/125), we expect that such a migration can be done safely via the following procedure:

1. Before we start copying the user's data to the new node, their current storage node begins returning
`503`
errors. This will cause the client to gracefully back off its sync attempts, and ensure that the data doesn't change while we try to migrate it.

1. After we've finished copying the user's data to the new node and updated their node-assignment in tokenserver, their previous storage node begins returning
`401`
errors. This will cause the client to refresh its tokenserver token and discover its new storage node in a timely manner, and it will happily sync against the new node.

Let's do the work to confirm that our expectations match reality. I have stood up an extremely basic "migratinator" service that we can use to test client behaviour in practice, see [https://github.com/mozilla-services/syncserver/pull/194](https://github.com/mozilla-services/syncserver/pull/194) for a description and [http://migratinator.rfk.id.au/](http://migratinator.rfk.id.au/) for a live server. We should use it to confirm that the following clients behave as expected:

* [x] Desktop Firefox
* [x] Firefox for iOS
* [x] Fennec
* [x] Fenix
* [ ] ~~Lockwise for Android~~
* [ ] ~~Lockwise for iOS~~

Specifically we need to check that:

* After beginning the migration, the client is unable to sync due to the
`503`
errors, but it just retries again later without showing any error UI to the user.

* After completing the migration, the client discovers its now sync node and continues syncing.
  * In particular, the client should _not_ re-upload any data it had previously stored on the server.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-608)
┆Sprint: SYNC - end 2020-02-14

**Comment by rfk** [comment]
Here's what I did to test Firefox Desktop:

* Setup:
  * Create a new profile.
  * In about:config:
    * set `identity.sync.tokenserver.uri` to "http://migratinator.rfk.id.au/token/1.0/sync/1.5"
    * set `services.sync.log.appender.file.logOnSuccess` to `true`.
  * Sign in to Firefox with a test FxA account
  * Check in about:sync-log to confirm that the initial sync as completed
* Simulate in-progress migration:
  * Visit http://migratinator.rfk.id.au/ and click "Begin Migration".
  * Sync Now in Firefox, and confirm that no error UI is displayed.
  * Check in about:sync-log to confirm that an error was logged
* Simulate completed migration:
  * Visit http://migratinator.rfk.id.au/ and click "Complete Migration".
  * Sync Now in Firefox, and confirm that no error UI is displayed.
  * In about:sync-log, confirm that a new successful sync has taken place.
  * Open the sync log, have a read, and confirm that it didn't re-upload any data.
* Cleanup:
  * Visit http://migratinator.rfk.id.au/ and click "Reset", to leave things in a known state for future tests.

Seems like Desktop behaves as we expect, which is a good start :-)

**Comment by data-sync-user** [comment]
➤ Rachel Tublitz commented:

Filed this issue ( https://github.com/mozilla-services/services-engineering/issues/33 ) to track the iOS testing efforts over on our services-eng board. I'll note the results here once that happens.

**Comment by rfk** [comment]
I ran through this procedure on current release Fennec and it seemed to behave as expected - watching the output in `adb logcat` showed it silently handling the `503` errors while migrating, then continuing a successful sync after the migration has completed.

**Comment by rfk** [comment]
It took way more edit-compile-test cycles than I expected, but I ran through this procedure on the latest master of Fenix, and it appeared to behave sensibly. It respected the `503`s during the migration period and continued with a normal sync at the new endpoint URL after the migration was complete.

**Comment by rfk** [comment]
From meeting, we decided there was not a lot of value in independently testing the Lockwise apps, given they share almost all of their sync code with Fenix.

**Comment by tublitzed** [comment]
Here's what I did for iOS:

1. Setup iOS to point to local application services [like this](https://github.com/mozilla-mobile/firefox-ios/pull/6148)

2. Commented out lines [55-50 here](https://github.com/mozilla/application-services/blob/master/components/viaduct/src/backend.rs#L54) in order to bypass https requirement.

3. Swapped the prod token server url [here](https://github.com/mozilla-mobile/firefox-ios/blob/master/Account/FirefoxAccountConfiguration.swift#L13) to use `http://migratinator.rfk.id.au/token/1.0/sync/1.5` instead.

4. Setup a fresh profile and Fxa account. Confirmed I could sync between iOS and Desktop (also pointed to `http://migratinator.rfk.id.au/token/1.0/sync/1.5` for it's tokenserver)

5. Simulated migration by visiting http://migratinator.rfk.id.au/ and clicking "Begin Migration".

6. Verified no UI errors and that I saw 503s in the Xcode debugger sync log.

7. Simulated completed migration by visiting http://migratinator.rfk.id.au/ and clicking "Complete Migration".

8. Verified that I could once again re-sync and see 200s in the Xcode debugger sync logs.

9. Visited http://migratinator.rfk.id.au/ and click "Reset", to leave things in a known state for future tests.

I also setup some logging in firefox-ios to confirm I was indeed building and syncing pointed to `http://migratinator.rfk.id.au/token/1.0/sync/1.5`.

Here's a [video of what I did](https://recordit.co/9QzW8YYsGo) - All seems to be working as expected!

**Comment by rfk** [comment]
Thanks @tublitzed!

Given that we've completed verification of the major clients, I'm going to tear own the instance behind `http://migratinator.rfk.id.au`. It's easy enough to stand back up if we want it back.
