### ISSUE TITLE
Enable "Automatically delete head branches" in our github repo config

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2503]
We can use the [setting described here](https://github.blog/changelog/2019-07-31-automatically-delete-head-branches-of-pull-requests/) to cleanup remote heads after the corresponding PR has been merged. May be a nice automated may to keep the remote repository a bit cleaner.

Any objections? If I don't hear any before this next comes up in triage, I'll go ahead and make the change.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-619)
┆Story Points: 0
┆Sprint: SYNC - end 2020-02-28

**Comment by linacambridge** [comment]
I really like this! Sometimes I forget to click the "delete" button after merging (or not at all if I'm pushing from the command line), and then new branches get lost in the list of long-since merged ones.

@eoger mentioned folks might still be using those branches for builds or integration tests. While deletions can be reverted if we want the branch to stick around, it _is_ a stumbling block to keep in mind. Maybe we can add a short reminder to our issue template, like "This branch will be automatically deleted after it's merged. Please make sure to click the "Revert" button next to the merge commit if you'd like to keep it around."

**Comment by rfk** [comment]
From @thomcc: if we link to the code from e.g. other issues, does the link stop working after the branch is deleted? (I feel like it probably does).

**Comment by mhammond** [comment]
I don't think we should worry too much about that though - branches should be understood as ephemeral and having them grow without bounds doesn't seem great.

(Note also that the branch almost certainly is going to exist on a developer's machine, so getting back an "accidental" deletion via that path seems reasonable too)

**Comment by rfk** [comment]
I went ahead and did this; the option reassuringly says "Deleted branches will still be able to be restored." so we'll see how it goes.
