### ISSUE TITLE
Take screenshot automaticly

### ISSUE THREAD

**Issue by Dawidek990** [mozilla/application-services#2608]
Hello, I need to know what to do so that the "take screenshot" option immediately saved a photo to disk, and did not ask every time where to save the photo. I don't have to click anything after clicking "download".

Or some firefox add-on that works like this option.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/SYNC-805)

**Comment by rfk** [comment]
Hi @Dawidek990, this sounds like a product support question, so I expect you will get better help by taking it to https://support.mozilla.org/ (which has an "ask a question" option that's designed for this sort of thing) than you will get in github issues. I'm going to close the issue here since it does not relate to the code in this github repo.

(Also, , I see that you also opened an equivalent issue over in https://github.com/mozilla/addons-server/issues/13452. Please don't make multiple copies of the same issue in different places, it makes them hard to track and reduces the effectiveness of our issue-tracking as a whole.)
