### ISSUE TITLE
Allow consumers of logins-api android SDK to run unit tests that call functions implemented in Rust.

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#262]
This kind of sucks to do, but it's very hard for me to imagine that Lockbox will accept not being able to run unit tests (on-device tests in an emulator *should* still be possible, though, although this is a painful prospect).

Apparently we need to produce a jar file that contains both the java class files, and the compiled native code for every platform we want to support running tests on. I suspect in practice that means at least windows x86, x86_64, linux x86, x86_64, and macOS. Maybe linux arm/aarch64? Not sure.

This is a big pain. Cross compiling the rust shouldn't be a huge deal (hopefully? Supposedly `rustup toolchain add` can do everything), but I strongly suspect cross compiling OpenSSL/SQLcipher will suck (especially to windows and mac)

I suspect that the way to handling the native code dependencies in a sane manner will be to fetch precompiled versions.

Caveats there: On windows the ABI needs to match, and on all platforms we need to be sure to compile position independent code even though we're producing static libraries for our native code dependencies (for OpenSSL the only way I could find to build a static lib w/ PIC is to build a shared lib and grab the static lib it produces as an intermediate), since ultimately they're linked into a dynamic library.

**Comment by ncalexan** [comment]
Any update on this: we're pretty close to having this ready on the `a-s` side of the house.  Publishing something for consumers to (well) consume isn't hard, but it would be nice to get https://github.com/mozilla/application-services/issues/252 in place first.

We're in good shape for Linux and macOS, but Windows is sticky: as @thomcc seems to have already been aware of, the ABIs need to match -- and cross-compiling with mingw to a _static_ library, a la #376, appears not to be ABI compatible with MSVC on my Windows 10 device.  I think that we might be able to produce a DLL with mingw and use that with MSVC.  That's OK here, I think, because this isn't actually going to ship to consumers.  (On Android, we very strongly didn't want multiple `.so` files.)

**Comment by rfk** [comment]
From triage: we can do this from our repo, unclear whether it works from other repos; @ncalexan any comment on the status here?

**Comment by ncalexan** [comment]
> From triage: we can do this from our repo, unclear whether it works from other repos; @ncalexan any comment on the status here?

Yes.  This is ready for other folks to use, and it's integrated into the `org.mozilla.appservices` plugin already, so that Megazord consumers should be "just ready".  See also https://github.com/mozilla-mobile/android-components/pull/1713, which shows how a-c can use this.

**Comment by rfk** [comment]
Thanks, I think we can close it out here then.
