### ISSUE TITLE
Bookmark migration failures

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#2660]
[https://github.com/mozilla-mobile/android-components/issues/5938](https://github.com/mozilla-mobile/android-components/issues/5938) has some strange bookmark migration failures we need to look at.  Sebastian took a deeper look at the error and found that a number of different issues were being grouped together in sentry.

|Error|Sentry Count|Actionable by a-s|
|----|----|----|
|`mozilla.appservices.places.PlacesException: Error executing SQL: unwinding panic`|[2](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6904470/events/?query=unwinding+panic)| #2607 if url has invalid utf?|
|`mozilla.appservices.places.PlacesException: Error merging: Item [..] can't contain itself`|[3](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6904470/events/?query=can%27t+contain+itself)| Issue #2683 to investigate|
|`mozilla.appservices.places.PlacesException: Error executing SQL: NOT NULL constraint failed: moz_bookmarks_synced_structure.parentGuid`|[12](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6904470/events/?query=NOT+NULL+constraint+failed)| #2536?|
|`mozilla.appservices.places.PlacesException: Database version 38 is not supported`|[2](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6904470/events/?query=version+38)| No|
|`mozilla.appservices.places.PlacesException: Error executing SQL: database disk image is malformed`|[1](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6904470/events/?query=malformed)|No |
|`mozilla.appservices.places.PlacesException: Database version 37 is not supported`| [3](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6904470/events/?query=version+37)| No|
|`mozilla.appservices.places.PlacesException: Database version 24 is not supported`|[3](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6904470/events/?query=version+24)| No|
|`mozilla.appservices.places.PlacesException: Error executing SQL: CHECK constraint failed: moz_bookmarks`|[1](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6904470/events/?query=CHECK+constraint+failed)| No|
|`mozilla.appservices.places.PlacesException: Error executing SQL: unable to open database: [..]`|many| No|
|`mozilla.appservices.places.PlacesException: Error executing SQL: FOREIGN KEY constraint failed`|[1](https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6904470/events/38104545)| No|

We should also determine which are actionable.  All errors result in a complete failure.  

Marking this as a spike - we need to fill out the table above and for any issues that we believe are actionable we should file a new issue for the specific problem.

┆Issue is synchronized with this [Jira Spike](https://jira.mozilla.com/browse/SYNC-843)
┆Story Points: 2
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-02-28

**Comment by grigoryk** [comment]
Seems like these issues are in three basic categories:
- `Database version X is not supported` - this is actionable by A-S if we care about it; see https://github.com/mozilla/application-services/issues/2402
- `database disk image is malformed`/`unable to open database` - likely various local corruption/weirdness, doesn't seem actionable; we also saw a long tail of these kinds of problems on Fennec
- all the other stuff - failed constraints, panics, etc - these seem like wrong assumptions about shape of the data coming from Fennec, likely not accounting for various bugs/peculiarities in how Fennec handled bookmarks.

**Comment by mhammond** [comment]
"FOREIGN KEY CONSTRAINT" appears to have exactly 1 event - https://sentry.prod.mozaws.net/operations/fenix-fennec-nightly/issues/6904470/events/38104545/

**Comment by mhammond** [comment]
The test added for #2536 fails with `Error executing SQL: NOT NULL constraint failed: moz_bookmarks_synced_structure.parentGuid)` without the fix added there, so it's safe to say that is a dupe.

**Comment by lougeniaC64** [comment]
@mhammond Currently both the `FOREIGN KEY constraint` and `CHECK constraint` errors are each being reported by one user. I'm not sure if that excludes them from being actionable so I'll press on.

After reviewing the [schema](https://github.com/mozilla/application-services/blob/8285df9c89dcd9137d6b0a05ef7e24c99c2f47e2/components/places/sql/create_shared_schema.sql#L99) for the `moz_bookmarks` table, it looks like the `CHECK constraint` error was caused by either a bookmark not having a fk to a places record or a bookmark with a non-root guid having no parent value. I'm not sure what specifically caused this error (as we don't have that level of granularity).

I _think_ the first step here would be updating the import code to report errors per record but that seems like a heavy lift all things considered. My inclination is to mark this not actionable.

I'm assuming the same first step applies to the `FOREIGN KEY constraint` error. I'm not even sure if this error is stemming from the [filling moz_places step](https://github.com/mozilla/application-services/blob/8285df9c89dcd9137d6b0a05ef7e24c99c2f47e2/components/places/src/import/fennec/bookmarks.rs#L100) in the migration process or the [fixup of moz_bookmarks](https://github.com/mozilla/application-services/blob/8285df9c89dcd9137d6b0a05ef7e24c99c2f47e2/components/places/src/import/fennec/bookmarks.rs#L126).

That sound about right?
