### ISSUE TITLE
Push out v0.53.0 to a-c and fenix migration branch

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2723]
Our latest release includes important fixes for server health that we want to get in to the Fenix beta migration, filing an issue so we don't lose track of doing that.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-882)
┆Story Points: 1
┆Epic: Fenix Migration
┆Sprint: SYNC - end 2020-03-13

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

To add a bit more here, I think first steps will be to get a-c master updated with this release, and then ensure that Fenix master picks it up. From there we can ask Grisha and/or Sebastian to see what they need in order to get it on the beta branch. It may be that we'll just cut the next beta with a-c master and nothing is required, but maybe not.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

PR is here - https://github.com/mozilla-mobile/android-components/pull/6110
