### ISSUE TITLE
Confirm requirements around per-record encryption in chrome.storage.sync

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#2745]
The current kinto-backed chrome.storage.sync API has some special logic to encrypt each record differently. We suspect it was driven by a secreview requirement to avoid fingerprintability, but we're not really sure. Let's do a bit of archaeology to confirm the requirements and make sure our replacement will meet them.

┆Issue is synchronized with this [Jira Spike](https://jira.mozilla.com/browse/SYNC-896)
┆Sprint: SYNC - end 2020-03-13

**Comment by rfk** [comment]
Adding some notes as I walk through the history here.

The bug in which the Kinto-backed storage stuff landed was [Bug 1253740](https://bugzilla.mozilla.org/show_bug.cgi?id=1253740), and it links to this helpful prose explanation of the design of storage system, including the crypto bits:

  https://wiki.mozilla.org/CloudServices/Sync/ExtensionStorage_Design_Doc

Key points from this doc, and some comments on how they map into sync:

* The kinto storage has a special "keyring" collection which stores a separate encryption key for each collection (thus, for the data owned by each extension). This keyring record is the only thing encrypted by `kB`, and it "was inherited from Firefox Sync and it helps us to minimize data that we reupload when a user's kB change".
  * This sounds very similar to the way we use `/crypto/keys` in sync, and I expect we don't need to keep it in the new world, since we *already have* `/crypto/keys` for this purpose.
* The keyring also holds a salt per Kinto collection, which is used to hash IDs related to that collection:
    * When we sync, we map the local collection name to an "obfuscated" remote collection name. This is done so that metadata doesn't leak information about what extensions a user has installed. The "obfuscated" name is computed by hashing the collection ID using the collection's salt. 
    * The ID for each record is hashed to try not to leak information about the record or the extension being used. The hashed record ID has to be consistent across clients so that syncing works correctly, so we hash the ID using the collection's salt.
    * I don't believe we have an equivalent approach for this elsewhere in sync, because we tend to use randomly-generated guids rather than predictable ids. So there may be something here we need to keep.
* There's some special tracking of the hash of the user's master key `kB`, designed to help Kinto detect when there has been a password reset. Again, we get this for free from the existing machinery in sync, and don't need to replicate it into the new world.

So I think I have a good idea of the requirements here and the questions we need to answer about the new implementation.

What I need to understand next is how the same data will be stored in the new re:merge-backed system: How does the chrome.storage.sync data model of one key-value-store-per-extension map into the world of BSOs? How will we manage BSO ids, an the ids of individual items stored for each collection? Etc.

I hoped to find a link to that via [this issue about making a re:merge schema for extension-storage](https://github.com/mozilla/application-services/issues/2596) but it doesn't seem to have been fleshed out yet.  @thomcc what's the best existing reference for what the stored data will look like on the server in the new world?

I'm confident we can design a good scheme here without jumping through a lot of special-case hoops, but I also think it will be worth our while to write it down explicitly and get some secreview feedback on the design, for completeness.

**Comment by rfk** [comment]
@glasserc if anything I said above sounds wildly off-base, please intervene before I get any further down this path :-)

**Comment by thomcc** [comment]
> @thomcc what's the best existing reference for what the stored data will look like on the server in the new world?

I assume you mean after decryption -- when encrypted they're just normal BSOs with the same fields.

I'm on my way out the door but should be able to get you example records from the todo demo tomorrow (I wish there were a way to need-info myself on bugzilla, since this is easy for me to do but is the sort of thing I might forget).

**Comment by rfk** [comment]
> I assume you mean after decryption 

I think that's right - I mean broadly "what's inside the encrypted payload of each BSO?" and "what goes into making the BSO id?".  For example, will there be one BSO per installed extension, with all key-value pairs inside the encrypted payload?

> I'm on my way out the door 

Thanks, no rush, I'm at the end of my week anyway and it's a public holiday here on Monday, so syncing up about this early next week is fine.

**Comment by thomcc** [comment]
> what's inside the encrypted payload of each BSO?

https://github.com/mozilla/application-services/blob/remerge-sync/components/remerge/src/sync/records.rs#L15-L27

The payload here is: The addon ID, and an untyped-map containing the addon data. Probably a few timestamps too, those are stored locally in ext storage and I haven't dug into their use.

> For example, will there be one BSO per installed extension, with all key-value pairs inside the encrypted payload?

Yes. This can change if needed, but it would be very surprising and would require me re-jiggering the list of "required features for extension-storage" I provided earlier.

> Thanks, no rush, I'm at the end of my week anyway and it's a public holiday here on Monday, so syncing up about this early next week is fine.

SGTM

**Comment by rfk** [comment]
High-level, the privacy properties under that schema sound strictly better than those of the current Kinto-backed scheme (but the tradeoff is that we have to transfer the entire dataset for an addon whenever one of its items changes, while IIUC Kinto can send individual changed items). So I don't anticipate any problems here.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

I think I have a good handle on this, and given that we plan to re-work some of the immediate plans around chrome.storage.sync, I don't think there's further action we can take here right now. Let's close this out, but replace it with a task to loop secreview in for approval of the new design for serializing this data into BSOs (whatever that turns out to look like). I think there's really only one obvious "shape" for how that could work and I have high confidence that it satisfy security concerns, so I don't expect this to be a blocker.
