### ISSUE TITLE
Hook our query plan infrastructure into tests

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2781]
This would help ensure that our queries use the indexes we think they're using, and let us detect undesired changes to query plans. Right now, we need to log plans manually using `println!("{}", sql_support::QueryPlan::new(&self.store.db, &sql, &[])?);`.

See @mhammond's [comment](https://github.com/mozilla/application-services/pull/2501/files#r369871194) for more thoughts.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-919)
┆Sprint: Backlog

**Comment by thomcc** [comment]
`cargo test --all-features` from the root with no package specified should include it (not sure if anything more specific works -- we're hitting cargo feature limitations here...). This is actually documented https://github.com/mozilla/application-services/blob/master/components/support/sql/doc/query-plan.md#usage. 

Note that I believe we enable this in CI too so that CI should have query plans output.

This is *only* for queries going through sql_support though. Ones that directly go through rusqlite (this is a lot of them) don't. We might be able to move it there under a feature though...

Partial output:
```
test storage::bookmarks::tests::test_bookmark_url_for_keyword ... ok
### QUERY PLAN
#### SQL:
UPDATE moz_bookmarks SET position = position - 1
         WHERE parent = :parent
         AND position >= :position
#### PLAN:
QUERY PLAN
`--SCAN TABLE moz_bookmarks
### END QUERY PLAN

### QUERY PLAN
#### SQL:
DELETE from moz_bookmarks WHERE id = :id
#### PLAN:
QUERY PLAN
|--SEARCH TABLE moz_bookmarks USING INTEGER PRIMARY KEY (rowid=?)
`--SCAN TABLE moz_bookmarks
### END QUERY PLAN

test storage::bookmarks::tests::test_delete ... ok
test storage::bookmarks::tests::test_delete_roots ... ok
### QUERY PLAN
#### SQL:
SELECT
            b.guid,
            p.guid AS parentGuid,
            b.position,
            b.dateAdded,
            b.lastModified,
            NULLIF(b.title, '') AS title,
            h.url AS url
        FROM moz_bookmarks b
        JOIN moz_bookmarks p ON p.id = b.parent
        JOIN moz_places h ON h.id = b.fk
        WHERE b.type = 1
        ORDER BY b.dateAdded DESC
        LIMIT :limit
#### PLAN:
QUERY PLAN
|--SCAN TABLE moz_bookmarks AS b
|--SEARCH TABLE moz_bookmarks AS p USING INTEGER PRIMARY KEY (rowid=?)
|--SEARCH TABLE moz_places AS h USING INTEGER PRIMARY KEY (rowid=?)
`--USE TEMP B-TREE FOR ORDER BY
### END QUERY PLAN
```
