### ISSUE TITLE
Document process to build and use an android component

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/application-services#281]
*We want a repeatable process to build and use an Android component.*

*Acceptance Criteria*
[ ] documented steps for a manual build process
[ ] issue created to capture automated work (later) if not done now.

**Comment by thomcc** [comment]
Depending on what you mean by 'android component' (presumably the rust-based stuff we ship out of this repo and not the ones in https://github.com/mozilla-mobile/android-components/), https://gist.github.com/thomcc/620fafc6b246cead296912e2773c8bb2 is probably the best starting point for this. It's no longer accurate since our folder structure and project names have changed but beyond that is *mostly* still the steps (One larger omission, that @mhammond hit last night, is that I think we probably want people to run `./build-all.sh desktop` too now, so that the gradle `'default'` toolchain can be built).

Most of that gist is setup -- the steps once everything is set up are running  `./gradlew $componentLibrary:assembleRelease` from the root of this repo, where `$componentLibrary` is either `fxa-client-library`, `logins-library` or (once #279 lands) `places-library`.

**Comment by mhammond** [comment]
https://github.com/mozilla/application-services/wiki/Building-the-Android-Components
