### ISSUE TITLE
Implement api to pass account creds to sync engines

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/application-services#288]
Ensure there’s a reasonable API in place that will support passing creds etc to our sync engines (which is already done for Lockbox, but we should take this opportunity to consider if we have it correct)

*Acceptance criteria*
- [ ] Documented api
- [ ] ...

**Comment by thomcc** [comment]
Currently there's no generic notion of a 'sync engine' in rust, so I think we might need to do that first.

We had it for a bit but there are a few challenges around it so we punted on it. There are some  somewhat substantial challenges around error handling, among other issues (and there are bugs in the rust library we use for error handling that make this worse than it needs to be... 😞)

I think for using history in the reference browser we might end up wanting to do this non-generically and think about how we can share the common pieces after.

This also probably gets a lot easier in the post-megazord world ("probably" because it depends on how we do the megazording -- if we do it more manually this becomes a lot easier. If it's an automated process we are likely to lose the control that we'd want).

**Comment by rfk** [comment]
From discussions, we're going to keep the API here as simple as possible.  The plumbing code in reference-browser will request an access token using existing fxa-client APIs and will pass the resulting token to the sync code.  So...is there any value in keeping this issue open, or shall we close it out?

**Comment by mhammond** [comment]
This is just part of the plumbing
