### ISSUE TITLE
Implement shared implementation for FFI error handling

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/application-services#289]
We’ve been copy-pasting error and result handling code from FxA into Logins then into Places. We need to work out how to share this code and make it less error prone. Out megazord strategy may impact how we tackle this.

*Acceptance criteria*
- [ ] ...

**Comment by thomcc** [comment]
I'm doing this today-ish.

At least for logins and places. FxA's error handling code is slightly different in a very subtle and annoying way that makes it more challenging and harder to update automatically, although I'll see if I can do that.

**Comment by thomcc** [comment]
(I assume this is about FFI error handling and changed the title to fit. There is boilerplate for other sorts of error handling that we'd like to find a way to share, but it's a much lower priority since it's safe code that's straightforward to write and use. The FFI error handling code is unsafe, tricky, and subtle misuse is extremely easy, so it would be good to avoid it's duplication).
