### ISSUE TITLE
Storage.Sync Sync-Merging Compliance

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#2900]
We need to ensure we behave the same as Chrome, and/or our Kinto implementation when merging at sync time.

[Here's a note from the chrome developer who implemented the API for chrome](https://stackoverflow.com/questions/23210499/chrome-storage-local-persistence) but it leaves a number of things vague, particularly around conflicts. For example:

* 2 devices both have `{foo: bar}`. device A calls `.clear()` and syncs, device B sets `{another: bar}`. Does the 'clear' win, or is a clear just like a `.remove()` of values?

* Related and similar to the above - is `.clear()` identical from a sync perspective to `.remove()` for every key?

* Related and similar to the above 2 - although it's documented that "server wins" for conflicts, is a `.remove()` considered conflicting? Eg, device A removes a key and syncs, device B sets a value for that key and syncs, do we end up with no key, or B's value?

* Device A has `{foo: bar}`, device B has `{another: bar}` but neither are connected to sync. When they both connect and sync (ie, so there's no "shared parent" to 3way merge on) do we merge or does the first writer win?

These are off the top of my head - there are almost certainly other scenarios.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1050)
┆Story Points: 5
┆Epic: Extension pref storage & sync updated to Sync1.5
┆Sprint: SYNC - end 2020-05-08

**Comment by glasserc** [comment]
I did some testing today on Chrome by modifying the `favourite-colour` extension from https://github.com/mdn/webextensions-examples (first to add the browser polyfill, and then to use `remove` or `clear` if the user cleared the input field). Chrome allows you to have multiple "profiles" running simultaneously but only one can be connected to a given Google account at once, so I tested by disconnecting one and connecting the other. While tedious, this had the side effect of preventing race conditions.

My best guess as to how things work so far:
- The merge resolution behavior appears to be whole-object. This does NOT track with what the person on StackOverflow wrote.
- Whichever object was written to the sync server "wins" and this object completely supplants the other object. No per-key logic is involved.
- The Chrome implementation appears to track tombstones on the client, but not on the server.
- When no object exists on the server, any object "wins".

# Are a `remove("a")` and a `set("a")` considered conflicting?

*Test procedure:*
- Set "blue" as my favorite color in profile 1, connecting it, disconnecting it
- Connect profile 2 and verify that the favorite color is now blue
- While profile 2 is connected, clear the field, causing a `remove()`
- In profile 1, set favorite color to "orange"
- Disconnect profile 2
- Connect profile 1
- Observe favorite color in profile 1.

*Result:* favorite color is orange. If I reconnect profile 2, profile 2 also gets the favorite color "orange".

*Conclusion:* `remove()` is not considered a conflict with a `set()`. This suggests no tombstones are kept whatsoever.

# Does `clear()` remove keys that weren't already present on the syncing device?

*Test procedure:*
- Modify `favourite-colour` to expose the complete contents of `storage.sync` as well as to store additional fields based on the typed color ("blue" sets `expert: true`; "green" sets `chill: true`).
- Also, modify it to call `clear()` instead of `remove()` if the field is cleared.
- Charmingly, you don't have to restart the browser or reinstall the extension or anything for Chrome to pick it up!
- Both profiles still have "orange" as their favorite color from the previous experiment.
- In profile 2 (currently connected), clear the input field and hit save.
- In profile 1, set the color to "blue" and hit save. Verify that the data in storage.sync is `{"colour": "blue", "expert": true}`.
- Disconnect from profile 2. Connect profile 1.
- Observe contents of storage.sync in profile 1.

*Results:* Contents are `{"colour":"blue","expert":true}`. Reconnecting profile 2 causes it to get the same contents.

*Conclusion:* Calling `clear()` not only doesn't clear additional keys, it doesn't even seem to clear the keys that were present on the device. This is consistent with not storing tombstones, but it even calls into question whether the merge strategy is "last write wins" as we supposed.

# Wait let's just make sure "sync is source of truth" is actually what's happening

*Test procedure:*
- In profile 2 (still connected), set favorite color to "orange".
- In profile 1, set favorite color to "purple".
- Disconnect profile 2 and connect profile 1.
- Observe favorite color in profile 1.

*Expected result:* Profile 1 should have the color "orange".

*Result:* It does.

*Conclusion:* Sync does appear to be the source of truth and takes precedence over modifications that happened "later" in time but while offline.

# What about clear(), is that, like, synced at all

*Test procedure:*
- Both profiles now have a favorite color of "orange", after the previous experiment.
- In profile 1 (still connected), clear the favorite color.
- Disconnect profile 1 and connect profile 2.
- Observe favorite color in profile 2.

*Expected result:* Profile 2 should have an empty favorite color.

*Result:* It doesn't.

*Conclusion:* This could be because the client doesn't tell the server about the deleted keys, or because the server doesn't tell the other client about them. The first would be consistent with not tracking tombstones at all; the second would be consistent with tracking them on the client but not the server.

# Let's also verify what this person on StackOverflow says about adding keys

*Test procedure:*
- In profile 2 (still connected), change the color to "red".
- In profile 1, change the color to "green".
- Disconnect profile 2 and connect profile 1.
- Observe favorite color in profile 1.

*Expected result:* The data in sync should be `{"colour":"red","chill":true}`.

*Result:* The data in sync is actually `{"colour":"red"}`.

*Conclusion:* No per-key merging happens.

# Is a `clear()` different in any way from `remove()` of all keys?

I wasn't able to identify a way to observe any difference from the perspective of merge behavior, since neither `remove()` nor `clear()` calls seem to have impact on the synced data.

# Does the merge algorithm behave the same way if it's the first sync for both profiles (shared keys)

*Question:* If two profiles are brand new, and both have data written to them, they will not have reference to any server timestamp. Syncing can thus not reconcile against previous states. How, then, to determine which value wins?

*Test procedure:*
- Use `clear()` on a currently synced profile to try to clean out the Google account as much as possible.
- Create a new profile, N1, and install the extension.
- Create another new profile, N2, and install the extension.
- In profile N1, set your favorite color to "first".
- In profile N2, set your favorite color to "second".
- Sign in to sync in N1. Observe favorite color in N1. Disconnect N1.
- Sign in to sync in N2.
- Observe favorite color in N2.

*Expected result:* Since we haven't seen any evidence of tombstones, it's hard to know if it's possible to have an "empty" Google account. If we don't, we might reasonably expect both profiles to get "orange", since that was the last value to be written to the server. On the other hand, it's possible that the values *are* being deleted from the server but the server isn't tracking tombstones; in that case, we'd expect N1 to successfully write "first" and N2 to get it. In either case, given what we know from the StackOverflow answer, we'd expect N2's value to be dropped.

*Result:* N1 and N2 both have "first".

*Conclusion:* It appears that clearing the account *does* work, and that it's possible to write to missing keys even from a brand new profile that doesn't know anything about existing server timestamps. The merging behavior is consistent with that seen in other experiments so probably 3WM is not part of the picture.

# Does the merge algorithm behave the same way if it's the first sync for both profiles (disjoint keys)

*Test procedure:*
- Use `clear()` on a currently synced profile to try to clean out the Google account as much as possible.
- Modify the extension to use a different key instead of `"colour"`. Let's have it use `{[colour]: colour}`, i.e. setting your favorite color to "orange" should store `{"orange": "orange"}`.
- Create a new profile, N1, and install the extension.
- Create a new profile, N2, and install the extension.
- In N1, set the color to "first".
- In N2, set the color to "second".
- Connect to sync using N1. Observe the favorite color. Disconnect sync from N1.
- Connect to sync using N2. Observe the favorite color.

*Expected result:* Per the StackOverflow answer, the given scenario seems like it should end up with `{foo: bar, another: bar}` -- `{foo: bar}` syncs first and so writes `foo`, and the second profile syncs and does not find an existing value for `another` so it gets added.

*Result:* Both N1 and N2 show `{"first":"first"}`.

*Conclusion:* No per-key merging happens, and the first object written wins. This is consistent with what we see in other experiments.

**Comment by mhammond** [comment]
Thanks Ethan, this is surprising. This is also very different from how the existing impl works, right?

**Comment by glasserc** [comment]
Right, the kinto.js-based chrome.storage.sync implementation resolves conflicts on a per-key basis with whatever is on the server "winning", more like how the Stack Overflow answer describes things. Which is the "right" choice I think depends on the assumptions you make about how extensions use preferences. If you assume one user-facing setting can correspond to multiple keys, then the Chrome behavior makes sense -- it prevents you from getting into an inconsistent state where one key corresponds to the setting on one device and another key on another device. The kinto.js behavior makes more sense if each user-facing setting only corresponds to a single key, because then you can merge preferences that have been set on different devices.

**Comment by mhammond** [comment]
Yeah - per-key merging means we can end up with the data being in a state that no device ever actually had. It's easy to imagine scenarios which would cause logically invalid data to exist confusing naive extensions.

Let's discuss this in tomorrow's meeting - we need agreement on what to actually implement. I haven't tried to reproduce your experiment yet - do you think someone should, or are you totally confident in your results? (I've obviously no reason to doubt them, but thought it worth asking :)

**Comment by glasserc** [comment]
We discussed this in the meeting and Shane argued convincingly that we should maintain the same behavior as Firefox does now. Changing (because Chrome does it the other way, or because we think it's more correct the other way) should be a separate decision that happens separately from migrating to the new backend. I'll work on a patch to reflect the behavior that we have in the legacy implementation.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

Ethan has a PR for this: https://github.com/mozilla/application-services/pull/3049 ( https://github.com/mozilla/application-services/pull/3049 ) looking for a review from [~mhammond@mozilla.com]
