### ISSUE TITLE
Help users clean up their Send Tab list

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3055]
As Ed mentioned, a good first step to helping users clean up their Send Tab list could be to add a link at the bottom of the menu to redirect users to the "Devices & Apps" sections on accounts.firefox.com. 

So far within a day, there have been 2 threads on Reddit of users asking how they can clean up that list. [https://www.reddit.com/r/firefox/comments/g9py1c/how_do_i_editremove_devices_from_the_send_linktab/](https://www.reddit.com/r/firefox/comments/g9py1c/how_do_i_editremove_devices_from_the_send_linktab/) and [【 highlighted #172b4d 】https://old.reddit.com/r/firefox/comments/ga97i8/firefox_sync_and_send_to_browser_how_can_i_clear/【 end highlighted 】]

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1201)
┆Epic: Send Tab Success Rate Improvements
┆Sprint: Backlog

**Comment by garvankeeley** [comment]
Removing devices is painfully slow due to:
1) Popup asking for explanation every time
2) reload loses scroll position, have to relocate, try doing this on an iPhone and prepare to scream
3) the reload in general is slow and unnecessary, the removal should be async and not make the user wait while it blocks the UI. The UI should immediately remove the selected item. In the one-in-million case where the server didn't delete the device, there is little benefit to not showing the item deleted, this isn't much clearer to the user than returning to the list and seeing the device there again.

**Comment by data-sync-user** [comment]
➤ Janet Dragojevic commented:

A like to manage devices was added to desktop under https://jira.mozilla.com/browse/SYNC-1707. 

closing this.
