### ISSUE TITLE
[Send Tab] FxA's invoke_command should return an error when the push server returns an error

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3120]
See https://github.com/mozilla/application-services/issues/3097#issuecomment-624922074 for more context.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1287)
┆Story Points: 3
┆Epic: Trusted Send Tab Telemetry
┆Sprint: SYNC - end 2020-07-17

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

Possibly alternate/complimentary approach would be to have the `/invoke_command` response include data about whether the push succeeded or failed, ref https://bugzilla.mozilla.org/show_bug.cgi?id=1642866

**Comment by rfk** [comment]
> Possibly alternate/complimentary approach would be to have the /invoke_command response
> include data about whether the push succeeded or failed

So um, it turns out I did this as part of https://github.com/mozilla/fxa/pull/5546 but didn't do a good job of it, so we're fixing it to include as part of FxA train-178 here:

  https://github.com/mozilla/fxa/pull/5887

I expect that will be sufficient to close this bug, and we can have the client use the newly returned information as part of its log output on desktop.

**Comment by data-sync-user** [comment]
➤ Ryan Kelly commented:

As of today's FxA deploy, the above PR is now live in production, and the `/invoke_command` endpoint should be returning additional debugging information. Specifically, the JSON response has boolean property `enqueued` to indicate the command was successfully stored and `notified` to indicate whether the notification was successfully sent.

I reckon this is good enough for the purposes of this ticket. Vlad, WDYT?
