### ISSUE TITLE
build-all.sh better download checksum handling

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3141]
Helping @gabrielluong setting up his dev environment today, he had a checksum problem with one of the artifacts [we download in build-all.sh](https://github.com/mozilla/application-services/blob/b95215f21b3b2755c662af5aeca7d7de34fa5073/libs/build-all.sh#L57).

We should help the user of these scripts by:
- Deleting the corrupt file for them.
- Informing them to re-run the script and/or trying the download again once.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1320)
┆Story Points: 0
┆Sprint: SYNC - 2021-06-25

**Comment by mgiang2015** [comment]
Hi @eoger, is this issue still up for grabs? I am new to contributing to open-source projects and I'd like to try taking on this :)

**Comment by eoger** [comment]
Hi @mgiang2015 looking at the build script I believe the issue is still valid. I don't work at Mozilla anymore, maybe @rfk can guide you?

**Comment by mgiang2015** [comment]
Thank you @eoger @rfk, I'll try tinkering with the script first meanwhile

**Comment by rfk** [comment]
Hi @mgiang2015, this issue is certainly still valid and we'd welcome you taking it on! Here's how I would recommend approaching this issue:

* Start by simulating a corrupted download by creating an invalid file, something like:
    * `rm -rf ./libs/desktop` # cleans any previous build artifacts
    * `echo "invalid file" > ./libs/v4.4.0.tar.gz`  # simulates a corrupted download of the sqlcipher sources
* Now try running the build scripts by doing `./libs/verify-desktop-environment.sh`; you should see that it fails with a not-very-helpful error message, like this:
    * `shasum: WARNING: 1 computed checksum did NOT match`
* To improve the user experience here, we need to update the [two](https://github.com/mozilla/application-services/blob/367280a8cedf7deb17fcc2ad6c5555d91c030446/libs/build-all.sh#L57) [places](https://github.com/mozilla/application-services/blob/367280a8cedf7deb17fcc2ad6c5555d91c030446/libs/build-all.sh#L68) in `build-all.sh` that use `shasum` to check file integrity.
    * Instead of just exiting the script with `exit 2`, these lines should detect the error, remove the corrupted file, and print a more helpful message before exiting.

Hope that helps!

**Comment by mgiang2015** [comment]
Thank you @rfk, it certainly helps. I'll start working on this and update here once i submit a PR

**Comment by mgiang2015** [comment]
@rfk can I assume that `shasum` is already installed on the machine? Or should I add a check clause for that as well?

**Comment by rfk** [comment]
> can I assume that shasum is already installed on the machine? 

Yes, it's reasonable to assume it is already installed. (And if it isn't I expect the resulting error message would do a decent job of helping the user understand the issue).

**Comment by mgiang2015** [comment]
Hi @rfk, I submitted pull request #4203 for this issue. Do help me review and let me know if any changes (both the code and PR descriptions) are needed. Thank you
