### ISSUE TITLE
Analyze webext-storage migration telemetry for errors

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3268]
We only have a little bit of time to fix issues in this if they arise, so we should analyze this ASAP.

I started on this last night here [https://sql.telemetry.mozilla.org/queries/72174/source,](https://sql.telemetry.mozilla.org/queries/72174/source,) and immediately ran into an issue with the data in bigquery.

A bug about it was filed [https://github.com/mozilla-services/mozilla-pipeline-schemas/issues/563](https://github.com/mozilla-services/mozilla-pipeline-schemas/issues/563), and there's an attached PR for that bug. Hopefully we can get that sorted in time.

We should be cognizant of the fact that there seems to be some (imperfect) data transformation step that occurs after landing code in mozilla-pipeline-schemas.

It's possible this information can possibly still be analyzed using ATMO, or whatever it's descendant is, if it looks like this will take too long to resolve?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1414)
┆Story Points: 5
┆Epic: Extension pref storage & sync updated to Sync1.5
┆Sprint: SYNC - end 2020-07-03

**Comment by data-sync-user** [comment]
➤ Thom Chiovoloni commented:

I'm trying to analyze this data in databricks currently, which is the replacement for ATMO (e.g. it's a spark cluster-based analysis method).

The data appears to be available.

**Comment by thomcc** [comment]
Initial work is https://sql.telemetry.mozilla.org/queries/72246#181211. Results are very good, over the past 20 days of nightly migrations, there have been a couple thousand, and only 3 have had any data loss at all.

This is just for the data prior to the https://github.com/mozilla-services/mozilla-pipeline-schemas/issues/563 fix (which went out last evening). I still need to update this so that the data that comes in after that fix will be measured, but then this bug will be done.

**Comment by thomcc** [comment]
https://sql.telemetry.mozilla.org/queries/72252 is a version of this that is live and should be accurate going forward, but only has one day of data currently.

**Comment by thomcc** [comment]
https://sql.telemetry.mozilla.org/queries/72245#181220 is a chart of the migrations per day. It can't yet include data loss numbers due to the 563 but mentioned in my previous comment (or if it did we'd either have to grab them out of json which is a bit costly, or would only have 1 day of data, as with the previous query).

**Comment by thomcc** [comment]
Marking this as done, as we have initial error info as well as dashboards we can continue montioring. 

In a week or two I'll finish this up by creating real dashboards, but that's set up in the next sprint.
