### ISSUE TITLE
[Bug] Fenix preview Android - Last Synced time changes but bookmarks not synced

### ISSUE THREAD

**Issue by ghost** [mozilla/application-services#3370]
See https://github.com/mozilla-mobile/fenix/issues/12625

If internet is on, and `Sync Now` option is pressed, the `Last Synced` time changes to current time, but no bookmarks are synced. 

```
07-17 12:42:17.258 28856 28971 D sync15::sync_multiple: sync was successful, final status=Ok
07-17 12:42:17.258 28856 28971 I sync_manager::manager: Sync finished with status Ok
07-17 12:42:17.258 28856 28971 I sync_manager::manager: engine "bookmarks" status: Err(Error(Store error: Error executing SQL: FOREIGN KEY constraint failed))
07-17 12:42:17.258 28856 28971 I sync_manager::manager: engine "passwords" status: Ok(())
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1496)
┆Epic: a-s consumer issues
┆Sprint: SYNC - end 2020-08-14

**Comment by linacambridge** [comment]
From that ticket, the reporter (whose account is now gone 😢) said:

> I cleared all data of the application, and now syncing bookmarks works fine. So most likely some other bug caused the local database to get corrupted which caused this issue.

I wish we had more details about which constraint failed; without that, the original database, or more detailed logs, this unfortunately isn't actionable. I wonder if we can try to handle consistency issues like this by trashing `moz_bookmarks_synced`—this shouldn't cause data loss, since we merged the bookmarks into `moz_bookmarks`, and everything else should be on the server—and repopulating it fully on the next sync.
