### ISSUE TITLE
Investigate arm64 crasher

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3646]
The current nimbus component crashes when run on an arm64 device, I'm going to try to understand this better as a top priority.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1836)
┆Epic: Fenix Client SDK
┆Sprint: SYNC - end 2020-10-23

**Comment by rfk** [comment]
The good news, such as it is, is that I've been able to reproduce the issue in a smaller stand-alone example, which I've pushed here for visibility:

  * https://github.com/rfk/arm64-bug-repro

AFAICT this is a problem with passing structs as arguments by value on arm64 android, possibly a bug in JNA or libffi. I'll try to dig in some more later and understand it better.

More good news: the issue only seems to manifest when passing structs, not primitive values, and it only seems to manifest when the amount of data to be passed in arguments does not fit in the argument-passing registers. So it seems unlikely to be affecting any of our hand-written FFI bindings, but is showing up in the more verbose bindings generated by uniffi.

**Comment by badboy** [comment]
What's the crash? We had issues passing structs as well. The cause was some disagreement of alignment of `long` on the JNA side. JNA's changelog suggests this might have been fixed, but I'm not sure which  JNA version you currently run

**Comment by badboy** [comment]
(Ah, 5.6.0, so the latest one. So maybe this is yet another bug)

**Comment by rfk** [comment]
> What's the crash? 

To clarify: the observed behaviour is that we read garbage data when [accessing a struct passed as an argument](https://github.com/rfk/arm64-bug-repro/blob/276faa58d2d1cebc09bf432ffe2e67827ecefb35/src/lib.rs#L24), if there are enough arguments to force the struct to be passed on the stack.

For code generated by uniffi this causes a panic due to some internal validation on the resulting data. @travis79 observed an attempt to free an unallocated pointer rather than a panic in the rust code, but I think it was probably the same underlying issue.

**Comment by travis79** [comment]
I guess it's possible to work around this by keeping the struct from getting passed on the stack?

**Comment by rfk** [comment]
After a lot of garbage printf debugging, I think I have gotten to the bottom of this.

The code for libffi in JNA appears to be doing the wrong thing [here](https://github.com/java-native-access/jna/blob/0a0e44d4e8c616eb948fae7b87f882db32db5e60/native/libffi/src/aarch64/ffi.c#L733) when it tries to write a small struct to the stack; it should be using `ecif->avalue[i]` rather than `ecif->avalue + i`, and as a result it ends up passing a pointer to the struct rather than the struct itself. The latest version of libffi on github does not seem to have this problem, but has changed *substantially* from the version bundled with JNA. So I will investigate what is the best way to upstream the fix in JNA.

I've had some luck in working around this bug by adding padding fields to the struct, so that it is too large to be considered for passing in registers. I will see if we can put this workaround in uniffi as a short-term fix, and confirm whether it avoids the crashers that we were running in to.

I will also write up some notes on how to build a modified local copy of JNA and use it in an Android app, since I had to do a bit of hacking to the build scripts to get it working for me.

**Comment by rfk** [comment]
> I will also write up some notes on how to build a modified local copy of JNA and use it in an Android app,
> since I had to do a bit of hacking to the build scripts to get it working for me.

I've pushed the beginnings of a howto here: https://github.com/mozilla/application-services/pull/3664

**Comment by rfk** [comment]
> I will see if we can put this workaround in uniffi as a short-term fix, and confirm whether it
> avoids the crashers that we were running in to.

Here's a workaround in uniffi that seems to do the trick for me: https://github.com/mozilla/uniffi-rs/pull/335

**Comment by rfk** [comment]
> So I will investigate what is the best way to upstream the fix in JNA.

And finally, here's the upstream JNA issue to figure out how to get this fixed: https://github.com/java-native-access/jna/issues/1259

With that, I'm going to call this bug complete.
