### ISSUE TITLE
Review UniFFI for creating Autofill FFI Layer

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3648]
Get familiar with UniFFI and assess whether it is sufficient for the creation of autofill's FFI layer.

┆Issue is synchronized with this [Jira Spike](https://jira.mozilla.com/browse/SYNC-1840)
┆Story Points: 8
┆Epic: Form data (addresses/credit cards) shared component
┆Sprint: SYNC - end 2020-10-23

**Comment by rfk** [comment]
I mentioned this in a recent meeting but surfacing here to reinforce: I'm highly motivated to use this as an opportunity to smoke-test the uniffi docs and general developer experience, so if you're not able to start from https://github.com/mozilla/uniffi-rs/ and find out how to use the tool successfully, please liberally file bugs and/or message me on slack to get unstuck. I'll try to address any questions with improved docs rather than one-off answers.
