### ISSUE TITLE
Store Scoped Keys and OAuth access tokens separately

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#379]

**Comment by vladikoff** [comment]
ref

https://github.com/mozilla/application-services/blob/e64a2d838572781cbc31fd2835729ffa6fc49069/fxa-client/src/lib.rs#L275-L279

**Comment by eoger** [comment]
Instead of doing a weird merging that I suggested at first (e.g. https://github.com/mozilla/application-services/issues/379#issuecomment-436811346), let's go with something more proper and store OAuth Access Tokens and Scoped Keys in two different data structures.
We'll also have to add a `get_scoped_key(s)` function to `FirefoxAccount` and the FFI to grab a previously cached scoped key.

**Comment by rfk** [comment]
> We'll also have to add a get_scoped_key(s) function to FirefoxAccount and the FFI
> to grab a previously cached scoped key.

A related proposal: https://github.com/mozilla/application-services/issues/381

I think there's value in treating (access_token, key) as an atomic pair that the client accesses via a single function call, to avoid edge-cases around key rotation.
