### ISSUE TITLE
Upgrade concept-fetch dependency version to 71.0.0

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/application-services#3829]
Original issue: https://github.com/mozilla-mobile/fenix/issues/17585

There was an API change in the `Request` class in concept-fetch which causes java class signature errors in a-s which is currently compiled against an older version.

Testing against a newer Android Components version, I'm able to see this error resolved.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2018)
┆Sprint: Backlog

**Comment by rfk** [comment]
Thanks for digging into the details here!

This feels like the sort of thing that should have been detected by a failing test somewhere in the android-components testsuite, but I guess that all the tests there that would have exercised this code and instead mocking out the network, and thus did not trigger the issue. I wonder whether the [`rusthttp` component](https://github.com/mozilla-mobile/android-components/tree/master/components/support/rusthttp) could grow a small test that would help us catch similar errors in future. I'm imagining something like:

* Create a mock `concept-fetch` implementation that returns a known value, rather than hitting the network.
* Configure the Rust code to use this mock.
* Call into a Rust function that hits the network, assert that it returns the mocked value.

Do you think that such a test would have caught the issue?

**Comment by jonalmeida** [comment]
Yes! I definitely think we should write some tests that uncover this before a PR lands. I've filed https://github.com/mozilla-mobile/android-components/issues/9494 for this that we will prioritize at our next triage meeting.


I've also grown rather affectionate towards our bots of late (Mergify and Github Actions) 🤖 . Would it make sense if a bot made a pull request with the latest AC version as our releases are made so that if a method signature fails, the CI build would fail in a visible fashion? Similar to the dependabot PRs that are automatically made in this project.

**Comment by rfk** [comment]
> Would it make sense if a bot made a pull request with the latest AC version as our releases are made so that if a method
> signature fails, the CI build would fail in a visible fashion?

This sounds amazing! 👍

**Comment by jonalmeida** [comment]
I filed this for myself to investigate as well: https://github.com/mozilla-mobile/relbot/issues/52
