### ISSUE TITLE
Symbolicate crashes in XCode / iOS

### ISSUE THREAD

**Issue by nbhasin2** [mozilla/application-services#3907]
We see crashes in XCode in our production app but cannot debug as they aren't symbolicated. Since we have Glean in A~S and will also add Nimbus I feel having symbolicating crashes will help in better debugging when crashes happen.

Ref issue: https://github.com/mozilla-mobile/firefox-ios/issues/7588

![](https://user-images.githubusercontent.com/8919439/97471385-0ac07e00-191f-11eb-8869-3ff54de01dcd.png)

![](https://user-images.githubusercontent.com/8919439/97471456-23309880-191f-11eb-8e94-874219cb83a8.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2604)
┆Epic: Important backlog

**Comment by rfk** [comment]
Unfortunately the current appservices team does not have much experience with iOS crashes or symbolication (or XCode in general to be quite honest) but we're happy to help here if we can. I'm not sure where to start though. @nbhasin2 I recall a slack conversation about `.dsym` files, so I had a quick look at the latest release published to github.

The source file [MozillaAppServices.zip](https://github.com/mozilla/application-services/releases/download/v72.1.0/MozillaAppServices.framework.zip) is, IIUC, what gets pulled in by Carthage when building firefox-ios. It contains both `Carthage/Build/iOS/MozillaAppServices.framework/` which the compiled code, and what looks like a corresponding `Carthage/Build/iOS/MozillaAppServices.framework.dSYM/Contents/Resources/DWARF/MozillaAppServices` which claims to be a "dSYM companion file":

```
[rfk] repos/mozilla-mobile/firefox-ios (git)-[master] % file Carthage/Build/iOS/MozillaAppServices.framework.dSYM/Contents/Resources/DWARF/MozillaAppServices
Carthage/Build/iOS/MozillaAppServices.framework.dSYM/Contents/Resources/DWARF/MozillaAppServices: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dSYM companion file x86_64] [arm64]
Carthage/Build/iOS/MozillaAppServices.framework.dSYM/Contents/Resources/DWARF/MozillaAppServices (for architecture x86_64):     Mach-O 64-bit dSYM companion file x86_64
Carthage/Build/iOS/MozillaAppServices.framework.dSYM/Contents/Resources/DWARF/MozillaAppServices (for architecture arm64):      Mach-O 64-bit dSYM companion file arm64                                
```

But I don't know enough about iOS built stuff to know whether this file is or could be helpful.

**Comment by rfk** [comment]
(Which is to say, this doesn't currently seem actionable by our team without more guidance on what you need - I had kind of hoped that we were just accidentally not including the symbols in the release bundle, but AFAICT we produce and ship the same "dSYM companion file" setup as you get from other Carthage dependencies).

**Comment by rfk** [comment]
Possibly a Dumb Question (tm) but @nbhasin2, to help me flesh out my own understanding of the setup here - do we currently have working symbolication for other Carthage dependencies?

**Comment by nbhasin2** [comment]
@rfk that's actually a really good question, I took a look at Sentry and our crashes in XCode organizer and we do get crashes from other Carthage dependencies. Below are some crashes from our linked frameworks using Carthage

- 1Password Extension framework - https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-320/issues/729280 
<img width="932" alt="image" src="https://user-images.githubusercontent.com/8919439/110555592-db125580-810a-11eb-8028-294d294c66cc.png">

- Leanplum - https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-320/issues/730935/
<img width="863" alt="Screen Shot 2021-03-09 at 7 10 17 PM" src="https://user-images.githubusercontent.com/8919439/110555723-1745b600-810b-11eb-8314-8ae23b44e8d4.png">

**Comment by rfk** [comment]
Great, thanks! So I guess it may indeed be something specific to pre-built dependencies. (Surfacing an earlier comment from Slack, there does seem to be something of [a history of Carthage debuggability issues with pre-built dependencies](https://github.com/Carthage/Carthage#dwarfs-symbol-problem), although I won't pretend to have any deep insight on that front).

An open-ended question...how much of a pain would it be to try doing a local build of AppServices as part of a firefox-ios release, rather than consuming the prebuilt binary dependency? Even if that's not something we want to do by default, it may be useful to try once, to help us kind of bisect the source of the issue here. (But I can imagine that may not be a particularly straightforward thing to try out! Just thinking through our options.)

**Comment by nbhasin2** [comment]
@rfk Thats a good idea and afaik we can publish locally built A~S to AppStore. Its not ideal but good for testing. We can send a Firefox iOS beta build with locally built A~S binary that way we can ask some folks to try it out and gather data from it and see if we get any symbolicated crashes 🤞🏼 

Suggestion: We should add a simple crash method in locally built A~S that we can hook up to Firefox iOS debug menu to force a crash from within A~S and expect symbolicated crash on Firefox iOS sentry

**Comment by nbhasin2** [comment]
@rfk Thats a good idea and afaik we can publish locally built A-S to AppStore. Its not ideal but good for testing. We can send a Firefox iOS beta build with locally built A~S binary that way we can ask some folks to try it out and gather data from it and see if we get any symbolicated crashes 🤞🏼 

Suggestion: We should add a simple crash method in locally built A-S that we can hook up to Firefox iOS debug menu to force a crash from within A~S and expect symbolicated crash on Firefox iOS sentry

**Comment by rfk** [comment]
> Suggestion: We should add a simple crash method in locally built A-S that we can hook up to Firefox iOS debug menu

Yes, I like this a lot. In fact, it may be worth having both the ability to crash in the Rust code (some sort of uncaught panic?) as well as in the Swift wrapper code (maybe using a try! on something known to always throw?).

**Comment by rfk** [comment]
(Moving this into the upcoming sprint, not because I think I can solve the issue, but because I intend to help pus the above testing idea along as much as I can)

**Comment by rfk** [comment]
> Suggestion: We should add a simple crash method in locally built A-S that we can hook up to Firefox iOS debug menu

@nbhasin2 I had a go at implementing such an API over in https://github.com/mozilla/application-services/pull/3923. Let me know what you think, and if there's anything I can do to help you plumb it into the debug menu (e.g. if you need it in a release vs from a local build).

**Comment by rfk** [comment]
Jeff Boek and I chatted about the next steps here earlier today, and I wanted to capture some points on the current state of affairs, for reference.

The above-mentioned "crashtest" lib is available in the latest releases of Application Services, `v73.0.2` or later). In order to use that, unfortunately you will also need to apply the breaking-API fixes for compatibility with `v73.0.0`, which are available in this PR: https://github.com/mozilla-mobile/firefox-ios/pull/8044.

I left some notes [here](https://github.com/mozilla/application-services/pull/3923#issuecomment-797165721) about using the crashtest lib, or you can view [our own `.swift` test file](https://github.com/mozilla/application-services/blob/main/megazords/ios/MozillaAppServicesTests/CrashTestTests.swift) to see it in action.

As discussed above, it may be that doing a local build of appservices rather than consuming the published binary artifacts will make a difference here. We recently landed some fixes to the local development workflow for appservices+firefox-ios, in theory you can make a local build of appservices and make it available to your local carthage setup by doing:

```
./appservices_local_dev.sh enable /path/to/checkout/of/application-services
```

This needs to be run after any changes to application-services in order to re-build and re-copy the library, but it's a nice little convenience for what would otherwise be a tedious manual copying process.

**Comment by boek** [comment]
We'll be upgrading Application Services this week and I will investigate further 👍

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866335

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
