### ISSUE TITLE
update the all_tests script to be able to run specific to a component.

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3994]
Instead of having to run `./automation/all_tests.sh` and have it build and test the entire repo, it should be possible to run `./automation/all_tests.sh <component>` and have it run all the tests for the specific component that I'm working on.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2142)
┆Story Points: 3
┆Epic: Onboarding
┆Sprint: SYNC - 2021-05-14

**Comment by bendk** [comment]
[testDebugUnitTest.zip](https://github.com/mozilla/application-services/files/6406393/testDebugUnitTest.zip)

Here's a copy of the test report.  It looks to me like the issue might be `java.lang.RuntimeException: failed to instrument android.content.pm.PackageManager$NameNotFoundException`, but I'm not really sure.

Can anyone recognize what the issue is here?  Are there steps I could take to debug it further?

**Comment by bendk** [comment]
Just merged in some code that adds the `automation/tests.py` script.  That doesn't exactly implement this, but I think it covers the use case if you use the `changes` mode.  In that mode the script calculates which packages have changes in them from the `main` branch and runs tests/clippy/fmt on those packages only.
