### ISSUE TITLE
Investigate if we can move the autofill encryption logic to the support crate

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4059]
Time box investigating how to move the [encryption logic](https://github.com/mozilla/application-services/blob/main/components/autofill/src/encryption.rs) from autofill to [the support crate](https://github.com/mozilla/application-services/blob/main/components/support) so that it can be used in logins and autofill to a few hours. If there isn't a simple solution, we'll copy the encryption logic from autofill to logins.

┆Issue is synchronized with this [Jira Spike](https://jira.mozilla.com/browse/SYNC-2179)
┆Story Points: 1
┆Epic: Logins uniffi and update
┆Sprint: SYNC - 2021-05-14

**Comment by mhammond** [comment]
Note that I don't think it's worth making a new crate for what's just a few lines of code. There's no logic there really - there's not a single "if" statement or loop. It's a very thin wrapper around what's *already* in a support crate.

**Comment by bendk** [comment]
So, I took this one last night to work on.  A big part of it was just to improve my rust knowledge, because the biggest challenge was updating the error handling code.  I have some code that seems to work, but I do agree that there's not much benefit.

The part that seems most worthwhile to refactor are the modules-level FFI functions (`encrypt_string()` and `decrypt_string()`).  It feels a bit weird to have multiple copies of those and that could be compounded if we ever needed to support more types (e.g. `encrypt_int()`).  That said, it's not really that bad and lougenia was saying that maybe we handle those some other way.
