### ISSUE TITLE
tests.py: FileNotFoundError: [Errno 2] No such file or directory: PosixPath('gradlew')

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#4084]
In my WSL environment:

```
skip@eden:/mnt/c/src/moz/application-services$ ./automation/tests.py gradle

Running gradle tests
gradlew test

------------------------------------------------------------------------------

Unexpected exception while running gradle tests
Traceback (most recent call last):
  File "./automation/tests.py", line 301, in run
    self.func(*self.args, **self.kwargs)
  File "./automation/tests.py", line 253, in run_gradle_tests
    run_command([GRADLE, 'test'])
  File "./automation/tests.py", line 66, in run_command
    subprocess.check_call(cmdline, **kwargs)
...
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('gradlew')
```

(same error if I execute `automation/tests.py gradle` (ie, no leading `./`)

`PROJECT_ROOT` is `.` and `GRADLE` is `gradlew` - which surprises me, but I'm not familiar with pathlib.

Changing to `PROJECT_ROOT = Path(__file__).parent.parent.resolve()` fixes the problem but doesn't seem completely correct - it's not clear (a) why GRADLE doesn't end up as "./gradlew" (it does using `os.path.dirname()/.join()` etc), (b) whether always specifying the fully qualified path, symlinks and all, is the right thing and (c) how it works for anyone? Hence no PR yet :)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2195)
┆Epic: local development, ci and release (backlog)
┆Sprint: Backlog

**Comment by rfk** [comment]
This happens for me as well. So IIUC, the pathlib stuff is helpfully normalizing away the leading `./` from `./gradle` because *as a file path* it's redundant. But it's really important when trying to execute it *as a command* because otherwise we'll look for it in `$PATH`, fail to find it, and error out.

I think a good approach here would be to `resolve()` the value in `GRADLE` so that we're passing a full path when launching the subcommand.
