### ISSUE TITLE
Avoid unwraps on `duration_since` calls

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#413]
In `impl From<SystemTime> for ServerVisitTimestamp` and `impl From<SystemTime> for Timestamp` we have copy-pasta'd 

`let d = st.duration_since(UNIX_EPOCH).unwrap(); // hrmph - unwrap doesn't seem ideal`

And indeed it's not ideal. We should make some effort to either remove this, or ensure it really isn't possible for it to be hit.

Followup from #389

**Comment by rfk** [comment]
This is labelled "ship-ready", do we need to return to this before Fenix MVP beta, or Fenix MVP release?

**Comment by mhammond** [comment]
I'd suggest "should" for beta, "must" for release

**Comment by rfk** [comment]
Is it just this `unwrap` that we're worried about, or our use of `unwrap` in general?

**Comment by mhammond** [comment]
@thomcc will correct me if I'm wrong, but it's subtle. Most unwrap calls which aren't in test code should be considered suspect and have a nice big warning about why, however, there are exceptions to the rule - eg, it's canonical to call unwrap after locking a mutex - eg [Most usage of a mutex will simply unwrap() these results, propagating panics among threads to ensure that a possibly invalid invariant is not witnessed.](https://doc.rust-lang.org/std/sync/struct.Mutex.html)

**Comment by thomcc** [comment]
It's just this unwrap I guess, since it will fire on users with a misconfigured clock.

In general we handle panics by turning them to errors/exceptions on the other side of the FFI, and that's true here too. Honestly, I'd be fine with closing this issue, and don't think it's really required for ship readiness. That said, we could also just change it to unwrap_or_default() just as well.
