### ISSUE TITLE
Error when trying to pair my phone and browser 

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4215]
Preconditions:
  - My phone already had a different FF account enabled, but I signed out from it.

Steps to reproduce:
  - Connect to my FF account on desktop (version: `91.0a1 (2021-06-15) (64-bit)`)
  - Click the "Connect another device" tab and the "Show code" button
  - Open FF on my phone (version `89.1.1`)
  - Open a new tab, click the scan button, and scan the image
  - Get the error message "Pair using an app" ... "Did you use the system camera?  You must pair from within a Firefox app"

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2255)
┆Sprint: Backlog

**Comment by rfk** [comment]
> Open a new tab, click the scan button, and scan the image

Unfortunately doing an "ordinary" QR-code scan doesn't work here, on the phone you have to go into settings and click "sign in to sync" and then it will give you the option to scan the code rather than entering a username and password. The "did you use the system camera" help text likely needs to be updated to reflect this :-/

**Comment by bendk** [comment]
Interesting, I'll close this one then.  I wonder if the user from https://bugzilla.mozilla.org/show_bug.cgi?id=1716177 was doing the same thing.

**Comment by mhammond** [comment]
I suspect so - IIRC, the "final notice to enable sync" etc emails are targeted at getting you to first install Firefox. It's perfectly reasonable to assume that the QR code would be to pair if you have firefox installed.
