### ISSUE TITLE
Create a plan for uniffi-ing and shipping push component

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4395]
Push component is currently only consumed by Fenix.  We want to uniffi it and ship the changes into Fenix. 

For this issue to be done - we should have a clear plan and issues created for the steps to uniffi the component, resolve any breaking changes in Fenix and ship to nightly.

Reference: https://mozilla.github.io/application-services/book/howtos/converting-a-component-to-uniffi.html as a guide for the process.

┆Issue is synchronized with this [Jira Spike](https://mozilla-hub.atlassian.net/browse/SYNC-2739)
┆Story Points: 3
┆Epic: Uniffi Push Component
┆Sprint End Date: 2021-09-03

**Comment by tarikeshaq** [comment]
Went through our codebase to identify what needs to change, here's a concrete list I noted down.

My _naive_ opinion is that this should be done in two PRs in A-S and one in A-C. One prepares rust/android API for uniffication, and the other does the rest. The epic would have a third ticket for resolving breaking changes on Android - I tried to carefully annotate those in my notes:

### Task 1: Prepare API for uniffication:
 - `PushManager subscribe`:
    - Move the `app_key` checking from the FFI layer down to the rust code
    - Have the function return `SubscriptionResponse` directly instead of having the FFI layer map to it
 - `PushManager verify_connection`:
    - Have the function return a vector of PushSubscriptionChanged, instead of mapping to it in the FFI layer
 - `Push Manager decrypt`:
    - Make the rust code return do the json work that the android layer does, and return a `Vec<u8>`, make the android code return a byte[]. **THIS IS A BREAKING CHANGE**, the consumer can then create the `ByteArray` type if they would like (which is what the android layer is currently returning
    - Move `uaid` retrieval from the FFI layer down to the PushManager function
 - `PushManager dispach_info_for_chid`:
    - Have push manager return `Option<DispatchInfo>` directly
    
  Note that this first tasks won't be super pretty, because the PushManager will be returning the protobuf structs directly, but it helps make the next task more or less trivial, and it'll be okay once we get rid of the protobufs
  
### Task 2: uniffi all the things
Steps to do this will follow this amazing doc https://mozilla.github.io/application-services/book/howtos/converting-a-component-to-uniffi.html?highlight=uniffi#first-get-familiar-with-uniffi

Here's what I imagine the UDL to look like https://gist.github.com/tarikeshaq/c179f2ee437c26611ce2e6b8d27cf529
Note that this changes the `Subscribe` API to take the config directly, and this will be a **BREAKING CHANGE** as A-C will have to do that

### Task 3: Resolve breaking changes in A-C
Not noting down too much here other than the pointed-out breaking changes above.

As we wrap up the uniffication, more breaking changes might pop up


Thoughts @mhammond? (also @skhamis since you recently uniffied components 😄, any big steps I seem to be missing?)

I'll go ahead and create the three tickets, the component is small enough that I think this can be done in 1 sprint (or less), but famous last words...

**Comment by jonalmeida** [comment]
From the AC consumer side, this sounds mostly fine to me.

We do have one oddity with the push component that I can't tell how it would be covered with uniffi: we cannot construct the `PushManager` without an initial token (which comes from a push service async) and [use a nullable check](https://github.com/mozilla-mobile/android-components/blob/main/components/feature/push/src/main/java/mozilla/components/feature/push/Connection.kt#L174-L184) to know if calls like `subscribe`/`unsubscribe` should early return based on that.

Will uniffi allow us to keep that logic since I doubt we're going to fix the internals of push with this change to allow for a better API?

**Comment by tarikeshaq** [comment]
@jonalmeida The work here should allow us to keep that logic, at worst the types might change a little, but overall it shouldn't make it worse 🤞 ... it doesn't help directly with that problem either 😞 That all said, with the component uniffied, changes to the API surface _should_ be cheaper for other changes 👀

**Comment by mhammond** [comment]
That sounds fine to me, although I guess I'm not sure where you plan landing this stuff given task1 and task2 have breaking changes - maybe 2 tasks landing in a single PR? Happy to work it out as we go though...

**Comment by tarikeshaq** [comment]
@mhammond looks like the first task didn't end up doing the breaking change 😄 #4423 (will take on that on the second task)

That said, I'm planning to have the second task be a single PR that lands on main, with a few of PRs that land on top of that PR's branch - just for simplicity of review, the PRs will looks something like:
- Adding the valid UDL
- The rust library compiles with scaffolding included
- Removes the ffi crate 
- Replaces the protobuf types with rust types
- Includes the Kotlin bindings and cleans up the kotlin API

The hope is that each one is decently small, and once they all are a part of the branch, we can land them all together in one PR

Either ways, I think this issue has served its purpose (the tasks were defined, and we have a plan to get this merged) so I'll close it off
