### ISSUE TITLE
FxA Login screen on iOS showing blank

### ISSUE THREAD

**Issue by skhamis** [mozilla/application-services#4815]
initial investigation (+ extra investigation help from @teshaq ): FxA is failing to get the webview URL to display to the user  — leaning that there is potentially some issue with FxA using the right persistence layer or failing to get the right url from the network. 
Couple things we know:
1. It does hit the rust layer fine, so does other components so doesn't seem to be an issue with bindings:
2. Nimbus + Viaduct work on Focus iOS so it’s not a Viaduct-doesn’t-work-in-SPM-situation

Will need to comb through how FxA works with Fx-ios and where the actual failure is coming from

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/SYNC-3041)
┆Story Points: 5
┆epic: FxA Ecosystem (backlog)
┆sprintEndDate: 2022-02-03

**Comment by tarikeshaq** [comment]
Alrighty, I'll close this on our side, the fix is released in https://github.com/mozilla/rust-components-swift/releases/tag/91.0.1 and iOS has a PR https://github.com/mozilla-mobile/firefox-ios/pull/9942 that uses it and fixes the problem. 

I filed a couple of follow-ups on our side: 
-  #4820: Since all the components are exposed as exactly one library now, they are all in the same namespace, meaning any name-conflicts **across components** will fail to compile. We should have a good story for this.
- #4821: We can optimize focus-ios's experience by only loading in the Megazord the libraries they need. They probably get a lot of bloat now
