### ISSUE TITLE
Skipped installing application-services binary due to the error: Incompatible Swift version - framework was built with 5.3.2 and the local version is 5.6

### ISSUE THREAD

**Issue by imnotabr** [mozilla/application-services#4923]
I'm working with an older version of Firefox (version 38 build 50).

When I moved to Xcode 13 to run the app on iOS 15.4, I use 

`carthage bootstrap --platform ios`

and I get the following error:

```
Skipped installing application-services binary due to the error:
	"Incompatible Swift version - framework was built with 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28) and the local version is 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)."
```

How do I fix this issue?
![Skipped installing application-services binary due to the error](https://user-images.githubusercontent.com/62814903/165160750-34caef07-388b-4bc0-a62f-cdf2b2eafcfd.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3145)

**Comment by skhamis** [comment]
Hi @imnotabr,
Xcode generally couples swift versions with their releases. Upgrading XCode means you're generally using a newer swift version (and it's strict about using same compiled versions as you can see) -- your two options most likely are:

1. Use an older XCode version (that has the 5.3.2, swiftland-1200.0.45 version) 
2. If you need XCode 13+, you'll need to specifically download the swiftlang 5.3.2 toolchain and tell Xcode to use that version https://github.com/apple/swift/releases

**Comment by imnotabr** [comment]
I can try the swiftlang 5.3.2 toolchain, but I'm reading below that "To submit to the App Store you must build your app using the version of Swift that comes with". So do I have no choice but to use Swift 5.6?

https://www.swift.org/download/#snapshots

![To submit to the App Store you must build your app using the version of Swift that comes with](https://user-images.githubusercontent.com/62814903/165179987-298c4075-fa62-43de-9240-6c9d9b631d84.png)

https://developer.apple.com/forums/thread/697110?answerId=699301022#699301022

On the Apple developer forums someone else had a similar problem, the solution mentioned is that "Your library needs to be [built from source as part of your project,](https://developer.apple.com/library/archive/technotes/tn2435/_index.html#//apple_ref/doc/uid/DTS40017543) or if it's a pre-compiled library, [it must be built as an XCFramework.](https://developer.apple.com/videos/play/wwdc2019/416/) Swift has never guaranteed that compiled modules are compatible across complier versions outside of following those two options."

How would I do this?

**Comment by skhamis** [comment]
Are you attempting to build an older version of Firefox to submit it to app store? From the screenshot you won't be able to use XCode 13+ as that comes with swift 5.6. 

However, I do highly recommend using the latest version as you'll run into the least amount of problems -- that being said -- from an application-services perspective...

Here are a couple of things you'll need to work though:
- Both firefox-ios and application-services moved away from Carthage earlier this year, since you're trying to build Firefox from October, 2021 I suggest using an application-services build around that time too:
  - You'll have to patch in some updates to get it running on Xcode 13
  - You'll need to patch in any updates 

Then you'll need to build the carthage binary locally: you'll have to use an old version a-s https://github.com/mozilla/application-services/blob/88207972e306299e78f91af349fa19bc1b59607e/docs/howtos/locally-published-components-in-ios.md

**Comment by skhamis** [comment]
Closing this issue since this is an unsupported method and not an actual bug --  the above comment should be able to get you in the right direction regarding what you're trying to do.
