### ISSUE TITLE
Refactor error handling code

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#4980]
Our error handling code is unnecessarily complex ([see the logins code for an example](https://github.com/mozilla/application-services/blob/main/components/logins/src/error.rs)).

I think there's a few cleanups that could help this significantly:
  - **Don't mix `thiserror` with `error_support`**.  Both of these crates are trying to do the same thing and it's redundant and confusing to use both.  In that logins example, `thiserror` defines a error conversions, messages, and an `std::error::Error` impl for the `ErrorKind` enum, but we don't actually use those because `error_support` defines the same things for the `Error` type.  We should use one or the other, probably `thiserror` since it has more features and is more ergonomic. 
  - **Document the internal -> public error conversion**.  Most of our components define an internal error type and an public error type.  Having this split allows us to keep the public API consistent and not introduce breaking changes for our consumers.  I'm not sure it's totally necessary and at some point we might consider combining these into a single type, but for now let's at least document what's going on and why.
  - **Separate error conversions from error logging**.  The `From` impl that converts internal errors to public errors also contains a bunch of `log::error` statements, which cause errors to be reported to Sentry on Fenix.  Having this functionality in the `from()` function is confusing and we should extract it into a dedicated error reporting function.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3190)
┆sprintEndDate: 2022-06-24

**Comment by mhammond** [comment]
Thanks for opening this - I agree!

> * **Document the internal -> public error conversion**.

I'd suggest we try and take this further - try and *avoid* a distinction between internal and public errors where possible - I don't see much justification for different sets of errors, and in most cases, the distinction was really just due to the fact we had hand-written FFI written after the component itself.

(It's not clear how feasible it would be to fix this for existing components, but it's probably worth a try, and will certainly help inform what we should do moving forward.)
