### ISSUE TITLE
Expose hashed_fxa_uid from sync to logins

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#505]
Split off from #434 (which is about exposing it for non-sync users, which seems separate enough to be a different issue to me).

In particular we need to provide https://github.com/mozilla/application-services/blob/1fa9ec922c4f5c38b37ceff8d3b1fa32ae1e9404/components/sync15/src/token.rs#L36 to logins

The largest difficulty here are around the fact that we don't persist data except for what's stored in GlobalState, which doesn't include this outside of a sync. That said, I don't think this is *that* difficult to work around, just annoying.

**Comment by mhammond** [comment]
I missed #434, which is a shame, as I would have strongly advocated for us getting the hashed uid in the same way we get the unhashed version - I don't see any privacy concerns with this and it would address a current limitation when sync fails due to a token-server error.

Regardless, shouldn't we just push ahead with #490? Ideally Lockbox would also submit the sync ping directly even if it also decides to unpack some of the data in that payload and use it to submit additional telemetry. #490 doesn't address returning the collected data, but that seems fairly easy to do, and IIUC is forward-compatible with the general telemetry strategy (ie, that submitting the telemetry will always be the responsibility of the embedding app)

(The device-id is another thorn in our side, but I think that's probably OK - there's no reason the embedding app can't be relied upon to augment our telemetry data with additional context only it knows)
