### ISSUE TITLE
Combine sync15 and sync15-traits

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5087]
Have both of these as separate crates adds extra complexity to the API.  For example #5083 changed things so that `sync15` re-exports some of the `sync15-traits` functions, this means that `sync15` now has 2 error types `Error` and the re-exported `SyncTraitsError`.

The main functionality that `sync15` adds over `sync15-traits` are standalone sync engines, which are only used on iOS and we want to replace that with `SyncManager`.  The main reason that they are separate crates is for desktop.  Desktop doesn't want to pull in all the dependencies of `sync15` so it just depends on `sync15-traits`.

Once iOS uses `SyncManager`, we should consider take a pass at trying to consolidate this code:
  - At that point, a lot of of the `sync15` functionality canl be deleted or moved into `sync-manager`
  - Any remaining functionality could be moved into `sync15-traits` and put behind a feature flag that desktop doesn't enable.
  - We could consider renaming `sync15-traits` at that point, maybe to `sync15-types` or maybe just `sync15`?

We could also do this work earlier, but it better to wait until we don't need to support standalone sync engines since that will make the task a lot easier.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3258)

**Comment by mhammond** [comment]
I'm quite keen on doing this sooner rather than later, mainly because things are getting messy, and some of the refactoring I'm playing with to better integrate "bridged" engines and "normal" engines is making it messier - particularly around things being `pub` that really should not need to be.

We've already started to use features in sync15-traits (so tabs on mobile can use the "full" sync" while tabs on desktop can use just the bridged sync) - so I think we should lean into them even more. Something like:

* sync15 gets features:
  * `crypto` - means all the crypto parts
  * `bridged-engine` means just code needed to implement the bridged engine (ie, desktop syncing) is supported.
  * `sync-engine` means the code needed to implement a `SyncEngine` - this implies `crypto` - *note* - the future intent is to merge `bridged-engine` and `sync-engine`, but that will not happen in the first instance. This *might* need to imply `crypto` in the first instance, but eventually will not.
  * `sync-client` means the code needed to be a full "sync client" - ie, do full management/initialization of server storage, keys, etc and sync one or more engines. This implies `crypto` but need not imply either of the `-engine` features.

What this would mean to our crates:
* sync15-traits is removed entirely.
* tabs gets its own features which selectively enable `sync-client` (used when iOS asks for tabs to sync), `sync-engine` (used when the sync manager or ios asks tabs to sync) and `bridged-engine` (used inside desktop.)
* places and most other components enable `sync-client` and `sync-engine` for the same reasons as tabs, but at this time does not need `bridged-engine`
* fxa-client enables `crypto` (as that's the only sync feature needed for send-tabs.

Then in a future when iOS uses the sync manager, the sync manager would be the only crate that enables `sync-client`

If that sounds OK, then I'm happy to bikeshed names!

My plan of attack here is:
* Restructure sync15 to make it easier to enable these features - eg, a new "sync_client" submodule where almost everything that's specific to just the "sync-client" feature lives - but don't actually add any features at this stage.
* Enable those features in sync15, but don't yet move sync15-traits in.
* Move sync15-traits in to the feature-enabled sync15

with each step getting reviewed and landing separately.

WDYT?

**Comment by bendk** [comment]
This seems great to me, including the names.  One question I had was how would the features work with UniFFI?  Would tabs have to have stub implementations for disabled features, or should we add some sort of feature support to UniFFI?

In any case, I think this is definitely a step forward.

**Comment by mhammond** [comment]
> Would tabs have to have stub implementations for disabled features, or should we add some sort of feature support to UniFFI?

That's a great question - we will needs stubs. I first thought about features, but ended up struggling with what the foreign bindings should do about them - how do we communicate to uniffi-bindgen when making the foreign bindings what features should be assumed as enabled in the .so? And what would they generate for features it is told are disabled?

(I guess we should discuss this in a uniffi issue :)

**Comment by tarikeshaq** [comment]
Closing as this was done in #5125
