### ISSUE TITLE
History syncing doesn't delete visits

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5472]
I'm pretty sure this is how we sync history visits for each record:
  - We fetch the history record from the server, which contains the "20 most recent visits" for the URL.
  - We insert a row for any visit, skipping visits that we already know about:
      -  In [`plan_incoming_record()`](https://github.com/mozilla/application-services/blob/main/components/places/src/history_sync/plan.rs#L66) we filter out visits that match a row in `moz_historyvisits` with the same timestamp/transition pair.
      - In [`apply_synced_visits()`](https://github.com/mozilla/application-services/blob/main/components/places/src/storage/history.rs#L867) we skip over visits that match the timestamp from `moz_historyvisit_tombstones` (this is slightly inconsistent with how `plan_incoming_record` uses timestamp+transition, but that's not a big issue).
  - We then send the history record with our most recent 20 visits as an outgoing record -- if we detect local changes from the server.

If I'm correct about the system, this does not allow clients to signal deletion of visits.  For example:
  - I visit a [this-week-in-rust](https://this-week-in-rust.org/) on my desktop
  - I sync my desktop and phone, now my phone has the visit in it's database
  - On my desktop, I delete history from the last hour.  This deletes the visit, but not the history record since I have older visits to this week in rust.
  - I sync on desktop, results in a history record for https://this-week-in-rust.org/ without the latest visit
  - I sync on my phone, which sees the history record with the missing visit.  It assumes the record is incomplete and uploads a history record with the visit back
  - When desktop syncs, it has the visit in it's tombstones, so it doesn't re-add the visit.  However, the visit is still on my phone.

I tried to test that this morning and this seemed to be the result -- although it seemed like I needed to sync several times before history sync worked as I expected, so maybe I'm missing something.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3681)

**Comment by bendk** [comment]
I think the solution here is to include tombstones in the latest 20 visits that you sync.  In the abstract this means that the `HistoryRecord.visits` list would include both "live" visits and tombstones.  In reality, we can't change the behavior of that field since we need to be compatible with older clients -- even if we implement sync payload evolution.  However, we can use a new field for it:
  - `visits` continues to store live visits
  - `visit_tombstones` stores a list of timestamps for tombstone visits
  -  The combined size of `visits` and `visit_tombstones` is 20.

I guess we need to wait for history records to support payload evolution before we can do this.

**Comment by mhammond** [comment]
Agree with everything, although:

> latest 20 visits that you sync

Only tangentially related to this ticket, 20 smells quite arbitrary - I wonder if we should have a more adaptive number - like tabs, "as many as can fit" seems ideal?

**Comment by bendk** [comment]
> Only tangentially related to this ticket, 20 smells quite arbitrary - I wonder if we should have a more adaptive number - like tabs, "as many as can fit" seems ideal?

Makes sense to me.  Maybe something like `payload_limit / avg_visit_size / 2`.  I think it could also be dynamic: each client could decide how many visits to try to fit in when they synced.  But my instinct is to keep it simple by using a fixed number.

**Comment by linabutler** [comment]
> If I'm correct about the system, this does not allow clients to signal deletion of visits.

You're totally correct about this! It's a long-standing limitation of Sync that there's no way to represent deletions of individual visits for a page. (Even deletions of entire pages don't work reliably, because of #5487—the same URL might have different GUIDs on different devices 😢).

I remember a couple of concerns that we had the last time we explored this, and thinking through them was tricky enough that we decided the "best worst" option was to defer it:

* Privacy.
* Interactions with "Clear Recent History".

The privacy concern was that storing tombstones for visits could leak a user's behavior. Because visits don't have GUIDs, we can only identify them by their timestamps—so we wouldn't just have a record of the user visiting a page at a certain time, we'd also have a record of them wanting to hide that visit.

The other concern was how this would interact with "Clear Recent History", and the related option in Desktop to delete all your history when the browser is closed. Both of these features delete many visits in a time range, and it seemed like we'd also want to support this if we supported deleting individual visits. But this got tricky quickly: would we need to reupload _all_ records for pages visited in the cleared time frame? And, if you cleared some / all your history on Desktop, would it be surprising to have those visits also disappear on all your other devices connected to your account?

Those were some of the things we thought about, and, unfortunately, I don't think we ever figured out good answers to either of those questions, or how we'd explain the behavior to users—and we eventually moved on to higher-priority things 🥺

I really am excited that you're looking at this with fresh eyes, though, and don't want to deter you from it at all! Maybe the answer is decoupling deletion of individual visits from ranges, maybe it's finding a way to represent deletions in a private way, maybe it's not as much of a privacy risk as we thought back then, or maybe we can find a way to give visits a stable identity, or, or...

**Comment by bendk** [comment]
Yeah this is definitely tricky.  I'll make a couple points and continue to think about the rest:

 - App-services's has `moz_historyvisit_tombstones` table, which makes me think that our mobile behavior isn't consistent with those privacy guidelines.
 - "And, if you cleared some / all your history on Desktop, would it be surprising to have those visits also disappear on all your other devices connected to your account" -- for it would be surprising for it *not* to clear that history from other devices and I would consider it a privacy issue.  But I'm not the typical user and we should definitely investigate this a bit more before making this change.
 - From a privacy and efficiency standpoint, it seems better to store the set of cleared time ranges rather than invididual tombstones.
 - If we did that, we lose some flexibility like the allowing users to manually delete individual visits.  But I don't think that's possible now -- you can only delete pages from your history, which I think means uploading a tombstone for the entire record.  If we wanted to support it in the future, maybe we should have a different system anyways since I agree that storing tombstones is not great from a privacy perspective.

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866542

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
