### ISSUE TITLE
De-dupe history records on the server

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5487]
In the [history schema evolution PR](https://github.com/mozilla/application-services/pull/5470), Lina taught me that sometimes [we can have records on the server with the same URL, but different GUIDs](https://github.com/mozilla/application-services/pull/5470#discussion_r1169523979).

This leads to weird corner cases:  if the two records have different titles/unknown fields which one is the right one?  What happens if the relative order of the two records changes between syncs?  I think we should do something to try to fix this.

The first part is how this happens in the first place.  @linabutler can you expand on the steps to cause this?  Is there some way to prevent it from happening?

The second part is recovery.  If we see 2 incoming dupe records (i.e. records with the same URL, but different GUIDs), I think we should do a reconciliation that removes the dupe:
  - Figure out a deterministic way to pick the "real" record (maybe the lowest GUID).  This is the record that we will continue to use going forward.
  - That record's visit list is computed by merging the visits from all records together
  - For other fields like `title` and `unknown_fields` we have a couple options:
    - Use the value from the real record.
    - Use the value from the record with the latest visit
  - We upload the real record, for the other records we can either:
    - Upload a tombstone.  This seems nice, but we need to figure out how this would affect other clients.  We don't want this to delete their history.
    - Leave the record alone and don't upload anything for it.
 - If other clients add visits to one of the non-real records, then we should add those visits to the real record but not change it's GUID.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3687)

**Comment by linabutler** [comment]
Thanks for writing this up @bendk! I'm still thinking over your recovery strategy, but I can start with an explanation of how and why this happens.

> The first part is how this happens in the first place. @linabutler can you expand on the steps to cause this? Is there some way to prevent it from happening?

I think the easiest—and maybe only?—way this can happen for modern (since 2018) clients is when you connect a new device that has lots of existing history pages, and sync it with a Desktop client that already has some of those pages in its local history.

It comes from a combination of two underlying issues:

1. The server doesn't have a full record of your history. A first sync on a newly connected device (Desktop or mobile) will only upload up to 5,000 pages from the last 30 days.
2. Desktop doesn't dedupe history records. When Desktop applies an incoming history record, it'll take the visits from that record, but won't change the local GUID to match the remote record.

Here's a more concrete example:

1. You visit `http://example.com` on device A, a Desktop, more than a month ago—or maybe less than a month, but you visited many more pages since then. In A's local database, that page has `guidAAAAAAAA`.
2. You sign in to sync on device A. It does _not_ upload a history record for `guidAAAAAAAA`, because it's outside the initial limit.
3. Now you visit `http://example.com` on device B (doesn't matter if it's Desktop or mobile). In B's local database, this page has `guidBBBBBBBB`.
4. You connect B to the same account as A. As far as B knows, no other device has visited `http://example.com`—because A didn't upload a record for it to the server—so it _will_ upload a record for `guidBBBBBBBB`, with your most recent visit.
5. Now A syncs again. It'll see B's new record, and adds the visits for it (and also take its title), but associate those visits and page title with the `guidAAAAAAAA` page in its local database.
6. You visit `http://example.com` on A. When A syncs again, it'll upload a new record with `guidAAAAAAAA`, containing the most recent visit from B _and_ any previous visits from A, up to 20 total.
7. B syncs again. If it's a mobile client that uses Rust Places, it'll change its local GUID from `guidBBBBBBBB` to `guidAAAAAAAA` without uploading a tombstone for `guidBBBBBBBB`, and take the title and new visit(s) from A. Any new visits from B will now be uploaded in record `guidAAAAAAAA`. If it's another Desktop, it'll take the title and visits from A, and update its entry for `guidBBBBBBBB`, and any new visits from B will still be uploaded in record `guidBBBBBBBB`.

Before 2018, Desktop also stored the sync ID and last sync time in prefs. If Firefox replaced the Places database on startup due to corruption, Sync could start uploading new records with the same URL, because it didn't know that the database was replaced, and that it should re-fetch all history records from the server. Since Desktop and Rust Places have been storing that metadata in the `meta` table for a while, it's not an issue for recent clients, but we also didn't have a good way to fix up server collections that already had dupes.

> Does desktop not have the same de-duping code?

It doesn't, unfortunately—Desktop doesn't try to dedupe history records at all. It'll use an incoming record's `histUri` to look up the page in Places, and update the local title and visits with the incoming record's—but will not adopt its GUID.

**Comment by mhammond** [comment]
hrmph - I thought we had a unique index on moz_places to ensure there was exactly 1 place_id for a URL, but apparently not :( We should probably fix that too, right?

**Comment by linabutler** [comment]
> I thought we had a unique index on moz_places to ensure there was exactly 1 place_id for a URL.

Oh, this is a timely comment; I was just looking at this the other day, for a different project! 😆 Desktop did have that unique index at one time, but removed it in mid-2016, in https://bugzilla.mozilla.org/show_bug.cgi?id=889561, because it was taking up too much space.

I think that's where `url_hash` came from originally—and it has a non-unique index because it can collide. Places uses a combination of application-level `url_hash` and `url` checks to ensure uniqueness in `moz_places`, and we copied that approach in Rust Places in 2018.

**Comment by mhammond** [comment]
Yes! I meant to correct my comment as I don't think we can have a unique index, but we should be able to have a relatively cheap constraint?

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866526

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
