### ISSUE TITLE
Cleanup the jwcrypto error hierarchy

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5493]
For #5485 we added some new error handling and a new error type for `jwcrypto`.  Since `fxa-client` was still using the older APIs and older errors, we couldn't make the new errors as clean as possible.  Let's move Fxa to using the new `EncryptorDecryptor` struct, then cleanup the error hierarchy:

* Merge `JwCryptoError`  and `EncryptorDecryptorError`
* Make variants for build-in operations like canary checks rather than using hard-coded strings.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3692)
┆Epic: Wrapper-less FxA

**Comment by mhammond** [comment]
> Let's move Fxa to using the new `EncryptorDecryptor` struct, then cleanup the error hierarchy:

We briefly touched on this yesterday, but I wonder if we can also come up with a better way of managing all the various keys - I'm thinking something like a callback interface that allows us to fetch "secrets" by name - so instead of where we have logins and credit-cards and (presumably) fxa having signatures like:

`string encrypt_fields(SecureLoginFields sec_fields, [ByRef]string encryption_key);`

(which effectively mean that all these components need to copy/paste code to securely store the keys, etc), we end up with something that allows the component to ask for a key when it's needed, which might mean a single a-c component can be used for *all* secret management across all our components.

(Lots of devil in the detail (eg, we'd probably also need to integrate canary testing?), and I don't think we should derail this ticket by trying to do that in the first instance, but worth thinking about)

**Comment by bendk** [comment]
That sounds really great.  Even the part about integrating canary testing seems nice since it would eliminate the duplication between autofill and logins on a-c.

If we were starting from scratch with this design, I'd argue that we should have 1 local encryption key for everything.  I can't think of a simple migration path to that though.

**Comment by mhammond** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866528

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
