### ISSUE TITLE
The nimbus start up path is causing the main thread to hang on iOS

### ISSUE THREAD

**Issue by OrlaM** [mozilla/application-services#5561]
Sentry stack trace
https://mozilla.sentry.io/issues/4168572539/events/871455e7008a4d648d70efb147e681f7/

This hang event is triggered if the main thread stalls for 2 or more seconds.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3717)

**Comment by tarikeshaq** [comment]
cc @jhugman @jeddai

**Comment by jhugman** [comment]
Top of the stack trace might point something going on in uniffi-generated code. Since this is 1 case in the last 30 days on a fairly old device, I'm not overly worried concerned about this; however, if it becomes more prevalent, we should investigate further.

/cc @bendk 

[uniffi_core::ffi::rustcalls::make_call](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_core/src/ffi/rustcalls.rs#L101)
[ffi_nimbus_aa39_rustbuffer_from_bytes](https://github.com/mozilla/uniffi-rs/blob/a93713ac0c87d7a5dc69763e143cc2f39e34f3c6/uniffi_bindgen/src/scaffolding/templates/RustBuffer.rs#L15)
[RustBuffer.from(nimbus.swift:22)](https://github.com/mozilla/uniffi-rs/blob/main/uniffi_bindgen/src/bindings/swift/templates/RustBufferTemplate.swift#L11)
[makeRustCall<T>(nimbus.swift:257)](https://github.com/mozilla/uniffi-rs/blob/a93713ac0c87d7a5dc69763e143cc2f39e34f3c6/uniffi_bindgen/src/bindings/swift/templates/Helpers.swift#L63)

**Comment by OrlaM** [comment]
Also meant to add thanks for looking into it!
