### ISSUE TITLE
Nimbus groovy plugin should first attempt to get release artifacts before falling back to taskcluster

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#5605]
For 114 we had to land a patch release to point the nimbus groovy plugin to github again in #5602 

We should change it in main so that it checks the release artifacts before falling back to the index we use for nightlies

cc @bendk @jeddai

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3733)

**Comment by bendk** [comment]
I'm hoping the release artifacts actually end up in archive.mozilla.org, @ahal is actually testing some things out related to this right now.

Also, it should be possible to differentiate nightlies from real releases, although it would be slightly hacky (is the last component 14 chars long).  Maybe we could use that rather than try one and then fall back.  I don't have strong feelings either way here though.
