### ISSUE TITLE
Split `forUnitTests` configurations into separate Gradle projects

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#562]
Right now, we have N Gradle projects:

- fxaclient
- logins
- ...

Each of those projects contains multiple *configurations*:

- default
- `-withoutLib` (for megazords)
- `-forUnitTests` (for unit testing with Robolectric)

default and `withoutLib` produce AAR files for Android; `forUnitTests` produces a JAR file for unit tests.  Sadly, configurations just don't play well with Gradle composite builds.  There's no expectation that they will play well with composite builds any time soon, either.

This ticket proposes to separate the special `forUnitTest` configurations out into separate Gradle projects.  That is, we'll have 2*N Gradle projects:

- fxaclient
- fxaclient-forUnitTests
- logins
- logins-forUnitTests
- ...

Downstream consumers won't notice a change 'cuz we can keep publishing identical Maven artifacts.  Composite build consumers will be able to substitute in the unit test bits, which isn't possible right now.  And locally, we'll have finer-grained Gradle tasks, so that building an Android AAR won't necessarily produce Desktop libraries that are for unit tests only.

I talked this through with @grigoryk and think it's a nice win all around, but the proof will be in the pudding.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-96)

**Comment by ncalexan** [comment]
I don't have much insight into how to make composite builds play well with megazords and the `-withoutLib` configurations at this time.  I'm still trying to get to the bottom of that.

**Comment by rfk** [comment]
From triage: @ncalexan we need your help figuring out next steps and triage here please...

**Comment by ncalexan** [comment]
> From triage: @ncalexan we need your help figuring out next steps and triage here please...

Backlog: this isn't urgent.  It fits into a larger story around Gradle composite builds; I'll pick this up some lonely Friday afternoon.

**Comment by rfk** [comment]
IIUC this will be simpler after https://github.com/mozilla/application-services/pull/1103 lands, because we'll only need a `-forUnitTests` version of the megazord rather than one for each individual component. @thomcc does that seem right based on your work so far?

**Comment by thomcc** [comment]
This seems insufficient to make unit tested composites work. The issue is:

1. Rust libs are built into `$project.buildDir/rustJniLibs/desktop`, *not* `$rootProject.buildDir`. E.g. they're built into the build dir of whatever project is using `rust-android-gradle`.
2. Libs depending on rust libs need to arrange for that directory to be on the test resource path or the dlopen will fail. e.g. we had to add `test.resources.srcDirs += "${project(':full-megazord').buildDir}/rustJniLibs/desktop"` to all the local libs in #1103 in order to work around this.
3. There's no (sane) way for us to do the same workaround for a lib that's brought in as part of a composite build.

**Comment by eoger** [comment]
@thomcc still relevant with the new megazord?

**Comment by vladikoff** [comment]
@thomcc reopen this if still needed
