### ISSUE TITLE
Fix taskcluster cached optimization

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5681]
The `[ci full]` flag seems to cause all the `fetch` and `toolchain` tasks to run, but taskcluster should be able to recognize that they're cached and skip them.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3780)
┆Sprint End Date: 2023-07-03

**Comment by data-sync-user** [comment]
➤ Ben Dean-Kawamura commented:

I just tested this out and the none of the fetch tasks ran:

https://github.com/mozilla/application-services/pull/5693 ( https://github.com/mozilla/application-services/pull/5693|smart-link ) 

I’m pretty sure the issue is that certain changes make us rebuild the docker image, which forces the toolchain tasks to run.  This is not really optimal but not that bad either, since it’s only certain changes when combined with [ci full]
