### ISSUE TITLE
Data review: FxA error tracking metrics

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5872]
> 1) What questions will you answer with this data?

How often do operations with our fxa-client fail and in what ways?

> 2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

These metrics will allow us to measure changes in the quality of the fxa-client.  For example, the first use of these metrics will be to monitor the effect of the moving the FxA code from firefox-android into application-services:

* https://github.com/mozilla/application-services/pull/5851
* https://github.com/mozilla-mobile/firefox-android/pull/3918

> 3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

We also plan to use manual testing.  However these metrics will be better for detecting low-frequency bugs.

> 4) Can current instrumentation answer these questions?

No.

> 5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   

Measurement Description | Data collection category | Tracking bug 
--- | --- | ---
FxA operation count (counter) |  Category 2 "Interaction data" | [#5871](https://github.com/mozilla/application-services/issues/5871)
FxA error count (labeled counter, with these categories: network, authorization, fxa_other, unexpected) |  Category 2 "Interaction data" | [#5871](https://github.com/mozilla/application-services/issues/5871)

> 6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.

This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/

> 7) How long will this data be collected?  Choose one of the following:

I want to permanently monitor this data. (Ben Dean-Kawamura)

> 8) What populations will you measure?

All release channels, countries, and locales.

> 9) If this data collection is default on, what is the opt-out mechanism for users?

Standard Firefox telemetry controls

> 10) Please provide a general description of how you will analyze this data.

* When deploying changes to FxA, we will monitor changes in the telemetry.
* As part of triage, we will check to see that the error rates are roughly stable.

> 11) Where do you intend to share the results of your analysis?

The sync team

> 12) Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? If so:

No

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3959)
┆Epic: Moving fxa-client functionality out of android-components

**Comment by eliserichards** [comment]
> > 1. What questions will you answer with this data?
> 
> How often do operations with our fxa-client fail and in what ways?
> 
> > 2. Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
> 
> These metrics will allow us to measure changes in the quality of the fxa-client. For example, the first use of these metrics will be to monitor the effect of the moving the FxA code from firefox-android into application-services:
> 
>     * [New fxa client [firefox-android: bendk/new-fxa-client] #5851](https://github.com/mozilla/application-services/pull/5851)
> 
>     * [Bug 1856729 - Switch to new app-services FxaClient mozilla-mobile/firefox-android#3918](https://github.com/mozilla-mobile/firefox-android/pull/3918)
> 
> 
> > 3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> We also plan to use manual testing. However these metrics will be better for detecting low-frequency bugs.
> 
> > 4. Can current instrumentation answer these questions?
> 
> No.
> 
> > 5. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.
> 
> Measurement Description 	Data collection category 	Tracking bug
> FxA operation count (counter) 	Category 2 "Interaction data" 	[#5871](https://github.com/mozilla/application-services/issues/5871)
> FxA error count (labeled counter, with these categories: network, authorization, fxa_other, unexpected) 	Category 2 "Interaction data" 	[#5871](https://github.com/mozilla/application-services/issues/5871)
> 
> > 6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/
> 
> > 7. How long will this data be collected?  Choose one of the following:
> 
> I want to permanently monitor this data. (Ben Dean-Kawamura)
> 
> > 8. What populations will you measure?
> 
> All release channels, countries, and locales.
> 
> > 9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> Standard Firefox telemetry controls
> 
> > 10. Please provide a general description of how you will analyze this data.
> 
>     * When deploying changes to FxA, we will monitor changes in the telemetry.
> 
>     * As part of triage, we will check to see that the error rates are roughly stable.
> 
> 
> > 11. Where do you intend to share the results of your analysis?
> 
> The sync team
> 
> > 12. Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection? If so:
> 
> No
> 
> ┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3959) ┆Epic: Moving fxa-client functionality out of android-components

# Data Review Form (to be filled by Data Stewards)

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

* Yes, through the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/)

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.

* Yes, through the general "Send Usage Data" preference in the applications' settings.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

* Yes, this data will be permanently collected. Ben Dean-Kawamura (bdeankawamura@mozilla.com) will be monitoring.

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

* Category 2 - interaction data.

5) Is the data collection request for default-on or default-off?

* Default on.

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

* No. 

7) Is the data collection covered by the existing Firefox privacy notice? **If unsure: escalate to legal if:**

* Yes.

8) Does the data collection use a third-party collection tool? **If yes, escalate to legal.**

* No.

## Result

data-review+

**Comment by bendk** [comment]
Thanks for the review!  I just put the metrics PR on the merge queue.
