### ISSUE TITLE
Document our CI setup and how to maintain it

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#601]
(I'm doing a refresh of the docs setup in this repo and filing issues for things that I can't find, but want).

It's not obvious to me why we have all three of travis, circleci and taskcluster set up this repo, or which one I should look at for what reasons.

**Comment by thomcc** [comment]
This would be very valuable, the taskcluster bits are especially mysterious to me.

CC @ncalexan.

**Comment by thomcc** [comment]
Oh, huh. There's already docs here: https://github.com/mozilla/application-services/blob/master/automation/taskcluster/README.md

Not sure how complete they are, but I wasn't aware they existed.

**Comment by rfk** [comment]
My high-level questions start from:

* What gets built in travis, and why there rather than somewhere else?
* What gets built in circle, and why there rather than somewhere else?
* What gets built in taskcluster, and why there rather than somewhere else?

I can spelunk to find out the what, but I'd like to also understand the why.

**Comment by eoger** [comment]
I can answer some of these:

> What gets built in travis, and why there rather than somewhere else?

This is mostly legacy: they provide macOS machines, so we can build our iOS framework binaries. However, the machines are very slow on free mode and timeout if our build process takes too long (happened in the past!).

> What gets built in circle, and why there rather than somewhere else?

- Testing: CircleCI spins up docker instances *very* fast, which allows us to get some feedback on a PR almost immediately.

- iOS releases: Travis is going to go away because of reasons above. Taskcluster doesn't provision macOS machines, which means we would have to rent a macOS machine and install/maintain a taskcluster daemon on it. CircleCI provides managed macOS machines.

**Comment by rfk** [comment]
> What gets built in travis, and why there rather than somewhere else?

As of https://github.com/mozilla/application-services/pull/665 we're no longer using Travis.
