### ISSUE TITLE
sync15 should add /1.0/sync/1.5 to tokenserver url if not present

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#604]
On all other platforms the tokenserver url passed to sync doesn't have /1.0/sync/1.5 in it, and sync appends it. For some reason the fxa-client rust code does append this. If we're getting custom token server urls from users, they probably want to enter it the same as they do elsewhere, so we should append it if it's missing.

This should be trivial, I'd like to make sure that this difference wasn't intentional though.

@rfk / @eoger thoughts?

**Comment by rfk** [comment]
The `fxa-client` code is adding this when reading remote config from the server:

  https://github.com/mozilla/application-services/blob/master/components/fxa-client/src/config.rs#L125

I don't recall the reasoning that lead to that decision, but IMHO it seems reasonable to move that logic out of FxA and into the Sync code somewhere.  If in some future world we wanted to switch to using a `v1.6` of the sync protocol, it feels like we'd want to change that somewhere in the Sync code rather than in FxA.

@eoger do you recall any of the context that lead to the way it's current done?

**Comment by thomcc** [comment]
I know that initially sync15 did append this to the URL, then when hooking it up to FxA it turned out to be a problem. I remember being convinced that the place to fix this was in sync15, which happened in https://github.com/mozilla/application-services/commit/74d71ef5b0b95bfa4a8c67ca652367dc7f4fbca7#diff-d774a5afb93b88b44ef8b759ec84f0d0
