### ISSUE TITLE
logins: Handle when insertion/update creates dupes

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#617]
Currently we don't handle this, but we should so that other clients (or us in the future) don't get confused.

We shouldn't naively insert/update records so that they have the same (username, hostname) as existing records.

We should either return an error, or update the existing record to have the new data, not sure which is better.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-263)
┆Story Points: 2
┆Epic: Logins Component 1.0
┆Sprint: SYNC - end 2019-11-22

**Comment by rfk** [comment]
Does this currently put other clients at risk of syncing down bad data and getting stuck? Is this likely to involve e.g. a schema change or some other b/w-compat issue?

**Comment by mnoorenberghe** [comment]
The unique key of `(origin, formActionOrigin, httpRealm, username)` has been enforced in Toolkit for a long long time and code assumes you won't have two matching usernames for the same form so that, for example, when you type your username and blur it, your matching password gets filled (FxiOS also has this fill behaviour btw.). It's totally fine to have an http auth login with the same username as a form login on the same origin though.

Since this isn't yet implemented it's having to be [re-implemented in Lockwise](https://github.com/mozilla-lockwise/lockwise-android/pull/968) which is unfortunate.

**Comment by thomcc** [comment]
The story around dupes was on the discussion agenda with our bi-weekly meeting with the lockwise for well over 6 months, and every time we brought it up what decision to make was postponed.

**Comment by mnoorenberghe** [comment]
Since our two biggest consumers (Firefox on desktop and Android) assume that there aren't dupes I think we can go ahead and implement this check and we can change it later. Now that potential dupes have already been written we'll maybe need to handle existing bad data but I'm fine with doing that in a later issue and for now worry about preventing new dupes. It would be nice to enforce this at the DB layer with a `UNIQUE` constraint though…

**Comment by eliserichards** [comment]
If this issue can be prioritized relatively soon that would be great 😉

**Comment by mnoorenberghe** [comment]
In our meeting last night we agreed to not worry about existing duplicates for now but to prevent new ones as the first priority.

**Comment by cse-test-sync** [comment]
➤ Ana Medinac commented:

10/21: Thom to write steps on "How to". Nobody is started, leaving in To Do column

**Comment by thomcc** [comment]
@lougeniaC64 There are a lot of ways you can go about this, but this is how I'd do it. This should at least get you started, please let me know if there's anything unclear!

- Add a new method to `LoginDb` for validating logins. You should replace the existing calls to `login.check_valid()?` (example: https://github.com/mozilla/application-services/blob/master/components/logins/src/db.rs#L343) to calls to this method. It should perform the existing validity check, and then check that the item is not a duplicate. 
- A record is a duplicate if `hostname`, `formSubmitUrl`, `httpRealm`, and `username` are all equal. Note that some of these may be null, and that SQL considers `x == x` to be false if `x` is null.
- You'll check versus all non-overridden mirror records, and all non-deleted local records. An example of a query that grabs these is here: https://github.com/mozilla/application-services/blob/master/components/logins/src/db.rs#L998. See the header comment in https://github.com/mozilla/application-services/blob/master/components/logins/src/schema.rs for a description of what 'mirror' and 'local' mean here.
- You'll need to add a new error to https://github.com/mozilla/application-services/blob/master/components/logins/src/error.rs#L67, indicating a login is invalid because it's a duplicate.
- You'll also need to add support for this check to the Kotlin in-memory logins store we provide for testing purposes: The easy place to do this is [the existing validity check function](https://github.com/mozilla/application-services/blob/master/components/logins/android/src/main/java/mozilla/appservices/logins/MemoryLoginsStorage.kt#L257), which has access to it's `list` member, which contains a list of [`ServerPassword`](https://github.com/mozilla/application-services/blob/master/components/logins/android/src/main/java/mozilla/appservices/logins/ServerPassword.kt)s.

**Comment by linacambridge** [comment]
@lougeniaC64 If you expose the dupe-checking method, this will take care of #1983, too! 😄

**Comment by cse-test-sync** [comment]
➤ Lougenia Bailey commented:

Using my first application services bug to learn and grow. Progress can be tracked on [my branch|https://github.com/mozilla/application-services/compare/handle-insert-update-duplicates ( https://github.com/mozilla/application-services/compare/handle-insert-update-duplicates )].  Outstanding work on this bug is the Kotlin support Thom listed above.

**Comment by data-sync-user** [comment]
➤ Lougenia Bailey commented:

PR: https://github.com/mozilla/application-services/pull/2101
