### ISSUE TITLE
Re-indent our SQL

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#630]
Turning on rustfmt messed up our SQL indentation in many files. Eventually we should go through and fix this. It should be pretty mechanical.

**Comment by suhailsinghbains** [comment]
Hi, Can I please work on this, I am a newbie here.

**Comment by suhailsinghbains** [comment]
Hi @thomcc 
I want some help, which files do i need to change?

**Comment by rfk** [comment]
Hi @suhailsinghbains, thanks for your interest!  We recently added some introductory docs on contributing to this repo since it requires a bit of unusual setup.  A great first step would be to read through the new doc here:

  https://github.com/mozilla/application-services/blob/master/docs/contributing.md

And let us know if anything is unclear or could be improved.  If you're able to successfully run `cargo test --all` and have all the tests pass, you should have everything you need to contribute.

I've removed the "backlog" label from this issue, which means that it should come up for discussion in our weekly bug triage session, so I'll make sure we add some clear next steps during that discussion if we don't get to it before then.

**Comment by thomcc** [comment]
There are 2 main problems I'd like to get fixed here:

1. Cases where the indentation of the SQL doesn't match correctly, for example [this](https://github.com/mozilla/application-services/blob/master/components/logins/src/db.rs#L184-L213) or [this](https://github.com/mozilla/application-services/blob/master/components/logins/src/db.rs#L487-L496) (but not [this](https://github.com/mozilla/application-services/blob/master/components/logins/src/update_plan.rs#L100-L116)).
2. Cases where the `"` is on a line on its own and has equal indentation to the next line, such as [this](https://github.com/mozilla/application-services/blob/master/components/places/src/storage/history.rs#L473-L474) or [this](https://github.com/mozilla/application-services/blob/master/components/logins/src/db.rs#L295-L296) (but not [this](https://github.com/mozilla/application-services/blob/master/components/places/src/storage/history.rs#L779-L780))

Here where the indentation is wrong:
- files in https://github.com/mozilla/application-services/blob/master/components/logins/src, specifically db.rs and update_plan.rs
- Many of the files in https://github.com/mozilla/application-services/tree/master/components/places/src, primarily the items in storage and api

**Comment by thomcc** [comment]
I did this for logins since it was bugging me and I was touching those files anyway. Places work can still be done

**Comment by suhailsinghbains** [comment]
Okay thanks @thomcc
