### ISSUE TITLE
Logins: update modification date if any field data changed

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/application-services#729]
Desktop (and iOS) show a last modified date that doesn't appear to be tied to only changing the password, thus changes to the URL or username should update the last modified date.

Consider renaming `timePasswordChanged` to a generic name like `timeLastModified` to reflect that more than one field modification will update this.

Relevant Code: https://github.com/mozilla/application-services/blob/master/components/logins/src/db.rs#L415-L419

UI in desktop:
<img width="205" alt="image" src="https://user-images.githubusercontent.com/5495083/53766257-5e579b80-3ea0-11e9-87e9-fe0c2e2caf64.png">

**Comment by thomcc** [comment]
Note that renaming things like this is tricky since the name on the server needs to remain the same. Since we use the same code for serializing data for sending over the FFI as we do for serializing/deserializing data from the network, this requires some duplication (This is largely why #695 didn't rename formSubmitURL to formActionOrigin, despite that being a more accurate name).

In the future we'd like to use protobufs for sending the data over the FFI, making this duplication inevitable but autogenerated (although since the iOS logins code currently takes advantage of the JSON API to make things more convenient, this is tricky too).

**Comment by garvankeeley** [comment]
Maybe I am wrong that `timePasswordChanged` should update, and in fact, it is only for password changes. Desktop does not update this date  when I change the username, I should have checked that.

**Comment by garvankeeley** [comment]
Based on my last comment, I am closing thus bug as works as-intended. 
This is clearly how Desktop was designed to work, and iOS should do the same.
