### ISSUE TITLE
Remove SQLCipher from the Fenix megazord

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#760]
Fenix doesn't use the logins component, hence doesn't need SQLCipher.  Let's remove it from the Fenix megazord in order to reduce bundle size and remove one (among several) reasons to take a dependency on OpenSSL.

**Comment by thomcc** [comment]
https://github.com/mozilla/application-services/pull/307 does part of this, but is very out of date, and doesnt' handle fenix at all, obviously.

Doing this will require making the incantation to run all the rust tests in CI substantially more complex, and it may require that we do a `cargo clean` between building other things and the fenix megazord, due to how cargo features interact in workspaces (cargo will often add a feature to a crate if something else in the dependency tree requires it, even if it's in a roundabout way)

(That's basically why I didn't push that patch through back then, we didn't have a solid reason for needing this beyond it being tricky to compile sqlcipher in some cases. Now that we do, it's a different story)
