### ISSUE TITLE
Add minimum Rust version check and test against it

### ISSUE THREAD

**Issue by ncalexan** [mozilla/application-services#77]
Over in https://github.com/mozilla/mentat, we have a [Rust compiler version check](https://github.com/mozilla/mentat/blob/88c6a4b05ca41d3900c7dded53b928e4aa9c7ab8/build/version.rs) and we try to run Travis CI against that version (https://github.com/mozilla/mentat/blob/88c6a4b05ca41d3900c7dded53b928e4aa9c7ab8/.travis.yml#L8).

It would be nice if `application-services` culted that approach so that I don't have to translate error messages into compiler requirements.

**Comment by thomcc** [comment]
To be honest, I'm not sure it makes sense for us to depend on a version other than 'stable' until we have actual rust consumers.

**Comment by mhammond** [comment]
I don't think documentation would help with Nick's issue. It appears that cargo-culting the same version check as mentat might help Nick - what would it hurt? (IIUC, the mentat check is for an earlier version than current stable, so it's not obvious to me what issue this would cause)

**Comment by thomcc** [comment]
It would require a lot of changes to make our code work under 1.25, and I don't think there would be any benefit. If we want to add a version check it should be for 1.26, which the current AS code uses.

**Comment by mhammond** [comment]
yeah, that makes sense, thanks. Nick, is there any reason we can't bump mentat to 1.27 first?  I certainly agree with Thom that we don't want to "backport" our code to an earlier version than a current stable before we have any actual consumers.

**Comment by ncalexan** [comment]
> yeah, that makes sense, thanks. Nick, is there any reason we can't bump mentat to 1.27 first? I certainly agree with Thom that we don't want to "backport" our code to an earlier version than a current stable before we have any actual consumers.

I have said this in a few places: my position remains that the Rust ecosystem cannot expect all consumers to adopt a new "stable" release every 6 weeks indefinitely.  As a library hopefully to be consumed by many projects, I don't want Mentat to force consumers to adopt new "stable" releases as a condition of use.  I think that the Rust ecosystem is rapidly approaching the infrastructure/it just works level of maturity, where stability matters more than having the newest shiny features; although maybe we're not there yet.

All that to say I want us to fix a Rust feature set and continue to build against that; and Mentat chose whatever it did (1.25?) 'cuz that was what "stable" was at the time.  We can definitely bump to something later when we're ready to commit `application-services` to supporting a version for some long-ish period of time (6 months?  12 months?).  If that bump is now, that's fine by me.

**Comment by thomcc** [comment]
> my position remains that the Rust ecosystem cannot expect all consumers to adopt a new "stable" release every 6 weeks indefinitely. As a library hopefully to be consumed by many projects, I don't want Mentat to force consumers to adopt new "stable" releases as a condition of use...

It's not a condition of use, it's a condition of updating to the latest version. Note that most libraries just base themselves on stable, for example rusqlite. (OTOH serde supports all the way back to 1.13.0, so your stance isn't unheard of, but serialization has some unique concerns here).

>  As a library hopefully to be consumed by many projects...

Yeah, but neither mentat nor application-services are there yet. Using an older version of rust is a hurdle for development, and it's extremely unclear to me that we get anything out of it until we do have many dependents (I'd go as far as to say that it's unclear to me that we get much out of it even if we do have many dependents, `rustup update` is not difficult and the rust team is quite conscious of only making forward compatible changes).

All that said, if you plan on updating once and for all, it might make sense to wait on the bump until the big "rust 2018" release. Or it might make sense to pin on one of the versions before it and explicitly *not* update (although, I think this is the rust team's nightmare, since presumably the thing they're trying to avoid with the epoch system is a python 2/3-esque split).

**Comment by vladikoff** [comment]
We kind of discussed this in https://github.com/mozilla/application-services/issues/1210

Closing this for now until we need to look at this again
