### ISSUE TITLE
History API: delete individual visit API request

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#840]
Fenix UI has ability to delete individual visits, but the provided APIs don't expose a direct way to do this. We can use the range APIs with a narrow timestamp range, but that doesn't guarantee that we won't affect visits for other URLs.

Is it feasible to add a `deleteVisitFor(url, timestamp)` method? Timestamp would be the exact timestamp we get back from `getVisitInfos`. This is essentially using (url, timestamp) pair as a compound key for a visit. I realize that doesn't exactly map to the schema, but it _should_ map to how data is stored most of the time (unless that visit disappears, somehow).

**Comment by thomcc** [comment]
We actually have this, it's https://github.com/mozilla/application-services/blob/f4381aac8d1315e983fb8b7e1ec99db1102903d7/components/places/android/src/main/java/mozilla/appservices/places/PlacesConnection.kt#L636-L647

Closing, please reopen if there's something I'm missing. I'm assuming you just missed it since it's at the bottom there.

**Comment by grigoryk** [comment]
Ah, my bad Thom!
