### ISSUE TITLE
Expose bookmark syncing

### ISSUE THREAD

**Issue by mhammond** [mozilla/application-services#850]
#723 is landing initial support for bookmark syncing, but it's not clear how this should be exposed.

History has a [helper function](https://github.com/mozilla/application-services/blob/master/components/places/src/history_sync/store.rs#L98) which supports sync, but that's too simplistic and assumes history syncing is the only engine supported by the component (eg, it stores the "global state" which applies to both history and bookmarks. places-api [has a wrapper around this wrapper](https://github.com/mozilla/application-services/blob/master/components/places/src/api/places_api.rs#L162), which is probably where we should add this support, removing the wrapper in store.rs.

**Comment by grigoryk** [comment]
@mhammond will this be part of the SyncManager work? IIUC either way changes will be required to A-C SyncManager, and it'll be nice to only have to make them once for the shippable solution. I understand if deadlines and deliverables/milestones get in the way though :)

**Comment by jdragojevic** [comment]
My understanding:

#892 is some prep work for Sync Manager.  It makes sense to finish it and merge it before exposing sync because of the scope of the changes, everything would have to be retested and there would not be a time savings.

Plan - with a goal to be complete by 12-April
1. land #892 for the sync manager work (which resolves #784 and #761)
2. expose syncing
3. Ready for integration by Fenix team.
