### ISSUE TITLE
LibreSSL? BoringSSL?

### ISSUE THREAD

**Issue by colinje** [mozilla/application-services#898]
I noticed the project uses openssl and was wondering if there was any discussion on switching to libressl or boringssl? Has the issues of government tampering with openssl been alleviated/audited to satisfy mozilla's concern for privacy?

I am out of the loop when it comes to these libraries, but was curious why mozilla wouldn't want to switch to something more.....trustworthy?

**Comment by thomcc** [comment]
See #752. The switch will be to NSS, not to BoringSSL/LibreSSL

**Comment by thomcc** [comment]
Note that for the time-being, we'll likely still rely on OpenSSL for encrypting logins storage for lockbox, (switching awayf from that is nontrivial) however I don't think as many concerns exist in this case, since it's entirely used for on-disk encryption, and not for anything that touches the network (let alone SSL/TLS)

**Comment by colinje** [comment]
Thank you for the quick response! This answers my questions and closing the issue :)
