### ISSUE TITLE
Audit for PII in error messages

### ISSUE THREAD

**Issue by jdragojevic** [mozilla/application-services#909]
Audit for PII in error messages

**Comment by jrconlin** [comment]
Check all files under the `/application-services` root.

Criteria used:
*rust* (`info!`,`warn!`,`error!`,`critical!`, `print!`, `println!`)
* we do a pretty good job of calling these as `log::...` probably should make that a pattern for the future.
* Aside from example code, errors in production run code either are fully static strings, include general exceptions, or data otherwise not including Personal Information. 
* `print!` and `println!` calls are restricted to examples and tests

*kotlin* (`Log.*`, `println`)
* One `println` which is [only used when logging failed](https://github.com/mozilla/application-services/blob/master/components/rc_log/android/src/main/java/mozilla/appservices/rustlog/RustLogAdapter.kt#L171).
