### ISSUE TITLE
Move crypto primitives to rc_crypto/NSS

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#955]
We need to replace each direct call to OpenSSL/ring in our repository by calls to `rc_crypto` backed by NSS.

* [x] RNG
* [x] HMAC-SHA-256
* [x] HKDF-SHA-256
* [ ] AEAD-AES-256-CBC-HMAC-SHA256
* [ ] AEAD-AES-128-GCM
* [ ] AEAD-AES-256-GCM
* [ ] ECDH agreement on P-256

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-155)
┆Story Points: 2
┆Sprint: SYNC - 2019-07-19
┆Epic: Trusted Crypto

**Comment by rfk** [comment]
Since we plan to implement this across several PRs, I stealth-edited a checklist into the main issue comment to help us ensure we don't miss any.  @eoger please update as appropriate.

**Comment by thomcc** [comment]
it might be worth noting that https://github.com/mozilla/application-services/blob/master/components/sync15/src/util.rs#L11-L15 doesn't actually need to use a CSPRNG. It's all kinds of overkill. (also `bytes` should be an array on the stack and not a vec, but that's neither here nor there)

**Comment by rfk** [comment]
>  AEAD-AES-256-CBC-HMAC-SHA256

Since I was looking at ring's API anyway, I had a bit of a poke at what it would look like to do sync's legacy encryption mode as an AEAD.  I think it would work OK structured along these lines:

* An `rc_crypto::aead::Algorithm` struct very similar to the one from `ring`, which says what AEAD algorithm you're doing and tells you the `key_len`, `tag_len`, and `nonce_len`.
  * An `AES256_CBC_HMAC_SHA256` instance of this where `key_len() = tag_len() = 32` and `nonce_len() = 16`
* An `rc_crypto::aead::Nonce` struct similar the one from `ring`, which encapsulates a nonce and forces to you acknowledge that it should only be used once.
  * Unlike `ring`, we'd have to have specify the algorithm in use when creating a nonce, because `AES256_CBC_HMAC_SHA256` uses a non-standard length of 16 bytes.  Something like: `Nonce::assume_unique_for_key(&Algorithm, value)`
  * We could also add `Nonce::random(&Algorithm)` for generating them at random, but it would have to check that the`nonce_len() >= 16` for safety.
* An `rc_crypto::aead:Aad` struct identical to the one from `ring`.
  * Sync's crypto doesn't need this, and would just use `Aad::empty()` always.
* A pair of methods `rc_crypto::aead::open()` and `rc_crypto::aead::seal()` that work like the ones in `ring`, but just return a fresh buffer instead of requiring us to manually manage the buffer so it can be operated on in-place.
  * (I'm not opposed to in-place variants, it just seems like a hoop we don't tend to jump through in the rest of our code).

With those, decrypting a BSO would look like:

```
let key = aead::OpeningKey(&aead::AES256_CBC_HMAC_SHA256, kSync);
let nonce = aead::Nonce::assume_unique_for_key(key.algorithm(), bso["iv"]);
let ciphertext = bso["ciphertext"] + bso["hmac"];  // or however you concat bytearrays in rust...
let plaintext = aead::open(key, nonce, aead::Aad::empty(), ciphertext);
```

And encrypting a BSO would look like:

```
let key = aead::SealingKey(&aead::AES256_CBC_HMAC_SHA256, kSync);
let nonce = aead::Nonce::random(key.algorithm());
let ciphertext = aead::seal(key, nonce, aead::Aad::empty(), plaintext);
bso["ciphertext"] = ciphertext[..-key.algorithm().tag_len()];
bso["hmac"] = ciphertext[-key.algorityhm().tag_len()..];
```

What's nice about structuring it this way, is that we can remove the various "`// Important!`" warnings in the current sync crypto code, [such as this one](https://github.com/mozilla/application-services/blob/a5e8adb0bfa6cfe5fcff2a709ab979d2b55fc88a/components/sync15/src/key_bundle.rs#L128), because it's hard to use this API incorrectly.

Anyway, food for thought when we come around to implementing that part...

**Comment by bug-mirror** [comment]
from mtg: in progress..

**Comment by rfk** [comment]
> AEAD-AES-256-CBC-HMAC-SHA256

@eoger pointed out a wrinkle in the proposal above that I wanted to note explicitly.  The sync1.5 encryption scheme uses a hmac of the *base64 encoded* ciphertext for authentication. In order to do the authenticate-and-decrypt operation in a single step, you have to either pass in the base64-encoded ciphertext, or you have to decode it into bytes on the caller side, and re-encode it as base64 on the callee side.  The first seems yuck; the second seems needlessly expensive.

I expect that this design decision was made way back in the day, in order to minimize the surface area of code handling unauthenticated data; similar to what's suggested [here](https://www.daemonology.net/blog/2009-06-24-encrypt-then-mac.html) it means we don't attempt to base64-decode untrusted data. In practice these days, I expect we're more likely to mess up manual HMAC verification than we are to have an exploitable bug in our base64-decoding routine.

**Comment by martinthomson** [comment]
I'm fairly certain that NSS won't want to take an AEAD that includes a base64 conversion.  NSS has a base64 encoder/decoder, but it's most certainly not constant time, so even if it weren't operating on the plaintext, we wouldn't want to run it inside the AEAD.

That means that - for backward compatibility - you will be assembling that primitive yourself.

That only suggests greater urgency for moving to a proper AEAD (ChaCha20-Poly1305 or AES-256-GCM probably).

**Comment by rfk** [comment]
> That means that - for backward compatibility - you will be assembling that primitive yourself.

Yep, understood.

**Comment by cse-test-sync** [comment]
➤ Vladislav Filippov commented:

waiting for QA
