### ISSUE TITLE
Migrate away from SQLCipher

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#960]
Implementing an NSS crypto backend is too much work. We should have a plan to move away from SQLCipher.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-729)
┆Epic: Logins uniffi and update
┆Sprint: SYNC - 2021-05-14

**Comment by thomcc** [comment]
My rough plan involves encrypting just the username and password strings in the DB, similar to the way we do on desktop.

The big issue with this is that we still actually need to keep SQLCipher around while we migrate away from it, otherwise users would lose data when they update to the version where we removed sqlcipher. I don't know how best to do this.

**Comment by rfk** [comment]
One of the outcomes from today's program review, is that we should arrange a smaller "architecture review" style meeting to discuss integrating the logins store into desktop. This sounds like a great topic to tackle as part of that meeting. /cc @linuxwolf.

**Comment by eoger** [comment]
Update: we have implemented an NSS backend for sqlcipher (which should be merged upstream at some point in the future).
I'm keeping the issue open as we might have reasons to move away from sqlcipher in the future anyway but feel free to close it if that last assumption is wrong.

**Comment by lougeniaC64** [comment]
@mhammond I've outlined a rough ROUGH draft of the work that I think is required to remove SQLCipher from logins. However having read the comments on this ticket, I'm honestly not sure when we would be able to actually remove the SQLCipher references, but this work below will at least put us on the path to do so.

- Move the [encryption logic](https://github.com/mozilla/application-services/blob/main/components/autofill/src/encryption.rs) from autofill to [the support crate](https://github.com/mozilla/application-services/blob/main/components/support) so that it can be used in logins and autofill
  - Honestly not sure about the uniffi implications but I think if we import the encryption logic from the support crate and expose it as a public module in autofill that _should_ work
- Update the logins schema and structs replacing the `username` and `password` fields with `username_enc` and `password_enc` similar to [autofill’s cc_number_enc field](https://github.com/mozilla/application-services/blob/main/components/autofill/sql/create_shared_schema.sql#L57)
  - Update calling code and tests
- Update [the logins mirror table](https://github.com/mozilla/application-services/blob/main/components/logins/src/schema.rs#L161) so that the fields are an encrypted JSON payload similar to [autofill](https://github.com/mozilla/application-services/blob/main/components/autofill/sql/create_shared_schema.sql#L73)
  - Update calling code and tests
- Add migration code for the above schema changes
- Add logic to scrub encrypted data similar to[autofill](https://github.com/mozilla/application-services/pull/4029)
- Update sync logic to encrypt/decrypt incoming/outgoing logins

Things I'm not so sure about:
- How having these two encryption schemes implemented at the same time will work in the wild
- When we'd actually be able to remove SQLCipher from logins
- How this work will be coordinated
  - I think moving the encryption logic to the support crate, the schema changes and the migration, the scrub logic, and the sync updates could be four distinct pieces of work. However, I'm not sure how much of this can be parallelized.

**Comment by mhammond** [comment]
Thanks Lougenia, that sounds about right. A few comments:

* TBH, I'm not too bothered by moving the encryption to a support crate - it's only about 30 lines of code and no "logic" as such, so a simple copy would be fine IMO (I heard someone say once that the time to generalize something is the *third* time you need something, not the second). I'm not strongly against doing this if someone is strongly for it, but I'm not :)

* I think the migration is going to be different than a "normal" migration - we'll almost certainly be migrating between 2 different database files. This also touches on the "two encryption schemes implemented at the same time" aspect - I don't think we will in practice - each database file will use its own scheme, and both databases will only be opened at the same time during the one-shot migration window.

* Re removal of sqlcipher: I think our intent should be that sqlcipher is only used in the migration code, and thus can be finally removed once we decide to stop supporting migrations.

* The Android and iOS side of the world will probably want their own tickets - eg, they will now be getting the `_enc` fields, and will need to call the encrypt/decrypt functions. The FFI part of this is straight forward, so if necessary can be done before uniffi (in which case it will be done twice, but the second time will be trivial) or after. The real challenges here will be in the android-components and firefox-ios repos. Migrations will also need work in these repos (the migration will need *both* keys)

**Comment by lougeniaC64** [comment]
>     * I think the migration is going to be different than a "normal" migration - we'll almost certainly be migrating between 2 different database files. This also touches on the "two encryption schemes implemented at the same time" aspect - I don't think we will in practice - each database file will use its own scheme, and both databases will only be opened at the same time during the one-shot migration window.

Re-stating this to ensure I understand, on an individual user level the two database files, one with the current sqlcipher implementation and the other with the new per-field encryption implementation, will only be functional during the migration. Afterwards the sqlcipher implementation will be inactive and/or marked for deletion. However, across our user base we will need to keep the current sqlcipher implementation (including [the functions](https://github.com/mozilla/application-services/blob/d15dff1413f47a249e11848aa9dbadcb546457d3/components/logins/src/db.rs#L114) to open the db with encryption keys and SALTs) until the migration period is complete. Is that correct?

If this is the case we would need to create new functions to manage database connections for the new database file in addition to the work I identified above.

>     * Re removal of sqlcipher: I think our intent should be that sqlcipher is only used in the migration code, and thus can be finally removed once we decide to stop supporting migrations.

I'm assuming we wouldn't be actually removing the sqlcipher code until the migration period is complete, right?

**Comment by mhammond** [comment]
> If this is the case we would need to create new functions to manage database connections for the new database file in addition to the work I identified above.

I think the existing functions are probably OK, but will manage the new DB. `open_and_get_salt` would probably just move to a private function in the migration code.

And yeah, because the sqlcipher code will be needed to do the migration, we can't delete it until we declare we will not be doing any more migrations.

**Comment by lougeniaC64** [comment]
> I think the existing functions are probably OK, but will manage the new DB. `open_and_get_salt` would probably just move to a private function in the migration code.

So I'm assuming whether we call [open](https://github.com/mozilla/application-services/blob/72b827c3e0f883163762857fd766df1aeb060725/components/logins/src/db.rs#L97), which would work for the new database file, or say `open_with_salt` would be a part of the changes we'd needed to make in the consumers' code. And that the salt function would be some of the logic we'd pull after the migration period.

**Comment by mhammond** [comment]
Yeah - something like `open_with_salt` goes away entirely, and a new function, say, `migrate_with_salt()` might be exposed instead (probably with a signature something like `open_and_get_salt(new_path: impl AsRef<Path>, old_path: impl AsRef<Path>, encryption_key: &str)` and which must be called before the "normal" `open` (which just takes the new path)

**Comment by bendk** [comment]
I think I have something close to ready, but I'd like to check on some things:

  - Not only will the open_with_salt() methods go away, but it seems like the functionality will go away.  This seems fine to me, it looks like the main reason for salt is to secure the database with a passphrase, which I don't think we do.  Just wanted to double check on this one though.
  - I just implemented the migrate() function in LoginDb.  Should I also expose it in LoginStore() to make it accessible to consumers?

**Comment by lougeniaC64** [comment]
>     * Not only will the open_with_salt() methods go away, but it seems like the functionality will go away.  This seems fine to me, it looks like the main reason for salt is to secure the database with a passphrase, which I don't think we do.  Just wanted to double check on this one though.

FWIW, this is my understanding as well. Once the migration period is over we shouldn't need the salt-related functionality

>     * I just implemented the migrate() function in LoginDb.  Should I also expose it in LoginStore() to make it accessible to consumers?

I'm not sure about this one honestly. I had assumed that'd we'd use the current `upgrade` logic to migrate users but we might want to expose the migrate functionality so consumers have more control over user migrations. For now, let's create a new issue for this and punt on it until the encryption work is complete and we're working on the consumer integration piece.

**Comment by mhammond** [comment]
> * I just implemented the migrate() function in LoginDb.  Should I also expose it in LoginStore() to make it accessible to consumers?

As Lougenia said, this isn't clear. I think it will be up to us to propose the api and mechanics for the migration. We'll probably need some way of knowing whether we actually want to migrate (ie, we probably need to know whether we actually migrated in the past.) But what if we failed due to, say, no disk space - should we keep trying? (see below, the answer might need to be "no")

In practice though, I think we will be insisting on successful migration before we work in any way. We aren't setting things up so that a failed migration will fall back to using the old DB (thank goodness, as that would be a world of hurt I think) - and if we allow the component to work in that case and they (say) create a new login, we end up in a dilemma for the next migration attempt - it can no longer assume an empty DB. So "failed migration" == "component doesn't work" - which kinda argues *against* giving the app much control over this.

One option might be to delete the old DB on success. If it exists, it means we must migrate before we work. If the new DB also exists we should assume it was a failed partial migration, so it should be deleted before the migration? That's going to be a problem for, say, old corrupt DBs - it doesn't matter how often we try we will never succeed.

Or maybe we just attempt to migrate once and treat failure as "too bad" - I think that's what we do for the Fennec -> Fenix migration. So in that scenario, the new DB existing on disk is enough for us to assume no migration is necessary.

(Regardless, I think we will want to ensure the old DB is deleted, as technically it still holds the user's logins - the user saying "delete all logins from this device" might be upset to learn there's still a DB holding some.)

We probably need to loop the Android ppl in, cc @grigoryk

**Comment by bendk** [comment]
> So "failed migration" == "component doesn't work" - which kinda argues against giving the app much control over this.

This seems like the case to me too.  If the migration fails, then I can't see a better path forward than just deleting the data and starting from scratch.  In theory, we might be able to fix some issues with an upgrade, but by that time they've already been using the places DB and saving new entries, so it would be serious work to restore the data for the user.  Even if we could, it seems like we would need to build some sort of UI to inform the user what's happening and make sure they actually want all the data restored.

Can anyone think of a better way to handle this?

> One option might be to delete the old DB on success. If it exists, it means we must migrate before we work. If the new DB also exists we should assume it was a failed partial migration, so it should be deleted before the migration? That's going to be a problem for, say, old corrupt DBs - it doesn't matter how often we try we will never succeed.

If we went this way, then I think the top-level migration function should catch any errors and delete the old file.  That way corrupt DBs get deleted and the user doesn't get stuck in a loop when there's corrupted data.  I think this would fail if the code panicked rather than returned an error, but some panics might be recoverable, like a memory error.  We also would want to retry the migration on power failures or something like that.

**Comment by mhammond** [comment]
Oh, I meant to say, recording (then remembering to watch) telemetry is our typical justification for this kind of brazenness!

**Comment by lougeniaC64** [comment]
Speaking of telemetry, do we want to collect migration specific telemetry? We didn't have our current triage process during the fenix migration so I don't recall how valuable those metrics were at the time.

**Comment by rfk** [comment]
👋🏻 hello, I am so excited to see this discussion moving forward that I just had to drop in here and catch up on it all!

> * Not only will the open_with_salt() methods go away, but it seems like the functionality will go away.  This seems fine to me, it
> looks like the main reason for salt is to secure the database with a passphrase, which I don't think we do.  Just wanted to
> double check on this one though.

Indeed all this "let the app provide an explicit salt" stuff should be able to safely go away after the migration. The reason behind it is in https://github.com/mozilla/application-services/issues/2100 if you're curious, and it exists entirely to work around some hackery in the way that iOS manages system resources. In the post-migration world, the file on disk will be an ordinary sqlite database, and the hackery will not be needed.

**Comment by jdragojevic** [comment]
I am actually closing this gh issue because the Jira equiv is an epic with all the work scoped and a bunch of tickets for the breaking.
